### ISSUE TITLE
tracking: support for golang ORM library 'xorm'

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#10131]
### Is your feature request related to a problem? Please describe.

XORM: https://xorm.io/

- [x] pg_tables https://www.postgresql.org/docs/current/view-pg-tables.html
    - [x] tablename
    - [x] schemaname
- [x] INFORMATION_SCHEMA.COLUMNS https://www.postgresql.org/docs/current/infoschema-columns.html 
    - [x] column_default
    - [x] character_maximum_length
- [x] CHAR
The actual query:

```sql
SELECT column_name, column_default, is_nullable, data_type, character_maximum_length, description,
    CASE WHEN p.contype = 'p' THEN true ELSE false END AS primarykey,
    CASE WHEN p.contype = 'u' THEN true ELSE false END AS uniquekey
FROM pg_attribute f
    JOIN pg_class c ON c.oid = f.attrelid JOIN pg_type t ON t.oid = f.atttypid
    LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = f.attnum
    LEFT JOIN pg_description de ON f.attrelid=de.objoid AND f.attnum=de.objsubid
    LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
    LEFT JOIN pg_constraint p ON p.conrelid = c.oid AND f.attnum = ANY (p.conkey)
    LEFT JOIN pg_class AS g ON p.confrelid = g.oid
    LEFT JOIN INFORMATION_SCHEMA.COLUMNS s ON s.column_name=f.attname AND c.relname=s.table_name
WHERE n.nspname= s.table_schema AND c.relkind = 'r'::char AND c.relname = 'a' AND f.attnum > 0 ORDER BY f.attnum;
```

**Comment by yezizp2012** [comment]
The missing issue about the `char` type casting will be addressed upstream: https://gitea.com/xorm/xorm/pulls/2278

**Comment by yezizp2012** [comment]
> The missing issue about the `char` type casting will be addressed upstream: [gitea.com/xorm/xorm/pulls/2278](https://gitea.com/xorm/xorm/pulls/2278)

Merged.
