### ISSUE TITLE
Tracking(connector): new Source DDL syntax

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#10214]
new syntax https://www.notion.so/risingwave-labs/Source-New-DDL-Design-733c586e98574c0db2e11a1a4ca7dda3 
- [x] improve planner test for different connectors and formats
- [x] refactor the resolve source schema
    - [x] https://github.com/risingwavelabs/risingwave/pull/10192 
    - [x]  https://github.com/risingwavelabs/risingwave/pull/10195
- [x] use `FORMAT ... ENCODE ...` to replace `ROW FORMAT`
    - [x] https://github.com/risingwavelabs/risingwave/pull/10561
    - [x] https://github.com/risingwavelabs/risingwave/pull/10768
