### ISSUE TITLE
Tracking: Investigate performance of kinesis source

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#10238]
- [ ] Either Setup some data snapshot. This will be the fixed data set for performance benchmark of kinesis. We should use this snapshot for kafka as well.
- [ ] OR benchmark via nexmark-bench.
- [ ] Benchmark q0/q1 with and without blackhole sink, see the max throughput of kinesis source.
- [ ] Benchmark q0/q1 with and without blackhole sink, see the max throughput of kafka. This used as comparison.

Related:
- [ ] https://github.com/risingwavelabs/risingwave/issues/10054
