### ISSUE TITLE
Tracking: Integration with DataGrip

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#10347]
- [x] https://github.com/risingwavelabs/risingwave/issues/10346
- [x] https://github.com/risingwavelabs/risingwave/issues/10339
- [x] https://github.com/risingwavelabs/risingwave/issues/11053
- [x] #11235 
- [x] #11258 
- [x] #11272 
- [x] #11689 
- [ ] #11948 
- [ ] #12021
- [x] #14224

**Comment by TennyZhuang** [comment]
new bug

```
Failed to retrieve user types in dev.information_schema. [XX000] ERROR: ParseError: Bind error: failed to bind expression: pg_catalog.obj_description(t.oid, 'pg_type'). Caused by: Feature is not yet implemented: unsupported function: "obj_description" Tracking issue: https://github.com/risingwavelabs/risingwave/issues/112 Server SQLState: XX000. dev.information_schema. [XX000] ERROR: ParseError: Bind error: failed to bind expression: p.proargtypes. Caused by: Item not found: Invalid column: proargtypes
```

**Comment by ZhicongZheng** [comment]
hi team, Is there any plan to continue supporting it? I'm currently using DataGrip 2025.2 and RisingWave 2.5.

**Comment by DoseOfCode** [comment]
bump
