### ISSUE TITLE
Tracking: enhance the auto cherry-pick GitHub Action

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#10401]
We have added a GitHub action:
https://github.com/risingwavelabs/risingwave/blob/main/.github/workflows/cherry-pick-to-release-branch.yml
to automatically open a corresponding pull request to the release candidate branch if the original pull request is merged and labeled with `need-cherry-pick-v0.19`.

Some further enhancements:
- [x] ~The release candidate branch in the workflow is now fixed. We may want to make it flexible, i.e. merge to the branch specified by the label. (since not many branches to maintain, probably OK)~
- [x] ~License-header-check somehow cannot be triggered automatically in the corresponding PR.~ Removed this check
- [x] ~Notify the author~ create an issue that cherry-picks fail and thus PR is not created due to conflicts and needs manual fix first.
- [x] Link the original PR in the corresponding PR description.
- [x] Label an already merged PR to trigger a cherry-pick one to the release candidate branch.

Feel free to propose more ideas!
