### ISSUE TITLE
Tracking: rust version of iceberg sink.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#10641]
This issue tracks the implementation of rust version of iceberg sink.

## Phase 1

In phase 1, we will focus on implementing an append-only iceberg sink.

### Iceberg rust client

- [x] https://github.com/icelake-io/icelake/issues/37
- [x] https://github.com/icelake-io/icelake/issues/38
- [x] https://github.com/icelake-io/icelake/issues/74
- [x] https://github.com/icelake-io/icelake/issues/39
- [x] https://github.com/icelake-io/icelake/issues/142

### Risingwave sink

- [x] #10642
- [x] #10643
- [x] #11650
- [x] #11652
- [x] #11775
- [x] #11776

## Phase 2

In phase 2, we we add update/delete for iceberg sink.

### Iceberg rust client

- [x] https://github.com/icelake-io/icelake/issues/40
- [x] https://github.com/icelake-io/icelake/issues/41
- [x] https://github.com/icelake-io/icelake/issues/172
- [x] #12221
- [x] https://github.com/icelake-io/icelake/issues/206

### Risingwave sink

- [x] https://github.com/icelake-io/icelake/issues/39
- [x] #12352
- [ ] #12016
- [x] #12326
- [x] #12721
- [ ] #13155
- [ ] #13897
- [x] #13898
- [x] #13899
- [x] #13900

**Comment by Xuanwo** [comment]
Let's rock!

**Comment by xxchan** [comment]
track on individual issues instead.
