### ISSUE TITLE
Tracking: more metrics for join operator

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#10760]
- [ ] selectivity.
- [ ] total storage size. This may already be solved by #9013 as the size of internal tables can also be queried by `pg_table_size`.
- [ ] total records count.  The tricky thing is how we can make it durable, i.e. how do we store this metrics
- [ ] row_length. Probably a histogram?

cc: @neverchanje

**Comment by fuyufjh** [comment]
I think some of the listed things are actually state table's statistics. 🤔 If so, it should be done as another kind of statistics of tables similar with estimated row count.

@lmatz Can you elaborate more on your idea?

**Comment by lmatz** [comment]
For `total records count` count, I agree it is actually state table' statistics.

The main motivation is that
right now, we have the cache miss rate, but we don't know the total number of records, so it is hard to judge whether
the cache miss rate actually makes sense.

For example, suppose we have a cache miss rate of 50%, which looks very bad. 
But if the total number of records is much larger than the number of records being cached, then it is actually not that bad.
I suspect it may be useful when clients have questions about the cache misses.

`Estimated row count` seems good enough as we just want to have a general idea. I can live with that


`row_length` I believe it was @neverchanje's idea

From my own perspective, it may also be useful when dealing with clients, answering questions such as why only XXX number of records are cached -> because the row length is huge,

But I forgot what @neverchanje 's original intention

**Comment by fuyufjh** [comment]
According to your reply, it still sounds like table's statistics instead of operator metrics.

It's doable but might introduce some additional cost. Not quite sure about this part.

Waiting for more inputs from @neverchanje

**Comment by fuyufjh** [comment]
Any updates? Ping @lmatz @neverchanje
