### ISSUE TITLE
tracking: Improving hdfs support.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#10783]
For details, please refer to #10575.

- [x] Create two images for different hadoop versions: 2.x and 3.x
- [x] Create an example to use k8s's configmap to allow user to pass hadoop config dirs to risingwave.
- [x] Update doc to tell user to create new image based on risingwave's image so that they can use patched hadoop client.

cc @wcy-fdu @arkbriar

**Comment by fuyufjh** [comment]
Is it possible to add the test in intergration tests? I don't think cloud team has bandwith to add HDFS as storage backend for us.

**Comment by arkbriar** [comment]
I believe the HDFS support is mature enough, both kernel's and operator/helm chart's. The problem left should be the support from the test driver, a.k.a. the kube-bench cc. @huangjw806

**Comment by wcy-fdu** [comment]
> I believe the HDFS support is mature enough,

+1, currently we has supported docker compose on HDFS and k8s on HDFS, and the remain work is to create real HDFS cluster and build test pipeline for it. We can go ahead when test team has bandwidth.
