### ISSUE TITLE
Tracking: Support TPC-H Queries (for Java frontend)

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#110]
Currently we've implemented almost all necessary operators and expressions required by TPC-H. This issue tracks bug-fix and implementation of TPC-H queries.

**A query is marked as supported iff. it has been added to the end-to-end test.**

## SQL Features in Queries

| Query | Group-by (Aggregation) | Order-by (Sort/TopN) | Join | Non-Correlated Subquery | Correlated Subquery | CTE / View |
|---|---|---|---|---|---|---|
| Q1 | ✔️ | ✔️ |  |  |  |  |
| Q2 |  | ✔️ | ✔️ |  | ✔️ (value in filter) |  |
| Q3 | ✔️ | ✔️ | ✔️ |  |  |  |
| Q4 | ✔️ | ✔️ |  |  | ✔️ (exists) |  |
| Q5 | ✔️ | ✔️ | ✔️ |  |  |  |
| Q6 | ✔️ (simple) |  |  |  |  |  |
| Q7 | ✔️ | ✔️ | ✔️ | ✔️ (table) |  |  |
| Q8 | ✔️ | ✔️ | ✔️ | ✔️ (table) |  |  |
| Q9 | ✔️ | ✔️ | ✔️ | ✔️ (table) |  |  |
| Q10 | ✔️ | ✔️ | ✔️ |  |  |  |
| Q11 | ✔️ | ✔️ | ✔️ |  | ✔️ (value in filter) |  |
| Q12 | ✔️ | ✔️ | ✔️ |  |  |  |
| Q13 | ✔️ | ✔️ | ✔️ (outer) | ✔️ (table) |  |  |
| Q14 | ✔️ (simple) |  | ✔️ |  |  |  |
| Q15 | ✔️ | ✔️ | ✔️ |  | ✔️ (value in filter) | ✔️ |
| Q16 | ✔️ | ✔️ | ✔️ |  | ✔️ (not in) |  |
| Q17 | ✔️ (simple) |  | ✔️ | ✔️ (table) |  |  |
| Q18 | ✔️ | ✔️ | ✔️ |  | ✔️ (in) |  |
| Q19 | ✔️ (simple) |  | ✔️ |  |  |  |
| Q20 | ✔️ | ✔️ | ✔️ | ✔️ (in & table) |  |  |
| Q21 | ✔️ | ✔️ | ✔️ |  | ✔️ (exists) |  |
| Q22 | ✔️ | ✔️ |  | ✔️ (table) | ✔️ (not exists & value in filter) |  |

## Batch

- [x] Batch: TPC-H Q1
- [x] singularity-data/risingwave-dev#177
- [x] singularity-data/risingwave-dev#439
- [x] singularity-data/risingwave-dev#296
- [x] singularity-data/risingwave-dev#440
- [x] Batch: TPC-H Q6
- [x] singularity-data/risingwave-dev#441
- [x] singularity-data/risingwave-dev#443
- [x] singularity-data/risingwave-legacy#2392
- [x] singularity-data/risingwave-legacy#2393
- [x] singularity-data/risingwave-legacy#2394
- [x] singularity-data/risingwave-dev#217
- [x] singularity-data/risingwave-legacy#2422
- [x] singularity-data/risingwave-legacy#2423
- [x] singularity-data/risingwave-dev#272
- [x] singularity-data/risingwave-legacy#2426
- [x] singularity-data/risingwave-legacy#2427
- [x] singularity-data/risingwave-legacy#2428
- [x] singularity-data/risingwave-dev#276
- [x] singularity-data/risingwave-dev#277
- [x] singularity-data/risingwave-dev#278
- [x] singularity-data/risingwave-dev#279

## Streaming

- [x] Streaming: TPC-H Q1
- [x] singularity-data/risingwave-dev#178
- [x] singularity-data/risingwave-legacy#1907
- [x] singularity-data/risingwave-dev#179
- [x] singularity-data/risingwave-legacy#1908
- [x] Streaming: TPC-H Q6
- [x] singularity-data/risingwave-legacy#2638
- [x] singularity-data/risingwave-legacy#2644
- [x] Streaming: TPC-H Q9
- [x] singularity-data/risingwave-legacy#2556
- [ ] singularity-data/risingwave-dev#490
- [x] singularity-data/risingwave-legacy#2839
- [x] singularity-data/risingwave-legacy#2840
- [x] singularity-data/risingwave-legacy#2890
- [x] singularity-data/risingwave-dev#496
- [x] singularity-data/risingwave-dev#491
- [x] singularity-data/risingwave-legacy#2897
- [x] singularity-data/risingwave-legacy#1911
- [x] singularity-data/risingwave-dev#497
- [ ] singularity-data/risingwave-dev#492
- [ ] singularity-data/risingwave-dev#495
- [ ] singularity-data/risingwave-dev#494
