### ISSUE TITLE
Tracking: User-defined Aggregate Function (UDAF)

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#11045]
Design doc / RFC: https://github.com/risingwavelabs/rfcs/pull/70/files

Necessary refactoring for aggregate function and executor in CN:
- [x] #10753 
- [x] #11909

Main tasks:
- [x] #10984
- [x] Handle `create aggregate` in frontend and maintain catalog in meta service.
- [x] Design UDAF API in Python and Java SDK
- [x] Implement UDAF under `Aggregator` trait.

**Comment by hezhaozhao-git** [comment]
Hello, is there any progress on this issue? Is there a planned release log?

**Comment by wangrunji0408** [comment]
> Hello, is there any progress on this issue? Is there a planned release date?

Hi, we have paused its development for a while due to low user demand and high complexity to support it efficiently. We plan to restart this work soon. A preview version may be released in 1.9 (April 2024).

**Comment by ravenfu** [comment]
I have the same demand, like implement  EMA(exponential moving average) function

**Comment by riaan53** [comment]
Any plans to support Rust (wasm) UDAFs for better performance? I see currently only python and JS is supported currently.

**Comment by stdrc** [comment]
As for now, we have supported the following UDF types:

- External UDF & UDTF
    - [Python](https://docs.risingwave.com/sql/udfs/use-udfs-in-python)    
    - [Java](https://docs.risingwave.com/sql/udfs/use-udfs-in-java)
- Embedded
    - No third-party library support
    - UDF & UDTF & UDAF
	    - [Python](https://docs.risingwave.com/sql/udfs/embedded-python-udfs)
	    - [JavaScript](https://docs.risingwave.com/sql/udfs/use-udfs-in-javascript)
    - UDF & UDTF
        - [Rust](https://docs.risingwave.com/sql/udfs/use-udfs-in-rust)

So we consider UDF feature available and are closing this tracking issue.

We still have some UDF-related feature/improvement planned, but IMO we don't need to tracking issue any more.

Here's a brief list, we can track the progress of each one in their own issue.

- https://github.com/risingwavelabs/risingwave/issues/14199
- https://github.com/risingwavelabs/risingwave/issues/18787
- https://github.com/risingwavelabs/risingwave/issues/18926
- https://github.com/risingwavelabs/risingwave/issues/20052
- https://github.com/risingwavelabs/risingwave/issues/20129
