### ISSUE TITLE
Tracking: Direct CDC Source Enhancement

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#11079]
- [x] Support lock-free and incremental snapshot https://github.com/risingwavelabs/rfcs/pull/63
    - [x] Support in-memory version of backfill for a single table - lock-free https://github.com/risingwavelabs/risingwave/pull/11707
    - [x] Persist backfill progress to support incremental backfill - incremental snapshot (#13204)

- [x] Share an upstream change log stream among multiple CDC tables
    - [x] Support create a `Source` streaming job for cdc connector to forward upstream events https://github.com/risingwavelabs/risingwave/pull/12535
    - [x] Derive query plan with `Chain` for the `CREATE TABLE ... FROM ...` command https://github.com/risingwavelabs/risingwave/pull/12535
    - [x] #13204
      - [ ] #13400
    - [x] https://github.com/risingwavelabs/risingwave/issues/13147
    - [x] Support the functionality for more upstream (v1.6), e.g. `postgres-cdc`
      - [x] https://github.com/risingwavelabs/risingwave/pull/13958

- [x] Preserve upstream transactional semantics
    - [x] https://github.com/risingwavelabs/risingwave/pull/14375

- Observability
    - #14353

- Optimization
    - [x] https://github.com/risingwavelabs/risingwave/issues/15812

- Misc
    - [x] https://github.com/risingwavelabs/risingwave/issues/16287
