### ISSUE TITLE
Tracking: refactor to imporve optimizer's robustness

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#11124]
- Schema check after different optimization phases
  - [x] heuristic optimizer https://github.com/risingwavelabs/risingwave/pull/9379/
  - [x] predicate push down
  - [x] column pruning
- Basic utils
  - [x] https://github.com/risingwavelabs/risingwave/issues/7234
      - https://github.com/risingwavelabs/risingwave/pull/11168
  - [x] introduce `ColIdxSet` to wrap `FixedSizedBitSet`
      - [x] https://github.com/risingwavelabs/risingwave/pull/10818
