### ISSUE TITLE
Tracking: Basic Built-in Functions

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#112]
Reference: [PostgreSQL: Documentation: 14: Chapter 9. Functions and Operators](https://www.postgresql.org/docs/current/functions.html)

## General for all types

* [ ] TEXT format input / output (cast from / into string)
* [ ] BINARY format input / output
* [x] singularity-data/risingwave-legacy#1916
* [x] singularity-data/risingwave-legacy#667 
* [x] singularity-data/risingwave/issues/2284

Aggregate

* [x] `count`

## Equality and Ordering for "most" types

* [x] `=` / `<>` / `!=`
* [x] #2684
* [x] singularity-data/risingwave/issues/2283
* [x] singularity-data/risingwave-legacy#666 
* [x] `<` / `<=` / `>` / `>=`
* [x] Implement `(NOT) BETWEEN AND` functions
* [x] #12761

Aggregate

* [x] `min` / `max`

## Boolean

* [x] explicit cast from / into int
* [x] Implement AND/OR/NOT operators
* [x] `IS [NOT] [TRUE | FALSE]`
* [x] #8933

Aggregate

* [x] #8936

## Window functions

* #8961

## Misc

- [ ] #14118

## More

* #8806
* #8831
* #8849
* #7117
* #7714
* #22606

**Comment by lmatz** [comment]
What's the difference between `Implement division operators (/) for all numeric types` and the `/` in `Implement arithmetic operators (+/-/*//) for all numeric types`?

**Comment by xiangjinwu** [comment]
> What's the difference between `Implement division operators (/) for all numeric types` and the `/` in `Implement arithmetic operators (+/-/*//) for all numeric types`?

Good catch. Guess it was a typo and I have fixed it.

**Comment by rotten** [comment]
I just ran into an issue with a tool that needed to run `pg_try_advisory_lock`, which, of course, failed because that function doesn't exist yet.  I don't see it in the list of functions (above) in this ticket already, so I thought I'd toss a vote in to add at least a mock for the function if the actual implementation doesn't make sense.  https://www.postgresql.org/docs/15/functions-admin.html#FUNCTIONS-ADVISORY-LOCKS-TABLE

**Comment by rotten** [comment]
The tool I was trying to use is [sqitch](https://sqitch.org) .  It uses advisory locks to ensure that only one sqitch is running at a time.

**Comment by rotten** [comment]
Awesome!  Thanks!
