### ISSUE TITLE
Tracking: WatermarkCache for StateTable

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#11320]
Currently state table issues DeleteRanges. If we include a watermark cache which caches the lowest row in the state table, we can avoid watermark cleaning if lowest row > watermark to be cleaned.

- [x] https://github.com/risingwavelabs/risingwave/pull/11161
- [ ] Add metrics for watermark cache
   - ~https://github.com/risingwavelabs/risingwave/pull/11161#discussion_r1282802837~ Outdated. With size 16, memory usage not super critical to be tracked.
   - Can still add cache hit / cache entries / cache miss.
- [x] Add microbench for state table. #11499 
- [x] Initialize state table with watermark cache for temporal filter. https://github.com/risingwavelabs/risingwave/pull/11512
- [ ] Bench temporal filter.
- [x] Test against https://github.com/risingwavelabs/risingwave/pull/11221.
