### ISSUE TITLE
Tracking: Support concurrent checkpoint

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#1156]
To improve our checkpoint strategy, we decide not to assume we only have a single barrier flowing through the graph any more. We need to revisit the design and implementation of our system to support concurrent checkpoint.

Streaming:
- [x] review executor implementation
- [x] support concurrent barrier injection/collection

Storage:
- [x] #2287
- [x] support concurrent transaction in hummock (i.e. transaction with larger epoch should wait for older epoch to commit)

**Comment by skyzh** [comment]
any updates? 🤪

**Comment by hzxa21** [comment]
> any updates? 🤪

Haven't started. Will do partition checkpoint first. Is there anything blocked on this?

**Comment by skyzh** [comment]
Nope, I'm just curious. 😇
