### ISSUE TITLE
Tracking: Alter Source/table with connector

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#11800]
- [x] https://github.com/risingwavelabs/risingwave/pull/11350
    - risk: might have conflict with https://github.com/risingwavelabs/rfcs/pull/72 
- [x] https://github.com/risingwavelabs/risingwave/pull/12164
- [x] https://github.com/risingwavelabs/risingwave/pull/14057
- [ ] https://github.com/risingwavelabs/risingwave/pull/15025/

**Comment by tabVersion** [comment]
@Rossil2012 here

**Comment by tabVersion** [comment]
#14057 can close this
