### ISSUE TITLE
Tracking: join optimization with partial update

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#11801]
join multiple tables with the same join key.
```SQL
SELECT * FROM A,B,C,D WHERE A.k = B.k AND A.k = C.k AND A.k = D.k;
```
- [ ] MaterializeExecutor: add `partial update` handle_pk_conflict_behavior (`field = coalesce(new_row.field, old_row.field)`)

- manually, It will be used for users who do not know all the join tables at the beginning
  - [ ] table's ON CONFLICT syntax 
  - [ ] create sink into table @shanicky 

- Optional 
  - [ ] ON CONFLICT DO UPDATE behavior

**Comment by fuyufjh** [comment]
I prefer to let users do this manually by using "sink to table" syntax, rather than optimizing these queries implicitly, because of the limitation of this approach

1. The join key (`k`) must be the primary keys of all tables e.g. A,B,C,D
2. The join had better to be a inner join, otherwise, we need another Materialized view to do the duplication

These limitations are hard to explain to users. I would rather let them to use "sink to table" syntax so that they can understand the correct use case and limitations quickly

**Comment by st1page** [comment]
After offline discussion, need an RFC later,
