### ISSUE TITLE
Tracking: embedded connector node

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#12090]
Phase1: Embedded connector node coexists with the original connector
In this phase, we will migrate connector RPC to the Embedded one step by step, so that we can review it easier and don't need to migrate it in one version.

- [x] Extract java_binding common codes into `jni_core`. https://github.com/risingwavelabs/risingwave/pull/12108
- [x] Start a JVM in Rust and register native methods. https://github.com/risingwavelabs/risingwave/pull/12122
- [x] Set up necessary environment variables for embedded connector node. https://github.com/risingwavelabs/risingwave/pull/12122
- [x] Replace Source CDC RPC with JNI. https://github.com/risingwavelabs/risingwave/pull/12122
- [x] Replace Source validation RPC with JNI. https://github.com/risingwavelabs/risingwave/pull/12270
- [x] Replace Sink validation RPC with JNI. https://github.com/risingwavelabs/risingwave/pull/12312
- [x] Replace Sink coordinator RPC with JNI. https://github.com/risingwavelabs/risingwave/pull/12724
- [x] Replace Sink writer RPC with JNI. https://github.com/risingwavelabs/risingwave/pull/12480
- [x] Migrate connector metrics from Java to Rust. https://github.com/risingwavelabs/risingwave/pull/12283 https://github.com/risingwavelabs/risingwave/pull/12584

Phase2: Embedded connector node only

Clean up:
- [ ] Remove java_binding crate
- [x] Disable the connector node and clean up existing codes related to it. https://github.com/risingwavelabs/risingwave/pull/12807 https://github.com/risingwavelabs/risingwave/pull/12804
- [x] https://github.com/risingwavelabs/risingwave/issues/13089
- [x] Remove connector service from ci tests https://github.com/risingwavelabs/risingwave/pull/13112
- [x] Remove connector service from the playground https://github.com/risingwavelabs/risingwave/pull/13114

**Comment by chenzl25** [comment]
> @chenzl25 I've just manually created an all-in-one package that combines connector libs and the risingwave binary. We should automate the workflow in future: https://github.com/risingwavelabs/risingwave/releases/download/v1.3.0/risingwave-v1.3.0-x86_64-linux-all-in-one.tar.gz

Yes. I will take a look. cc @huangjw806
