### ISSUE TITLE
Tracking: SQL-backend based meta store

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#12449]
### Is your feature request related to a problem? Please describe.

- [x] #12475
- [x] Catalog controller(database, schema, table, source, sink, index, view, function, connection, user etc).
- [x] #12690
- [x] SQL-based leader election.
- [x] Refactoring on streaming/barrier manager.
- [x] System parameter, notification version and tracking id etc.
- [x] streaming DDL syntax support
	- [x] create streaming jobs: table, mv, sink, index.
	- [x] drop streaming jobs.
	- [x] cancel streaming jobs.
	- [x] replace table.
	- [x] create sink into table.
	- [x] scaling: reschedule and auto scaling.
- [x] Hummock metadata controller.
- [x] Testing.
- [x] Migration tool from etcd to sql-backend.
- [x] https://github.com/risingwavelabs/risingwave/issues/15030
- [x] #15051 
- [x] #15693

**Comment by kwannoel** [comment]
- Is background ddl supported?

And for testing to be precise we have:
- [ ] Recovery tests
- [ ] Backwards compat tests

**Comment by yezizp2012** [comment]
Most tasks are completed in the kernel. Remaining issues are tracked in #19106.
