### ISSUE TITLE
Tracking: Implement e2e benchmark tool for RisingWave

### ISSUE THREAD

**Issue by zehaowei** [risingwavelabs/risingwave#127]
Mainly benchmarking for state management of RisingWave, e2e throughput, price/performance, data freshness, e2e latency

Functionality
- [x] Cmd tool
- [x] Configurable source & workload generator
- [x] Execution pipeline(pg sql, Kafka, CDC)
- [x] Metrics service
- [x] Support using pg SQL & table source to benchmark RisingWave
- [x] Support using Kafka to benchmark RisingWave
- [ ] Support using CDC(MySQL->Debezium->Kafka) to benchmark RisingWave

Source
- [x] Implement TPC-H as benchmarking source
