### ISSUE TITLE
RisingWave Roadmap Q4 2023

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#13115]
# Note
 
Initial date: Oct. 10, 2023
Last update: Oct. 28, 2023

One year and four months ago, in April 2022, we open sourced RisingWave, the distributed SQL streaming database. A month ago, in July 2023, we released the first official version of RisingWave, RisingWave 1.0, a battle-tested system that can be used in production. More recently, RisingWave 1.3 has been released.

As an open-source streaming database released under Apache 2.0 license, the development team behind RisingWave actively collect feedback from users and strives to democratize stream processing: to make it simple, affordable, and accessible.

As a system that has been deployed in production in dozens of enterprises and fast-growing startups, how will RisingWave evolve? We plan to make it transparent and periodically update our roadmap. Here’s what you can anticipate in the future release of RisingWave.

Note that the roadmap is not final, and we will frequently update our roadmap to reflect and the item priority to better serve users.

# Short-term goals (within the next 3 months)

- **Adaptive Scaling**

    https://github.com/risingwavelabs/risingwave/issues/13140

    Implement adaptive scaling to automatically adjust materialized view parallelism based on the number of CPU cores in the cluster.
    
- **Improvements on the Existing External Sinks**
    
    Optimize performance and improve stability of supported external sinks like Doris, Clickhouse, and Elasticsearch. We’ll also expand supported encoding formats for Kafka sink, including Protobuf, Avro, and the support for Schema Registry.
    
- [x] **Iceberg Sink V2**

    https://github.com/risingwavelabs/risingwave/issues/10641 

    We recently introduced a native integration with Iceberg, which is no longer based on the official Java library. It’s fully rewritten by Rust for performance and stability. We plan to stabilize it in the next few months.

    Most of the works have been done.
    
- **Enhanced Observability**
    
    Expand system tables and add metrics for stateful operators to provide greater visibility into system health and performance.
    
- **Improved Open-source Web UI**
    
    Enhance RisingWave's open-source web UI with additional system information and monitoring capabilities.
    
- [x] **Sink into Table**
    
    Users may want to dynamically union the results of multiple views into a single table. For example, a view may correspond to an department in a company while there can be new departments once in a while. With this feature, users can seamlessly merging data from new views as they are added.

    Done: https://docs.risingwave.com/docs/current/sql-create-sink-into/
   
- [x] **CDC Connection Sharing**

     https://github.com/risingwavelabs/risingwave/issues/11079

    RisingWave currently creates one CDC connection per table. Each connection will individually consume the replication logs, which consists of transactions not only to the source table, but also other tables in the same database. Therefore, multiple connections will lead to the duplicate consumption and a heavy load on the upstream database.
    
    Shared CDC connections can thus reduce the load and improve the stability of CDC.

    Done: 
    - [Connection sharing for Postgres](https://docs.risingwave.com/docs/current/ingest-from-postgres-cdc/#create-multiple-cdc-tables-with-the-same-source)
    - [Connection sharing for MySQL](https://docs.risingwave.com/docs/current/ingest-from-mysql-cdc/#create-multiple-cdc-tables-with-the-same-source)
    
- [x] **Recoverable `CREATE MATERIALIZED VIEW`**
    
    Persist materialized view progress to allow recovering from failures without losing work already completed.

    https://github.com/risingwavelabs/risingwave/pull/12167
    
- **CDC Transaction Atomicity**
    
    CDC transactions in RisingWave currently applies by events, which may contain only partial content in a transaction. With the new feature, RisingWave will buffer all CDC events within a transaction until it can be fully applied atomically.
    

# Mid-term goals (within the next 6 months)

- [x] **SSL/TLS Secured Connection**
    
    Implement SSL/TLS encryption for client/server communications to enhance security.

    In progress: https://github.com/risingwavelabs/risingwave-docs/issues/1699
    
- [x] **Alter Materialized View**
    
    Add ability to modify existing materialized views. https://docs.risingwave.com/docs/current/alter-streaming/
    
- **Session Window**
    
    Introduce session window functionality for advanced streaming analytics.
    
- **MemTable Spill**
    
    A refresh to a small table could suddenly cause 1k times amplification on write throughput. Such a case typically happens when there is a 10+ way join. A way to mitigate this is to make mem table spillable, thus avoiding OOM.
    
- **Dedicated Computes for Materialized View Creation**
    
    Some users complained that RisingWave’s materialized view creation is too slow, as it requires a resource-intensive ad-hoc computation. On the other hand, since the streaming (incremental computations) is long-running, it requires less resources at the same time. As a result, it’s possible to allocate dedicated resources for MV creation separately when needed, and deallocate them once finished.
    
- **More External Sinks**
    
    Redshift Sink and Snowflake Sink are in the plan.
    
- **Recursive CTE**
    
    Enable recursive common table expressions (CTE) to traverse hierarchical data like the organizational tree in a company.
    
- **Shared Meta Plane**
    
    Enable RisingWave clusters to share the meta plane, including Etcd (or Postgres in the future), to better utilize compute resources across clusters.
    
- **Parallel CDC Snapshot Loading**
    
    Introduce parallelism during CDC snapshot loading to improve user experience for large upstream tables.
    

# Long-term goals

- **Optimize analytical query performance on third-party systems like Presto and Trino**
- **GraphQL API**
    
    To allow retrieving results from RisingWave directly through the browser.
    
- **Serverless Compaction**
    
    Automatically scale Compactor instances in and out to match workload demands in a serverless model.

# Welcome to comment

Please feel free to leave your comments below. We would love to hear from the community and update our agenda accordingly!!!

**Comment by ly9chee** [comment]
Any plans for columnar storage? i.e. user can choose to register their materialized view to a columnar format (like parquet) and then this materialized view is suitable for both point-get and ad-hoc queries 😄, also the olap system like apache doris and clickhouse are no longer needed.

**Comment by yingjunwu** [comment]
> Any plans for columnar storage? i.e. user can choose to register their materialized view to a columnar format (like parquet) and then this materialized view is suitable for both point-get and ad-hoc queries 😄, also the olap system like apache doris and clickhouse are no longer needed.

That's a great question. We don't have plan for supporting columnar storage within the next 3 months. The reason is that RisingWave aims at offering open-source users and paying customers the best stream processing experience, and it's still not the right time for us to introduce columnar storage.

However, we fully understand that many users have the need to do both stream processing and real-time analytics. Here's our immediate solution:

1. [done] allow users to deliver data out from RisingWave to dedicated services like ClickHouse and Apache Doris, with or without Kafka connection;
2. [done] allow users to deliver data out from RisingWave to data lakes.

We may allow users to create columnar tables (explicitly) in the future, but it all depends on our progress in enhancing RisingWave's stream processing capability.
