### ISSUE TITLE
Tracking: jsonb operations

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#14003]
To support more ORM tools, it's necessary to add more system information functions/expressions. Here's the corresponding [list in Postgres](https://www.postgresql.org/docs/9.5/functions-info.html).

- [ ] current_catalog
- [ ] current_database
- [ ] current_query
- [ ] current_role
- [ ] current_schema
- [ ] current_schemas
- [ ] current_user
- [ ] inet_client_addr
- [ ] inet_client_port
- [ ] inet_server_addr
- [ ] inet_server_port
- [ ] pg_backend_pid
- [ ] pg_conf_load_time
- [ ] pg_is_other_temp_schema
- [ ] pg_listening_channels
- [ ] pg_my_temp_schema
- [ ] pg_postmaster_start_time
- [ ] pg_trigger_depth
- [ ] session_user
- [ ] user
