### ISSUE TITLE
Tracking: Ibis Support 

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#14004]
[ibis](https://ibis-project.org/): the portable Python dataframe library.
[ibis has supported postgresql](https://ibis-project.org/backends/postgresql).

We separate the Ibis suppport development into three stages:

- [ ] Support more functions to align RW with PG. 
  - [ ] https://github.com/risingwavelabs/risingwave/issues/14003
- [x] Enhance `sqlalchemy-risingwave`  to satisfy all the requirement of `ibis-postgres`.
- [x] Support a `sqlglot-risingwave` sqlglot.dialects.dialect.Dialect
- [x] Contribute `ibis` to get official support.
  - [ ] https://github.com/ibis-project/ibis/pull/7954

Bugs found while supporting ibis.
- https://github.com/risingwavelabs/risingwave/issues/14423
- https://github.com/risingwavelabs/risingwave/issues/14670
- https://github.com/risingwavelabs/risingwave/issues/14734
- https://github.com/risingwavelabs/risingwave/issues/14731
- https://github.com/risingwavelabs/risingwave/issues/14735

Feature requests:
- func: levenshtein(character varying, character varying) 
- func: textregexeq(character varying, character varying)
- func: make_date https://github.com/risingwavelabs/risingwave/pull/14827
- func: make_time https://github.com/risingwavelabs/risingwave/pull/14827
- func: make_timestamp https://github.com/risingwavelabs/risingwave/pull/14827
- func: make_interval
- func: random()
- func: log10(numeric, numeric) 
- func: hstore(character varying[], character varying[])
- func: last(double precision)
- support `limit null`
- support data type like `NUMERIC(38,9)`
- support risingwave `sqlglot.dialects.dialect.Dialect` 
- support `information_schema.schemata`
- fix `get_columns` in sqlalchemy-risingwave

**Comment by KeXiangWang** [comment]
Marked as Done temporarily. Will continue to support more features if requested by users.

**Comment by KeXiangWang** [comment]
> Curious if you have any fully featured examples of ibis-risingwave anywhere?

Currently no.

> I think a really nice fully featured example could be tpch against an iceberg source with ibis-risingwave?

Thanks for the suggestion! We will consider that. Is there a specific reason you want to use `ibis-risingwave`? Does SQL API not meet your requirements? We also have `psycopg2` support for python users. The doc is [here](https://docs.risingwave.com/docs/current/python-client-libraries/).

**Comment by KeXiangWang** [comment]
You actually can use Python UDFs with the SQL API. Unfortunately the UDF functions haven't been supported in `ibis-risingwave`. cc @alicelyy PTAL
