### ISSUE TITLE
Tracking: related work for `CREATE SINK INTO TABLE`

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#14063]
## misc & fix
- [x] https://github.com/risingwavelabs/risingwave/pull/14065
- [x] https://github.com/risingwavelabs/risingwave/pull/14134
- [x] https://github.com/risingwavelabs/risingwave/pull/14136
- [x] https://github.com/risingwavelabs/risingwave/pull/14158
- [x] https://github.com/risingwavelabs/risingwave/issues/14157

## drop table
- [ ] drop table cascade

## alter table
- [x] #14417
- [x] https://github.com/risingwavelabs/risingwave/issues/14068

## properties
- [x] default column
- [x] generated column
- [ ] watermark

## system tables feature
- [ ] https://github.com/risingwavelabs/risingwave/issues/14066

## Testing
- [ ] Test it in sqlsmith

**Comment by kwannoel** [comment]
Added a task for testing with sqlsmith.
