### ISSUE TITLE
Tracking: potential concurrent futures

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#14067]
Found by #14013 

## Meta

- [ ] [diff](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/stream/source_manager.rs#L249)

[pre_allocate_splits](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/stream/source_manager.rs#L625)
- [ ] [arrange_reschedules](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/stream/scale.rs#L1337)
- [ ] [arrange_no_shuffle_relation](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/stream/scale.rs#L1077)
- [ ] [create_actors_on_compute_node](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/stream/scale.rs#L668)
- [ ] [create_actors_on_compute_node](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/stream/scale.rs#L689)
- [ ] [validate_cdc_table](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/rpc/ddl_controller.rs#L609)
- [ ] [drop_database](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/rpc/ddl_controller.rs#L345)
- [ ] [send_to_all_sink_writers](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/sink_coordination/coordinator_worker.rs#L121)
- [ ] [ClusterManagerCore::new](https://github.com/risingwavelabs/risingwave/blob/chore/lint-await-in-loop/src/meta/src/manager/cluster.rs#L566)
- [ ] [start_heartbeat_checker](https://github.com/risingwavelabs/risingwave/blob/chore/lint-await-in-loop/src/meta/src/manager/cluster.rs#L378)
- [ ] [update_schedulability](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/cluster.rs#L260)
- [ ] [revoke_privilege](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/mod.rs#L3646)
- [ ] [grant_privilege](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/mod.rs#L3485)
- [ ] [init_user](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/mod.rs#L3219)
- [ ] [alert_set_schema](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/mod.rs#L2187)
- [ ] [alter_owner](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/mod.rs#L1948)
- [ ] [drop_relation](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/mod.rs#L1518)
- [ ] [clean_dirty_tables](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/mod.rs#L791)
- [ ] [unmark_creating_tables](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/mod.rs#L684)
- [ ] [mark_creating_tables](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/mod.rs#L671)
- [ ] [drop_function](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/mod.rs#L627)
- [ ] drop_schema
- [ ] drop_database
- [ ] create_database
- [ ] [post_apply_reschedules](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/fragment.rs#L1233)
- [ ] [migrate_fragment_actors](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/fragment.rs#L757)
- [ ] drop_table_fragments_vec
- [ ] [notify_fragment_mapping](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/manager/catalog/fragment.rs#L260)
- [ ] [dump_await_tree_inner](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/dashboard/mod.rs#L217)
- [ ] [list_user_info_by_ids](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/controller/utils.rs#L398)
- [ ] revoke_privilege
- [ ] grant_privilege
- [ ] drop_user
- [ ] notify_users_update
- [ ] flush_params
- [ ] get_downstream_chain_fragments
- [ ] get_upstream_root_fragments
- [ ] update_actor_splits
- [ ] [migrate_actors](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/controller/fragment.rs#L675)
- [ ] [alter_name](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/controller/catalog.rs#L1144)
- [ ] create_view
- [ ] create_database
- [ ] handle_barrier_complete
- [ ] finish_jobs
- [ ] run_multiple_commands
- [ ] recover_background_mv_progress
- [ ] CommandContext::to_mutation
- [ ] v2::insert_models
- [ ] restore_default_cf
- [ ] restore_system_param_model
- [ ] restore_metadata_model
- [ ] 

## Hummock

- [ ] compaction_event_loop
  - [ ] [src/meta/src/hummock/manager/mod.rs:2686:41](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/hummock/manager/mod.rs#L2759)
  - [ ] https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/hummock/manager/mod.rs#L2686
- [ ] [on_handle_check_split_multi_group](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/hummock/manager/mod.rs#L2512)
- [ ] [hummock_timer_task](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/hummock/manager/mod.rs#L2302)
- [ ] [init_metadata_for_version_replay](src/meta/src/hummock/manager/mod.rs:1835:9)
- [ ] https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/hummock/manager/mod.rs#L1806
- [ ] [for context_id in context_ids {](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/hummock/manager/versioning.rs#L193)
- [ ] commit_epoch_sanity_check
- [ ] [release_invalid_contexts](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/hummock/manager/context.rs#L104)
- [ ] [move_state_table_to_compaction_group](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/hummock/manager/compaction_group_manager.rs#L673)
- [ ] [list_compaction_group](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/meta/src/hummock/manager/compaction_group_manager.rs#L414)
- [ ] [register_table_ids](https://github.com/risingwavelabs/risingwave/blob/chore/lint-await-in-loop/src/meta/src/hummock/manager/compaction_group_manager.rs#L197)

## Frontend
- [ ] [complete_stage](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/frontend/src/scheduler/plan_fragmenter.rs#L627)
- [ ] cancel_all_scheducancled_tasks
- [ ] clean_all_stages
- [ ] all_children_scheduled
- [ ] QueryRunner::run

## Stream

- [ ] build_actors
- [ ] create_nodes_inner
- [ ] build_agg_state_storages_from_proto
- [ ] many apply_chunk
- [ ] StatelessSimpleAggExecutor::apply_chunk
- [ ] SourceStateTableHandler::trim_state
- [ ] SourceStateTableHandler::take_snapshot
- [ ] rebuild_stream_reader_from_error
- [ ] SourceExecutor::update_state_if_changed
- [ ] replace_with_new_batch_reader
- [ ] get_diff
- [ ] SimpleAggExecutor::apply_chunk
- [ ] [map_filter_chunk](https://github.com/risingwavelabs/risingwave/blob/18b5a7bc34529be34e4851bdf16af52f75e7399a/src/stream/src/executor/project.rs#L120)
- [ ] dispatch_barrier
- [ ] persist_state_per_vnode
- [ ] recover_backfill_state
- [ ] parse_debezium_chunk
- [ ] ColumnDeduplicater::dedup
- [ ] AggGroup::apply_chunk
- [ ] StateTableInner::commit
- [ ] LogStoreRowOpStream::init

## Batch

- [ ] HashShuffleSender::send_done
- [ ] HashShuffleSender::send_chunk
- [ ] ConsistentHashShuffleSender
- [ ] BroadcastSender
- [ ] ExecutorBuilder::try_build
- [ ] SortAggExecutor::output_agg_states
- [ ] update_agg_states
- [ ] InsertExecutor::do_execute
- [ ] ProjectionOrderBy::get_result

**Comment by hzxa21** [comment]
@Li0k @Little-Wallace Can you help review the ones in `Hummock` section? Most of them are related to compaction logic in the meta side. I believe we may not be able to make it concurrent because the existence of compaction/version lock.

**Comment by lmatz** [comment]
Is `StatelessSimpleAggExecutor::apply_chunk` not a false positive? 
Saw it is used in the query plan of nexmark q102
Link #15004 for visibility
