### ISSUE TITLE
Tracking: enhancement for temporal fitler 

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#14088]
- [x] https://github.com/risingwavelabs/risingwave/pull/13985
- [ ] https://github.com/risingwavelabs/risingwave/issues/14085
- [ ] https://github.com/risingwavelabs/risingwave/issues/14084
