### ISSUE TITLE
Tracking: Enhanced integration with StarRocks

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#14822]
We want to enhance the StarRocks sink, providing a full-featured integration and progress the feature toward a more stable phase.
Here is a list of specific tasks:
- [x] Test the integration with StarRocks v2.5 (2.5.18), which will be the minimum supported version afterwards.
- [x] Test with StarRocks v3.0 (3.0.9) and v3.1 (3.1.7). Not required to include it in CI. 
- [ ] Support multiple MySQL frontend servers. Right now we only support one address.
- [x] Starting from v2.2, StarRocks introduced the JSON support. Since our minimal supported vesion is v2.5, we can convert complex data types like JSONB into JSON.
- [x] Refine the error when the user tries to sink a timestamptz column. We should suggest converting timestamptz to timestamp at first. 
       For example, "TIMESTAMP WITH TIMEZONE is not supported for Doris sink as Doris doesn't store time values with timezone information. Please convert the column '{}' to TIMESTAMP first."
- [x] Refine the error for INTERVAL, TIME, and BYTEA.

Once all finished, we'll try to publish on the integration guide in StarRocks's document website.

**Comment by xxhZs** [comment]
Test the multiple MySQL/HTTP frontend servers.  our request and fe exchange only two cases, 1. get the table schema. 2. request forwarded to be, tested the fe under the multi-cluster, these two functions, the cluster can be completed by any node, so may not need to implement multiple ports.
