### ISSUE TITLE
Tracking: deprecate range tombstone

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#14824]
Given that we have introduced table watermark in #13148 and have all executors switched to use table watermark to clean up storage states, it is time to gradually deprecate the general-purpose range delete support via range tombstone in storage because it has deeply invaded in the read/write/compaction path of storage and increased the maintenance burden. 

- [x] Deprecate range tombstone in the write path (#14776)
- [ ] Expose per table vnode watermark via SQL. User can make sure per table vnode watermark exists in all relevant state tables before upgrading to the future release version, where range tombstone is completely deprecated (https://github.com/risingwavelabs/risingwave/pull/15344)
- [ ] Deprecate range tombstone in compaction https://github.com/risingwavelabs/risingwave/pull/15613
- [ ] Review executor read pattern and deprecate range tombstone in the read path. https://github.com/risingwavelabs/risingwave/pull/15613
