### ISSUE TITLE
Tracking: barrier manager in Meta service

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#15]
This will be a step-by-step plan to fix singularity-data/risingwave-legacy#1455. For more details, check the [design doc](https://singularity-data.larksuite.com/docs/docusjTKPRA9HzK5SoCTOJLXMle) by @skyzh.

- [x] singularity-data/risingwave-legacy#2737
- [x] singularity-data/risingwave-legacy#2787
- [x] singularity-data/risingwave-dev#386
- [x] singularity-data/risingwave-legacy#2898
- [x] #17
