### ISSUE TITLE
tracking: enhance the support for NATS

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#15376]
- [ ] Support querying directly from a NATS source.
- [x] #15377
- [ ] Reject create-source commands if the subject/stream doesn't exist.
- [ ] Add protobuf to NATS's integration test. (Update ci/scripts/gen-integration-test-yaml.py)
- [x] https://github.com/risingwavelabs/risingwave/issues/15507
