### ISSUE TITLE
Tracking: optimize performance of hummock manager in meta-node

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#15397]
### Background 
Some user meet a problem which is the meta-node use too much CPU resource (nearly 100%, one whole core), and hummock manager can not generate compact task in time.
![image](https://github.com/risingwavelabs/risingwave/assets/16376959/189579bf-7be4-4695-ab93-e76a677a0220)

### Develop Task

- [x] optimize metrics report https://github.com/risingwavelabs/risingwave/issues/15153
- [x] reduce object clone of `HummockVersion` (https://github.com/risingwavelabs/risingwave/pull/15386)
- [x] optimize ETCD (SQL-Backend) transaction cost , batch several compact task for once ETCD. Maybe SQL-Backend could solve part of this problem. But in current implementation, all operations of `HummockManager` would acquire the same lock and update the same key in ETCD, So it is still important to batch operations.
