### ISSUE TITLE
Tracking: schema changes of source | (table with connector) 

### ISSUE THREAD

**Issue by Rossil2012** [risingwavelabs/risingwave#15582]
A relay for #11800.
- [ ] `ALTER TABLE <name> FORMAT ... ENCODE ... ( ... )`
- [x] `ALTER SOURCE <name> FORMAT ... ENCODE ... ( ... )`: https://github.com/risingwavelabs/risingwave/pull/14057
- [x] `ALTER TABLE <name> REFRESH SCHEMA`: https://github.com/risingwavelabs/risingwave/pull/15025
- [x] `ALTER SOURCE <name> REFRESH SCHEMA`: https://github.com/risingwavelabs/risingwave/pull/15541

Note: A minor difference between `ALTER SOURCE <name> REFRESH SCHEMA` and `ALTER TABLE <name> REFRESH SCHEMA` is that the former rejects if columns are missing or changed, while the latter do this check only when the column is referenced by downstream tasks.

**Comment by Rossil2012** [comment]
Possible solution: using the semantics whether the source executor is reset.
https://github.com/risingwavelabs/risingwave/pull/15025#discussion_r1512488010

**Comment by Rossil2012** [comment]
cc @tabVersion @fuyufjh @st1page.

**Comment by fuyufjh** [comment]
Related discussion about watermark https://github.com/risingwavelabs/rfcs/pull/85#issuecomment-2120297051

**Comment by fuyufjh** [comment]
Note down a requirement for `ALTER SOURCE CONNECTOR` today: without this, changing a single argument will need to recreate the source/table and re-consume the upstream.

[Slack thread](https://risingwave-labs.slack.com/archives/C078FMP8G9K/p1718762130353449?thread_ts=1718758576.982059&cid=C078FMP8G9K)

**Comment by yuhao-su** [comment]
We probably also need the same for `alter sink`

**Comment by st1page** [comment]
> We probably also need the same for `alter sink`

Can you explain more about it? Should the sink re-send all the historical data or just send it with the current progress?

**Comment by st1page** [comment]
Changed the pr description and will create a new PR for "alter connector" to make the issue clearer

**Comment by fuyufjh** [comment]
Note down a reminder: alter a secret that referenced by a connector is also kind of `alter source` i.e. it should be refreshed without rebuilding the `SourceExecutor`.

**Comment by fuyufjh** [comment]
We divided the cases into 2 categories: No Rebuild and Rebuild.
1. If a property change doesn’t need to rebuild the connector instance or state, then it can be done in a lightweight fashion, such as mutate it with a single barrier
2. If a property change need to rebuild the connector or state, such as change the Kafka consumer topic or change the connector type e.g. from File to Kafka, then we clean the previous state, drop the old actors and create new ones.

**Comment by xxchan** [comment]
For rebuild, there's another case: alter schema



|                             | alter small param | alter connector       | alter schema         |
| --------------------------- | ----------------- | --------------------- | -------------------- |
| non-shared source           | no rebuild        | rebuild (clean state) | no rebuild ⚠️      |
| shared source               | no rebuild        | rebuild (clean state) | rebuild (keep state) |
| materialized source (table) | no rebuild        | rebuild (clean state) | rebuild (keep state) |
 

(More discussion on https://risingwave-labs.slack.com/archives/C069EV2Q5MK/p1726639203021329

**Comment by fuyufjh** [comment]
Just found a new issue addressing this. https://github.com/risingwavelabs/risingwave/issues/18440 Let's move there for discussion.

**Comment by tabVersion** [comment]
close this one for duplicate with #18440
