### ISSUE TITLE
investigate `cargo zigbuild` for cross-compiling targeting lower GLIBC version

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#15749]
To make the release binary compatible with most Linux distros, we decided to build it on `manylinux2014` starting from #4556 since it features GLIBC 2.17, which is relatively low.

However, the outdated environment also makes maintenance difficult for us. Examples:
- Very tricky to install `lld`: https://github.com/risingwavelabs/risingwave/pull/13746#issuecomment-1833450034
- When building dashboard, Nextjs 20 requires Nodejs 18, which is not compatible with GLIBC 2.17: #14913

Theoretically, the target GLIBC version does not have to be the same with the host GLIBC version, which is essentially the idea of cross-compiling. For a long time, however, this has been [considered difficult and impossible](https://stackoverflow.com/questions/2856438/how-can-i-link-to-a-specific-glibc-version#comment5277633_2856438).

Fortunately, the build system from `zig` makes the life easier to do cross-compiling on C/C++ dependencies (see https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html). There's also a wrapper for using `zig cc` in Rust projects named [`cargo-zigbuild`](https://github.com/rust-cross/cargo-zigbuild).

By including the GLIBC version in `--target`, we're able to make the artifact linked with a different version of GLIBC than the current system uses. Ideally, this allows us to use an arbitrary distro for building RisingWave Linux binaries and still makes it compatible with most old systems.

```
cargo zigbuild --target aarch64-unknown-linux-gnu.2.17 -p risingwave_cmd_all
```

---

However, there're still some outstanding issues for this to work correctly. Generally, it requires all `-sys` dependencies to correct handle the cases for cross-compiling.

- [x] Statically link `libz` by enabling `libz-static` feature of `rdkafka`. #15754 
- [ ] `sasl2-sys` does not cross compile: https://github.com/MaterializeInc/rust-sasl/issues/46
- [ ] `zigbuild` may not work correctly with `linkme`: https://github.com/rust-cross/cargo-zigbuild/issues/214

**Comment by BugenZhao** [comment]
Since #15821, this is no longer a must-have.
