### ISSUE TITLE
Tracking issue for shared source

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#16003]
RFC https://github.com/risingwavelabs/rfcs/pull/72

- [x] #14172 
- [x] https://github.com/risingwavelabs/risingwave/pull/15602
- [x] CREATE TABLE (no change)
- [x] https://github.com/risingwavelabs/risingwave/issues/18338
- [x] https://github.com/risingwavelabs/risingwave/issues/18299
- pause/start from latest to avoid waste work
	- [x] pause SourceExecutor before a Backfill is created. This means the SourceExecutor doesn't waste work, and the first MV (maybe we even want multiple MVs?) doesn't need backfill.  #16348
	- [x] #16576
	- [x] #16626
- [ ] Check whether metrics need refinement (whether cloud needs change)
- [x] #18749
- [ ] benchmarks https://linear.app/risingwave-labs/issue/PERF-163/[test-request]-disable-shared-source-by-default-in-the-daily-benchmark

## ALTER

- [x] https://github.com/risingwavelabs/risingwave/pull/18750
- [ ] schema change (https://github.com/risingwavelabs/risingwave/issues/11800, https://github.com/risingwavelabs/risingwave/issues/15582)
   - [ ] #19063
- scaling 
	- [x] #16825
	- [ ]  #19508
	- [x] https://github.com/risingwavelabs/risingwave/issues/18300
- [x] #19297

## testing
- [x] more e2e tests https://github.com/risingwavelabs/risingwave/issues/15995
- [ ] https://github.com/risingwavelabs/risingwave/issues/15994
- [x] backfill test #18924
