### ISSUE TITLE
Tracking: support more type casts

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#1632]
* [x] string to interval (`select '3 month'::interval;`)
* [x] interval to string
* [x] time to string
* [x] timestampz to string
* [x] timestamp to string
* [x] date to string
* [x] time to interval
* [x] interval to time
* [x] timestamp to date
* [x] timestamp to time

The following requires timezone from session context (#3552):
* [ ] date to timestampz
* [ ] timestamp to timestampz
* [ ] timestampz to date
* [ ] timestampz to timestamp
* [ ] timestampz to time

**Comment by xiangjinwu** [comment]
Remaing ones tracked by #5826
