### ISSUE TITLE
tracking: batch select on source

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#16411]
### Is your feature request related to a problem? Please describe.

- [ ] batch select on pulsar source
- [ ] batch select on kinesis source
- [ ] batch select on nats source
- [ ] batch select on google pub/sub source 
- [ ] batch select on jdbc sources, including
    - [ ] batch select on mysql source,
    - [ ] batch select on postgres source,
    - [ ] batch select on mongodb source,

**Comment by xxchan** [comment]
#18583
