### ISSUE TITLE
Tracking: Remote storage IOPS optimization

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#16973]
This issue tracks ideas on optimizing remote storage IOPS:
- [x] #16087
- [ ] Enable disk cache on system disk
- [ ] Monitor per state table read iops and block efficiency
- [ ] Unit based block prefetch for streaming state table
- [ ] Priority based block eviction considering operator/state table access pattern
- [ ] Limit per core remote storage IOPS
- [ ] CN local compaction
- [ ] Explore leveraging local disk as cache or maintain disk-based local version for read-heavy state table
