### ISSUE TITLE
Tracking: enable sink_decouple by default for all types of sink

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#17095]
Currently (as of v1.9) sink_deoucple is enabled by default in the following sinks:
- MQ with append-only stream (including kafka, pulsar, kinesis, google pubsub. nats, mqtt)
- Clickhouse with append-only stream
- Iceberg/Datalake with commit_checkpoint_interval set > 1

For other sinks, user must specify `sink_decouple` session variable to enable this feature explicitly before sink creation. Given that external sink error and unavailability are unavoidable and uncontrollable by RisingWave, we should enable the sink checkpoint decoupling feature by default to provide a better user experience. We can do it gradually with the following schedule:
- [ ] Create an alert when log store lag is large and increasing
- [x] Enable `sink_decouple` by default for upsert stream in `v1.10`
  - [x] MQ (kafka, pulsar, kinesis, google pubsub, nats, mqtt)
  - [x] Clickhouse
- [ ] Enable `sink_decouple` by default for all other sinks in `v1.11`
  - [ ] Biquery
  - [ ] Doris/Starrocks
  - [ ] #17073
  - [ ] Redis
  - [ ] Snowflake
  - [ ] Cassandra
  - [ ] JDBC
  - [ ] http
  - [ ] ~~Datalake (iceberg/deltalake)~~ _(not eligible when `commit_checkpoint_interval` set to 1)_
- [ ] Support async log truncation in eligible sinks _(currently only kafka/pulsar sink is supported and for other sinks, there will be unnecessary writes into log store with sink decouple enabled even in happy path)_
  - [x] Kinesis 
  - [x] Google pubsub
  - [x] Nats
  - [ ] ~~MQTT~~
  - [ ] ~~Clickhouse~~
  - [ ] Biquery
  - [ ] ~~Doris/Starrocks~~
  - [ ] Elasticsearch
  - [ ] Redis
  - [ ] ~~Snowflake~~
  - [ ] ~~Cassandra~~
  - [ ] ~~JDBC~~
  - [ ] ~~http~~
  - [ ] mongodb
  - [ ] dynamodb
  - [x] ~~Datalake (iceberg/deltalake)~~ _(not eligible when `commit_checkpoint_interval` set to 1)_

**Comment by hzxa21** [comment]
Note that pre-existing sinks created before will not be affected. In other words, if a sink is created with sink decouple disabled, sink decouple will not be enabled after version upgrade.

**Comment by xxhZs** [comment]
With the current logic, sink decouple is turned on by default in both cases
1. Chunk level trancate（async）:
 MQ (kafka, pulsar, kinesis, google pubsub, nats): 
 redis
 Biquery https://github.com/risingwavelabs/risingwave/pull/17488
 mongodb dynamodb https://github.com/risingwavelabs/risingwave/pull/17645
 es opensearch https://github.com/risingwavelabs/risingwave/pull/17746
 jdbc
 
2. commit_checkpoint_interval > 1
Starrocks
clickhouse
Datalake
iceberg

3. The special can't async because of the interface, but decouple was enabled before, so it stays as is.
mqtt

Not supported async commit_checkpoint_interval now
doris + snowflake: It's also possible to implement commit_checkpoint_interval, but it hasn't been done yet because there's no demand for it 
cassandra  http: java connector node, need to implement Java async，and HTTP is a test for the Flink interface, so it seems that our current strategy is not to recommend using it
sql server: commit by Barrier

**Comment by xxhZs** [comment]
Currently supports default sink_decouple = true sink:
1. chunk level trancate(async)
all mq (only mqtt cannot support async, But because it has been turned on sink_decouple before, it remains turned on); redis; jdbc
biquery https://github.com/risingwavelabs/risingwave/pull/17488
Elasticsearch/opensearch https://github.com/risingwavelabs/risingwave/pull/17746
mongodb+dynamodb https://github.com/risingwavelabs/risingwave/pull/17645
2. commit_checkpoint_interval > 1 default sink_decouple  = true
delatlake iceberg starrocks clickhouse

Currently dont supports sink_decouple = true sink:
snowfalke doris Can support commit_checkpoint_interval , but no user requirements are not realized
cassandra,http: java interface
sql server: barrer commit

**Comment by fuyufjh** [comment]
Thank @hzxa21 for summarizing the status quo. 

After some thoughts, I'd like to propose to enable `sink_decouple` for all sinks (again). Reasons:

1. First of all, my motivation is to provide a consistent experience for users. We need to clearly answer the question: How does RisingWave behave when the sink goes wrong? The answer is completely different for the case of `sink_decouple=true/false`, which confuses users a lot.
2. It increases the stability of clusters, which is exactly the initial motivation of log store. The performance concern is less important here because the bottleneck of a sink is very like to be something else, especially for these unsupported ones (Snowfalke, Cassandra), I bet their bottleneck must not be on the log store :)
3. Also, reduce mind burden for our engineers. For example, we can rely on the retrying logic provided by log store, so that the `SinkExecutor` can return `Err` safely. The less branches, the more robustness.

**Comment by fuyufjh** [comment]
> 2\. `commit_checkpoint_interval > 1` default `sink_decouple  = true`
>     `` delatlake ``iceberg ``starrocks ``clickhouse ``

For data lakes `delatlake` and `iceberg`, I think they are supposed to write in low frequency, perhaps we should set a higher default value of `commit_checkpoint_interval` for them, such as 10 secs.

For data warehouses, there is indeed some additional runtime cost, but I'd like to trade this off for better stability.

**Comment by pjpringlenom** [comment]
For sink decouple with upsert. Does this result in the conflation of multiple updates on the same key with in commit_checkpoint_interval ? I.e. reduce number of updates being sent per key

**Comment by xxhZs** [comment]
> For sink decouple with upsert. Does this result in the conflation of multiple updates on the same key with in commit_checkpoint_interval ? I.e. reduce number of updates being sent per key

Hello, the answer is no, sink decouple is just a simple replay of the sink value and is not designed to compress the same key

**Comment by fuyufjh** [comment]
> For sink decouple with upsert. Does this result in the conflation of multiple updates on the same key with in commit_checkpoint_interval ? I.e. reduce number of updates being sent per key

Good point. If there are many duplicates in the output data of each `commit_checkpoint_interval`, this can help to dedup. 

Currently the decoupling is implemented by a very simple structured called log store. As the name implies, it just records input events one by one without doing any optimization like compacting the events under the same PK. We have not encountered such cases yet that deduplicating here can help a lot, but if anyone have met such cases, we may consider applying this optimization.

**Comment by xxhZs** [comment]
https://github.com/risingwavelabs/risingwave/pull/18182
