### ISSUE TITLE
Tracking: automatically schema change for cdc table

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#17643]
We are going to support the automatic schema change for MySQL CDC. When upstream executed a `ALTER TABLE  ADD/DROP column` statement, it will be replicated automatically to the corresponding `Table`.

- [x] Extend the CDC connector to emit and parse the schema change message https://github.com/risingwavelabs/risingwave/pull/17707
- [x] Source executor initiate a RPC to the Meta to start the config change procesure https://github.com/risingwavelabs/risingwave/pull/17876
  - construct a streaming graph for the new Table job, this is **challenging** since the schema change is initiated from CN instead of FE
  - pass the new streaming graph to Meta and start the config change process

- [x] Save failed auto schema change DDL into event log
- [x] Fill in the newly added `cdc_table_id` field in `Table` catalog
- [ ] https://github.com/risingwavelabs/risingwave/issues/17985
