### ISSUE TITLE
Tracking: deprecate etcd metastore

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#18727]
### Is your feature request related to a problem? Please describe.

- [x] [integration and recovery simulation tests](https://github.com/risingwavelabs/risingwave/pull/18678)
- [x] [other ci tests](https://github.com/risingwavelabs/risingwave/pull/18099)
- [x] chaosmesh and longevity tests
- [x] [etcd metastore code clean](https://github.com/risingwavelabs/risingwave/pull/18621)
- [x] doc updates, including operator, helm etc.

**Comment by yezizp2012** [comment]
Opened an issue for doc updates: https://github.com/risingwavelabs/risingwave-operator/issues/711
