### ISSUE TITLE
Tracking: reduce unnecessary computation in OverWindow

### ISSUE THREAD

**Issue by stdrc** [risingwavelabs/risingwave#18972]
- [ ] For any `rank`-series, stop the iteration early when the output (rank number) is not changed any more. https://github.com/risingwavelabs/risingwave/pull/18950
- [ ] If changes in input row are not related to partition key, order key and window function arguments, the changes can be emitted to upstream directly. This is a little bit similar to #12201.
- [ ] For any `rank`-series and aggregate functions that supports incremental computation, jump to the first current key directly instead of sliding one by one.
- [ ] For `dense_rank`, if a newly inserted row has same value with existing ones, then no other rows need to be updated.
