### ISSUE TITLE
Tracking: remaining refactoring and tests for sql meta store

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#19106]
### Is your feature request related to a problem? Please describe.

- [x] #19521 
- [ ] deprecate `TableFragments` together with `actor` and `actor_dispatcher` tables. Let `build`, `scale` and `recovery` support the generation of actors in memory, reduce the writing of metastore, and reduce the memory occupation of meta node. related: https://github.com/risingwavelabs/risingwave/issues/18094
- [ ] #23655
- [ ] re-enable backup unit tests.
- [x] add e2e test for pg/mysql metastore in pr/main-cron
  * #19152 
- [ ] investigate whether in-memory sqlite can be used in the simulation test, including reorganization of the integration simulation test that needs kill operation.
- [ ] support transactional commit of metadata for replace table.
- [ ] remove compatible id allocation for `table`, `actor` and `fragment`.
