### ISSUE TITLE
Tracking: time-series related functions

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#19343]
### Downsampling (with gap-filling)

https://questdb.io/docs/reference/sql/sample-by/#fill-options
https://docs.timescale.com/api/latest/hyperfunctions/downsampling/
https://www.timescale.com/blog/how-to-proactively-manage-long-term-data-storage-with-downsampling/
https://docs.timescale.com/api/latest/hyperfunctions/gapfilling/time_bucket_gapfill/

three common filling strategies: 

- [ ] Use `locf` to carry the last value forward
- [ ]  Use `interpolate` to linearly interpolate the value 
- [ ] Fill in NULL by default

### Agg Helper Functions

- [ ] Candlestick: https://docs.timescale.com/api/latest/hyperfunctions/financial-analysis/candlestick_agg/#candlestick

- [ ] Rollup. This function must work with an aggregation function. 
    1. For example, if we aggregate per minute in an MV, we can reuse the results and further aggregate the values per hour in a second MV on MV. However, “reusing” is not always straightforward. “sum” and “max” are easy, but what if it is “average” and other approximated statistical aggregations? It would be hard for users to write them directly in SQL.
    2. Rollup can work with the ”candlestick_agg” too.

### Mathematics and Statistics

- [ ] weighted moving average and more generally as covered by InFluxDB’s “technical analysis” functions: https://docs.influxdata.com/enterprise_influxdb/v1/query_language/functions/#technical-analysis
        
    1. CHANDE_MOMENTUM_OSCILLATOR
    2. RELATIVE_STRENGTH_INDEX

- [ ] one-variable statistical aggregation. The following ones are used often in risk calculation, e.g. tail risk and VAR risk that need to be monitored in real-time. https://docs.timescale.com/api/latest/hyperfunctions/statistical-and-regression-analysis/stats_agg-one-variable/

    1. kurtosis
    3. skewness
    4. stdev

- [ ] two-variable statistical aggregations. https://docs.timescale.com/api/latest/hyperfunctions/statistical-and-regression-analysis/stats_agg-two-variables/. Similar use cases as above. Just highlight a few common ones:

    1. correlation
    2. covariance
    3. regr_slope and regr_intercept

**Comment by fuyufjh** [comment]
`ROLLUP` is supported https://github.com/risingwavelabs/risingwave/pull/11119

**Comment by fuyufjh** [comment]
The left part is

1. Gap-filling aggregation. Can be done either by
   - (Preferred) Extend `GROUP BY` e.g. `SAMPLE BY` , wich means `GROUP BY` with gapfilling
   - Extend `TVF` e.g. `TUMBLE` -> `tumble_with_gap_filling`
   - The former one is preferred because it's easier to support interpolating.
2. Aggregation functions
   - See *Mathematics and Statistics*

**Comment by riaan53** [comment]
I'm glad this is getting some attention. I can share some of the things I'm trying to do that might help with direction. I'm working with a lot of IoT data that needs to be downsampled to specific intervals with aggregation functions, gap-filled only up to a maximum duration, then filled with nulls or other values to indicate the sensor is offline. Sampled timestamps should always be continuous so sensors can be compared, correlated, pulled into ML sequences, etc. Interpolation functions can vary—LOCF and linear are common but don’t cover all IoT sensor types.

Note that `generate_series ` does not work on historical data, especially for streaming, if you do it with smaller timestamp like 1s the cluster falls over for more than a few hours of data. I had to specifically use it only if the timestamp is missing. This query also does not work for the next values or in real time if the last point is unavailable.

Also see: https://www.timescale.com/blog/sql-functions-for-time-series-analysis/

```
create MATERIALIZED VIEW signals AS
WITH hop_data AS (
    SELECT
        name AS sensor_name,
        window_start,
        window_end,
        COUNT(value) AS data_count,
        AVG(value) AS total_value
    FROM HOP(sensor_data, timestamp, INTERVAL '1 MINUTE', INTERVAL '1 MINUTE')
    GROUP BY name, window_start, window_end
),

global_max_timestamp AS (
    SELECT MAX(window_start) AS max_timestamp FROM hop_data
),

lead_data AS (
    SELECT
        hd.sensor_name,
        hd.window_start,
        hd.window_end,
        hd.total_value,
        COALESCE(
            LEAD(hd.window_start) OVER (PARTITION BY hd.sensor_name ORDER BY hd.window_start),
            (SELECT max_timestamp FROM global_max_timestamp) + INTERVAL '1 MINUTE'  -- Include last interval
        ) AS next_window_start
    FROM hop_data hd
),

missing_intervals AS (
    SELECT
        sensor_name,
        generate_series(
            (window_start + INTERVAL '1 MINUTE')::timestamp,
            (next_window_start - INTERVAL '1 MINUTE')::timestamp,
            INTERVAL '1 MINUTE'
        ) AS missing_timestamp
    FROM lead_data
    WHERE next_window_start - window_start > INTERVAL '1 MINUTE'
),

combined_data AS (
    SELECT
        sensor_name,
        total_value,
        window_start,
        window_end,
        TRUE AS is_observed
    FROM hop_data
    UNION ALL
    SELECT
        sensor_name,
        NULL AS total_value,
        missing_timestamp AS window_start,
        missing_timestamp + INTERVAL '1 MINUTE' AS window_end,
        FALSE AS is_observed
    FROM missing_intervals
),

data_with_last_observed AS (
    SELECT
        sensor_name,
        window_start,
        window_end,
        total_value,
        is_observed,
        MAX(CASE WHEN is_observed THEN window_start ELSE NULL END) OVER (
            PARTITION BY sensor_name ORDER BY window_start
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS last_observed_time,
        MAX(CASE WHEN is_observed THEN total_value ELSE NULL END) OVER (
            PARTITION BY sensor_name ORDER BY window_start
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS last_observed_value
    FROM combined_data
)

SELECT
    sensor_name,
    window_start,
    window_end,
    CASE
        WHEN last_observed_time IS NOT NULL
             AND window_start - last_observed_time <= INTERVAL '5 MINUTES' THEN last_observed_value
        ELSE 0  -- Fallback value for gaps beyond 5 minutes
    END AS interpolated_value
FROM data_with_last_observed
ORDER BY sensor_name, window_start;

```

I have not tested the performance with this but would assume it would not be the best. This is just an example i swop out parts in code for different aggregation function and interpolations. But cant get it to fill gaps if there is no next value for realtime data. Hope it helps and let me know if you need me to test out some things.

**Comment by lmatz** [comment]
![Image](https://github.com/user-attachments/assets/b8929bed-743f-4fe5-8e69-9a38c7a0cf79)

saw users are implementing `Candlestick` by themselves
