### ISSUE TITLE
Tracking: Improve SQL observability commands: EXPLAIN/DESCRIBE/ANALYZE

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#19361]
Open to community contributors 😄. You will get a chance to familiarize with parts of the parser/binder/optimizer. This will be useful functionality for users as well.

- [x] https://github.com/risingwavelabs/risingwave/issues/19123
- [x] https://github.com/risingwavelabs/risingwave/issues/18803
- [ ] https://github.com/risingwavelabs/risingwave/issues/17218
- [x] https://github.com/risingwavelabs/risingwave/issues/21432
- [ ] #21150 
- [x] Support `EXPLAIN(backfill, format dot)`. This should print the backfill graph, and also the backfill tree for auto derived backfill.
