### ISSUE TITLE
Tracking: Iceberg engine table

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#19418]
# Milestone 1
- [ ] create table (non-atomic ddl) including creating a hummock table, iceberg sink, external iceberg table, and iceberg source.
- [ ] drop table (non-atomic ddl) including dropping a hummock table, iceberg sink, external iceberg table, and iceberg source.
- [ ] direct DQL to the iceberg source.
- [ ] direct DML to the hummoc table.
- [ ] allows for creating a materialized view on top of the table with an iceberg engine.
- [ ] iceberg catalog: SQL/JDBC catalog
- [ ] iceberg warehouse: S3

# MileStone 2
- [ ] complete data type support
- [ ] atomic create table
- [ ] atomic drop table
- [ ] alter table add column
- [ ] alter table change engine
- [ ] EMR serverless compaction & expiration
- [ ] backup &  restore

# MileStone 3
- [ ] Rust based compaction and expiration
- [ ] local disk cache for iceberg table meta and data
- [ ] iceberg batch query performance (including predicate pushdown and merge on read)
