### ISSUE TITLE
Tracking: webhook optimization

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#19585]
Most of the work of webhook has been done in https://github.com/risingwavelabs/risingwave/pull/19272. 
However, there're still several TODO:
Performance
-  [ ] Using session pool to avoid creating a session and converting expr per event.
Test
-  [ ] Refactor test scripts.
-  [ ] Add more tests, especially the tests for various corner cases.
-  [ ] Benchmark test
Functionality
-  [ ] Support Shpoify.
-  [ ] Support generated columns or INCLUDE clause.
