### ISSUE TITLE
Tracking: Exactly once semantics for some sinks

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#19678]
After discussion, we will use the log store to implement the exactly once semantics of some sinks.

To achieve "exactly once", we need to ensure that the data sent to the external sink is written only once. The key here is that if we can know the location of the data in the log store, and the downstream sink provides a way to perform idempotent query operations whether a bunch of data exist in downstream sinks, we can decide how to handle the data in the log store during recovery based on the visibility of the downstream: either rewind or truncate it.

Roadmap

- [ ] Implement exactly once iceberg sink
  - [ ] persist metadata and log store location
  - [ ] processing recovery logic based on persistent information(re commit or rewind log store)
  - [ ] clean up persistent metadata promptly
- [ ] Implement exactly once file sink
  - [ ] persist metadata and log store location
  - [ ] processing recovery logic based on persistent information(re commit or rewind log store)
  - [ ] clean up persistent metadata promptly
- [ ] ...
