### ISSUE TITLE
batch: Local execution mode for serving highly concurrent queries.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#1974]
Implement local execution mode for serving highly concurrent queries according this design: https://github.com/singularity-data/risingwave/blob/main/docs/batch-local-execution-mode.md

Optimizer:

- [x] #2334
- [x] #3450
- [ ] Implement plan cache.

Executor:

- [x] Refactor batch executor mod to support it to run on frontend.
- [x] #2809
- [x] #2754
- [ ] Cache data during two epochs.
- [x] #2364
- [x] #3481
- [x] #5013 
- [x] #5014
- [x] #5106

Test:

- [x] Move more e2e test to local modal.
- [x] Setup performance test.
- [ ] #5015

**Comment by twocode** [comment]
What kind of benchmark would be used for this scenario? YCSB? Sysbench?

**Comment by liurenjie1024** [comment]
> What kind of benchmark would be used for this scenario? YCSB? Sysbench?

I think both are ok.
