### ISSUE TITLE
Tracking: AWS Glue Schema Registry for sources and sinks

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#19804]
- [x] Source with `encode avro`
- [ ] Sink with `encode avro` (WIP)
- [ ] Source with `encode protobuf`
- [ ] Sink with `encode protobuf`
- [ ] Source with `encode json`
- [ ] Sink with `encode json`
- [ ] `create connection`
