### ISSUE TITLE
Tracking: cross-MV state sharing

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#2016]
https://singularity-data.quip.com/xrgPARGiVv9W/Cross-MV-State-Sharing-and-Create-Index

## Create Index Statements, Use Indexes

- [x] https://github.com/singularity-data/risingwave/issues/2015
- [x] https://github.com/singularity-data/risingwave/issues/2017
- [ ] https://github.com/singularity-data/risingwave/issues/2013
- [x] https://github.com/singularity-data/risingwave/issues/1909
- [x] https://github.com/singularity-data/risingwave/issues/1908
- [ ] https://github.com/singularity-data/risingwave/issues/2195
- [ ] https://github.com/singularity-data/risingwave/issues/2211

## State Sharing (on multiple worker nodes)

- [x] https://github.com/singularity-data/risingwave/issues/1881
- [ ] https://github.com/singularity-data/risingwave/issues/1912
- [x] https://github.com/singularity-data/risingwave/issues/2099
- [x] https://github.com/singularity-data/risingwave/issues/2145
- [x] https://github.com/singularity-data/risingwave/issues/2151

## Delta Join

- [x] https://github.com/singularity-data/risingwave/issues/1807
- [x] https://github.com/singularity-data/risingwave/issues/1751
- [x] https://github.com/singularity-data/risingwave/issues/1661
- [x] https://github.com/singularity-data/risingwave/issues/885
- [x] https://github.com/singularity-data/risingwave/issues/719
- [x] https://github.com/singularity-data/risingwave/issues/1964
- [x] https://github.com/singularity-data/risingwave/issues/1882
- [x] https://github.com/singularity-data/risingwave/issues/2045
- [x] https://github.com/singularity-data/risingwave/issues/2076

## Multi-way Joins

- [x] https://github.com/singularity-data/risingwave/issues/1962
- [x] https://github.com/singularity-data/risingwave/issues/1907
- [x] https://github.com/singularity-data/risingwave/issues/2147
- [x] https://github.com/singularity-data/risingwave/issues/2146
- [x] https://github.com/singularity-data/risingwave/issues/2148

## Misc

- [x] https://github.com/singularity-data/risingwave/issues/1971
- [ ] https://github.com/singularity-data/risingwave/issues/1863
- [x] https://github.com/singularity-data/risingwave/issues/1791
- [x] https://github.com/singularity-data/risingwave/issues/1906
- [x] https://github.com/singularity-data/risingwave/issues/1901

**Comment by jon-chuang** [comment]
Is shared state intelligent enough to identify arrangements which are a superset of the desired input (e.g. need to project/filter)

**Comment by skyzh** [comment]
Nope. That’s why we are moving filter and column reordering projections inside LogicalScan, so that we can have more information when reusing arrangement. https://github.com/singularity-data/risingwave/issues/2343

**Comment by skyzh** [comment]
e.g. if we push down filter into scan, the logical plan will be like MultiWayJoin with n LogicalScan children. This pattern is very easy to detect.
