### ISSUE TITLE
Implement CONCAT_WS

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#2405]
Implement `CONCAT_WS`.

Example: `concat_ws(',', 'abcde', 2, NULL, 22)` => `abcde,2,22`

Split into multiple PR:
- [x] Evaluation of `concat_ws`, to handle strings. #2470
- [x] Parsing, typechecking, binding, (includes implicit `cast` of `concat_ws` arguments into strings.). #2589
- [x] Add e2e tests for `timestamp` and other **time related** data types as arguments. This is pending casts from `timestamp` to `varchar`. See #112 

Reference:
https://www.postgresql.org/docs/9.1/functions-string.html

#112

**Comment by skyzh** [comment]
> convert non-null Datums in the row into strings, concat all strings with separators

You may assume that concat_ws will always have string as parameter, and let the SQL frontend to insert the cast function for you. I guess this would make things easier.

**Comment by kwannoel** [comment]
> > convert non-null Datums in the row into strings, concat all strings with separators
> 
> You may assume that concat_ws itself will always have string as parameter, and let the SQL frontend to insert implicit cast function for you. I guess this would make things easier.

Apologies, I realized my original comment was ambiguous with regards to how I handle NULL values as arguments to concat_ws.

With the suggested approach, how do I handle `null` values as arguments to `concat_ws`? These might only surface during runtime, SQL frontend can only remove literal `NULL` values.

I'm thinking of just using `Datum`, then within the `eval` function we can check if `Datum` is `NULL` or not, and skip it if it is, otherwise concatenate it, after casting it into a `String`.

**Comment by xiangjinwu** [comment]
`Datum` is a nullable value of **any type**. The comment above suggests to simplify this problem into handling nullable values of **string**, which are `Option<&str>` from `Utf8Array`. The frontend can generate sub-exprs (`Expr::Cast`) to make sure all arguments (`ArrayImpl`) passed to `concat_ws` in backend are always `Utf8Array`.

No matter it is `Datum` (`Option<ScalarImpl>`) or `Option<&str>`, the handling of `null` is the usual way of handling `Option::None` is rust.

In the non-null case, it is easier this way because the conversion from `ScalarImpl` to `String` is just reusing `cast` (which is yet to be implemented). To keep PRs small, we can support concat of strings first and add those casts in a follow up.

**Comment by kwannoel** [comment]
> `Datum` is a nullable value of **any type**. The comment above suggests to simplify this problem into handling nullable values of **string**, which are `Option<&str>` from `Utf8Array`. The frontend can generate sub-exprs (`Expr::Cast`) to make sure all arguments (`ArrayImpl`) passed to `concat_ws` in backend are always `Utf8Array`.
> 
> No matter it is `Datum` (`Option<ScalarImpl>`) or `Option<&str>`, the handling of `null` is the usual way of handling `Option::None` is rust.
> 
> In the non-null case, it is easier this way because the conversion from `ScalarImpl` to `String` is just reusing `cast` (which is yet to be implemented). To keep PRs small, we can support concat of strings first and add those casts in a follow up.

Need some further clarification. Am confused by the term "implicit cast". It was mentioned [here](https://github.com/singularity-data/risingwave/pull/2427#discussion_r870908612) that I will still need to explicitly call `cast_explicit` on all the arguments. Is it called implicit because that the type we are casting to is not explicitly a varchar, but a function call which will do a cast in runtime?

On the backend, is the idea to:
1. evaluate argument expressions to an `ArrayImpl` i.e. `expr.eval(input)`.
2. Convert `ArrayImpl` into `Utf8Array`
3. Call `concat_ws` on the Utf8Arrays?

If so, how should I go about converting `ArrayImpl` to `Utf8Array`, is there a safer way than just unwrapping the ArrayImpl?
Is there an idiomatic way to transpose a vector of `Utf8Array`? My understanding is that each `Utf8Array` is a column, and we want to transpose to pass rows into `concat_ws`.


Thanks for your patience in answering my questions :pray:

**Comment by xiangjinwu** [comment]
`implicit` vs `explicit` is from the database user's perspective: `CAST(123 AS varchar)` and `123::varchar` are explicit, while `substr(123, 2)` and `concat(123, 'foo')` are implicit. As mentioned above, implicitly casting to varchar reports an error in most cases (e.g. `substr` here) except for `concat`. So we need to use the call `cast_explicit` (rather than `cast_implicit`) although the cast expr is implicitly added by us (db developer) rather than explicitly written by db user.

The high level idea of backend 1&2&3 is correct.
* To convert from `ArrayImpl` to `Utf8Array`, there is `as_utf8` and `into_utf8`.
* As for vector transpose... There is currently no utilities to convert between column-major and row-major. Just use nested for-loops to make it working first, and see if it is possible to improve from there.

**Comment by kwannoel** [comment]
> may put "closes #XXXX" in the PR to close the related issue automatically after the PR is merged.

Not closed yet, because still have frontend changes to be made.

**Comment by xiangjinwu** [comment]
FYI casting from numbers is WIP: #2522
