### ISSUE TITLE
Tracking: Extended SQL support in Binder & Planner

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#2656]
Basic SQL support: #338

Extended support:
* [x] struct type (aka row)
* [x] list type (aka array)
* [x] hop window function https://github.com/singularity-data/risingwave/pull/1980
* [x] https://github.com/singularity-data/risingwave/issues/454
* [x] #2619
* [x] #2911
* [ ] https://github.com/risingwavelabs/risingwave/issues/9284
* [x] #2317
* [x] #2708
* [x] #1343

**Comment by xxchan** [comment]
Close since there's only one left. Track there.
