### ISSUE TITLE
Tracking: missing features to support the user behavior example

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#3007]
See: 
- https://flink.apache.org/2020/07/28/flink-sql-demo-building-e2e-streaming-application.html
- https://singularity-data.quip.com/7FkaAmL8UzAl/E-commerce-user-behavior-analysis-Assignee-Eric-Fu

To do:

- [x] https://github.com/singularity-data/risingwave/pull/3094
- [x] https://github.com/singularity-data/risingwave/issues/146
- [x] https://github.com/singularity-data/risingwave/issues/3003
- [x] https://github.com/singularity-data/risingwave/issues/3006

Optional features (need further discussion):

- [ ] Create View 
- [ ] Processing time as a column
