### ISSUE TITLE
Tracking: improve scan_range

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#3477]
- [ ] support multiple ranges. e.g., `select from table where x > 10 or x < 5`, and `in` 
  - https://github.com/singularity-data/risingwave/pull/3756 `in` supported
  - [ ] #4205
- [x] #3507 store `Datum` with the correct data type instead of `expr`, so that we can calculate vnode and prune partitions
  - [x] cast to proper type (workaround in https://github.com/singularity-data/risingwave/pull/3470 & moved to fe in #3507)
- [ ] support constant expression instead of only literal expression. 
  - #4155
  - [ ] support converting constant with larger type than the column, e.g., `select * from t where v1 < 60000 -- v1 is smallint`
- [x] #4896

**Comment by fuyufjh** [comment]
related: #3479

**Comment by xxchan** [comment]
To calculate the vnodes to prune paritition (https://github.com/singularity-data/risingwave/issues/3450), we have to store evaluated `Datum` in scan_range 🤔
