### ISSUE TITLE
Tracking: Introduce row-based encoding for internal state

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#3615]
As we have done some investigation and discussion on row-based ([row-based encoding](https://singularity-data.quip.com/5TutAoAlk6Oa/RFC-Row-based-encoding-in-relational-table-layer)), it's time to introduce row-based encoding for out internal system, and here is the roadmap:

- [x] #3616
- [x] Implement row-based encoding 1.0 with value encoding.
- [x] #4036
- [x] #4106
- [x] Implement `join` executor's  read/write path with row-based encoding (block until [#3254](https://github.com/singularity-data/risingwave/issues/3254) resolved).
- [x] #4367
- [x] Design an efficient row-based format.
- [x] Benchmark row-based encoding and cell-based encoding more detailed.

Related issue [cell-based relational table](https://github.com/singularity-data/risingwave/issues/849).
