### ISSUE TITLE
Tracking:Pgwire Extended Query Mode

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#3676]
- [x] #2924 
- [x]  #3131 
- [x]  #3294 
- [x]  #3392 
- [x]  #3592 
- [x] #3829
- [x] #4374
- [x]  #4049 
- [x] #4288

related: #2621

**Comment by BowenXiao1999** [comment]
Cool! I think after this Tracking we'll have a MVP pg-wire layer

**Comment by ZENOTME** [comment]
Extended query mode can support almost statement without params (except binary format of some type:
- struct
- list 
- interval

We have the poor support for statement with params. For now we only can support 'select $1,$2,$3..'. 
As we know for now, to support statement with params, we need to do
- [ ] supports more complex statement 'select ** where  ** = $1 '
- [ ] infer params type e.g. ($1,$2)

**Comment by BowenXiao1999** [comment]
There are some usecases of prepared statement in bench: https://singularity-data.quip.com/qqEzA045G2ac/Design-Sysbench-combined-with-TPCH. We can take it for ref or target for it.

**Comment by ZENOTME** [comment]
After #5498 is complete,
We can support most of extended query mode now, including:
- extended query mode message flow
- all text format param 
- all text format result 
- all kind of prepare statement with param

**There are still some remained type format not be supported, including:**

- [ ] binary format param
  - [ ] struct 
  - [ ] list
  - [ ] interval 
  - [ ] timestampz 
- [ ] binary format result 
  - [ ] struct 
  - [ ] list
  - [ ] interval 
  - [ ] timestampz 

If the client uses text format, extended query mode can be used.
If the client uses binary format, **except the type still not be supported**, the extended query mode can be used too.

**Comment by BowenXiao1999** [comment]
Done some research on other postgresql database (Mz). 

For binary format, seems only list and map and not easy to implemented. 
https://github.com/MaterializeInc/materialize/blob/61a82dfd8432b094189c4f839f67ab738f0f3bc1/src/pgrepr/src/value.rs#L390-L421

https://github.com/MaterializeInc/materialize/blob/61a82dfd8432b094189c4f839f67ab738f0f3bc1/src/pgwire/src/protocol.rs#L693-L701
