### ISSUE TITLE
Tracking: implement ProjectSet operator

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#3814]
- [x] https://github.com/singularity-data/risingwave/pull/3813
  * [ ] rename TableFunction operator to FunctionScan
- [x] https://github.com/singularity-data/risingwave/pull/3882
- [x] https://github.com/singularity-data/risingwave/pull/3931
  * [ ] fix TODOs 
- [x] https://github.com/singularity-data/risingwave/pull/4030
- [ ] table functions in agg

**Comment by xxchan** [comment]
Finished. Some minor improvements are left undone, but won't be tracked anymore.
