### ISSUE TITLE
Tracking: use `stream_key` instead of `pk`

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#3957]
in https://singularity-data.quip.com/3lUJAQMthect/RFC-Streamkey-instead-pk, we introduce the `stream_key` instead of `pk`. the `stream_key`'s derivation should consider the append-only and distribution keys, so we should derive it in the streaming optimization phase instead of the logical phase.

<del>- [ ] add `stream_key` in the `plan_base` and derive it in `to_stream`</del>
- [ ] add the `stream_key` derive in `to_stream` (use the current `rewrite for stream`) https://github.com/singularity-data/risingwave/pull/4275
- [ ] remove the old `pk` in the `plan_base`
- [ ] rename the `pk` in the plan
