### ISSUE TITLE
SqlSmith: Additional Subtask of Agg function

### ISSUE THREAD

**Issue by marvenlee2486** [risingwavelabs/risingwave#3964]
References: https://www.postgresql.org/docs/14/sql-expressions.html
see 4.2.7 Aggregate Expression and 4.2.8 WIndow Function

Currently, the Agg function is implemented (with distinct only) and no other parameters is in it. 
Supposingly
```
Function{ name, args ,over, distinct, order_by, filter}
```
name is the name of the agg func and args is basically the input expression. 

Generally the implementation of agg function in this PR #3932 involve aggregate function without additional parameter (except distinct). Therefore, there is a few subtask additional to the agg function,
- [x] Implementation of Agg function itself #3932
- [x] Implementation of choosing either distinct  or approx../orderby but not both #3933 
- [ ] Implementation of Order-by for Agg
- [ ] Implementation of Over (Window Function) for Agg 【Hold on because feature has not yet implemented  https://github.com/singularity-data/risingwave/issues/3963】
- [ ] Implementation of FIlter for Agg
- [ ] Implementation of ALL for Agg (This is the default option, that wihtout distinct, whatever) shall we not implement this?

Based on the postgresql resource i share above,
There is aggregation function (distinct, filter, all)
There is window function (distinct, filter, all) 

Therefore, all these case shall needed to be implemented so that the corresponsding feature are able to reuse in both case.

**Comment by fuyufjh** [comment]
Can somebody help to summarize what is missing for SqlSmith now? This issue seems to be very out-of-date.
