### ISSUE TITLE
Tracking Issue: Sink

### ISSUE THREAD

**Issue by nanderstabel** [risingwavelabs/risingwave#4143]
Tracking issue for everything related to Sink

Sinks:
- [x] Kafka: #3942
- [x] MySQL: #3877 
- [x] #4197
- [ ] elastic search 

E2E testing:
- [x] #4398
- [ ] e2e testing for MySQL: #4198
- [ ] #4240

Bug fix/Refactor:
- [x] fix sink from aggregated mv: #4067
- [x] remove sink crate: #4152
- [x]  infinite loop when drop sink + drop table: #4302
- [x] schema mismatch when writing to mysql: #4303
