### ISSUE TITLE
Tracking Issue: Index.

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#4339]
Tracking issue for everything related to Index.

# Basic Feature:
- [x] meta: catalog #4340
- [x] optimizer: batch covering index selection #4520
- [x] optimizer: batch non-covering index selection #4587
- [x] optimizer: batch index merge optimization #4820
- [x] batch executor: index lookup join in distributed mode #4647
- [x] optimizer, scheduler: dml support index lookup #4701

# Enhancement
- [x] optimizer: improve index range cost #4877

# Performance
- [x] bench: performance test

**Comment by chenzl25** [comment]
https://singularity-data.quip.com/9racAbR17zmC/SysBench-For-RisingWave
