### ISSUE TITLE
Tracking: Critical Stability Issues

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4543]
This is a tracking issue for the critical bugs found during stress tests. They may either cause the system to crash or stuck, which are deadly threats to the production deployment.

As we know that stability & reliability is one of the most important objectives of this quarter, so let's take them as the first priority.

Please feel free to append your issues into this list.

- [x] https://github.com/singularity-data/risingwave/issues/3909
- [x] https://github.com/singularity-data/risingwave/issues/4270
- [x] https://github.com/singularity-data/risingwave/issues/4354
- [x] https://github.com/singularity-data/risingwave/issues/4365
- [x] https://github.com/singularity-data/risingwave/issues/4427
- [x] https://github.com/singularity-data/risingwave/issues/4429
- [x] #4547 
- [x] #4553
- [x] #4735
- [x] #4755
- [ ] #4762
- [x] #4774
- [x] #4790
- [x] https://github.com/singularity-data/risingwave/issues/4817
- [x] https://github.com/singularity-data/risingwave/issues/4857
- [x] https://github.com/singularity-data/risingwave/issues/4861
- [x] https://github.com/singularity-data/risingwave/issues/4870
- [x] https://github.com/singularity-data/risingwave/issues/4894
- [x] https://github.com/singularity-data/risingwave/issues/4918
- [x] https://github.com/singularity-data/risingwave/issues/4919
- [x] https://github.com/singularity-data/risingwave/issues/4921
- [x] https://github.com/singularity-data/risingwave/issues/4922
- [x] https://github.com/singularity-data/risingwave/issues/4927
- [x] #5012
- [x] https://github.com/risingwavelabs/risingwave/issues/5157
- [x] https://github.com/risingwavelabs/risingwave/issues/5209
- [x] https://github.com/risingwavelabs/risingwave/issues/5220
- [x] #5274 
- [x] #5316 
- [x] #5353
- [x] https://github.com/risingwavelabs/risingwave/issues/5392
- [x] https://github.com/risingwavelabs/risingwave/issues/5393
- [x] #5587
- [x] #5609
- [x] #5614
- [x] #5711
- [x] https://github.com/risingwavelabs/risingwave/issues/5726
- [x] #5755
- [x] #5773 
- [x] https://github.com/risingwavelabs/risingwave/issues/5833
- [x] https://github.com/risingwavelabs/risingwave/issues/5911
- [x] #6031 
- [x] #6093 
- [x] https://github.com/risingwavelabs/risingwave/issues/6200
- [x] #6343 
- [x] #6551 
- [x] #6561 
- [x] #6573

**Comment by neverchanje** [comment]
Seems we need to have a testing framework for the compactor. It's probably like pre-generating a set of fake SSTs and performing compaction multiple times with different settings.

**Comment by fuyufjh** [comment]
Almost all issues here have been fixed. From this month, I'll open another tracking issue to trace the performance & stability issues. Thanks, everyone! ❤️
