### ISSUE TITLE
Tracking: Grouping TopN based on SQL window function

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#4847]
Based on the previous discussion #3646 , we decide to use SQL window function to represent that, there are several sub tasks:

- [x] Bind SQL window function
- [x] Add `LogicalSqlWindowFunction` PlanNode and convert the specified pattern to `LogicalTopN`
  - [x] Support `rank < N`
  - [ ] #5692
  - [ ] (optional) support more complex condition
- [x] #5302
- [x] Add nexmark Q9, Q18, Q19 to test the result
  - [x] Q9 & Q18
  - [x] ~~Q19: requires output rank number (Won't support now)~~
- [ ] Support `rank()` besides `row_number()` (Similar to `WITH TIES` in normal TopN).
  - [x] #5486 
  - [x] #5538
  - [x] #5642
  - [x] #5691
