### ISSUE TITLE
Tracking(frontend): explain statement 

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#4856]
design doc: https://singularity-data.quip.com/fek1AUiMz5lz/RFC-Option-based-Explain-Syntax-and-Format
- [x] parse options https://github.com/singularity-data/risingwave/pull/4730 
- [ ] explain analyze https://github.com/risingwavelabs/risingwave/issues/896
- [x] options implementation
  - [x] trace
  - [x] verbose
  - [x] type
     - [x] physical
     - [x] logical
     - [x] distSQL   https://github.com/risingwavelabs/risingwave/issues/3710
   - [ ] format (must include format for distsql JSON -> Tree etc.) 
       - [x] https://github.com/risingwavelabs/risingwave/issues/14168
