### ISSUE TITLE
tracking: code camp - Exploit the order property for query optimization

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#4942]
- [x] https://github.com/singularity-data/risingwave/pull/4719
- [x] https://github.com/singularity-data/risingwave/pull/4903
- [x] sortAgg
  - https://github.com/risingwavelabs/risingwave/pull/5046
   - [x] add sortAgg plannode
   - [x] use sortAgg when input supply order 
  - https://github.com/risingwavelabs/risingwave/pull/5120
   - [x] use sortAgg when the required order(order passThrough)
   - https://github.com/risingwavelabs/risingwave/pull/5280
- [ ] Index 
   - [x] use covered Index for LogicalScan::to_batch with required order
   - https://github.com/risingwavelabs/risingwave/pull/5280
   - [ ] use secondary Index for LogicalScan::to_batch with required order
- [ ] sortMergeJoin(todo: add subtask here)

**Comment by st1page** [comment]
please add a comment and I can assign the issue to you :heart:   @GeorgKreuzmayr

**Comment by GeorgKreuzmayr** [comment]
> 

Alright, thanks! <3

**Comment by GeorgKreuzmayr** [comment]
> please add a comment and I can assign the issue to you ❤️ @GeorgKreuzmayr

Alright, thanks!  ❤️ @st1page

**Comment by st1page** [comment]
we will not use secondary index scan and SortMergeJoin for Order property now with out good cost-based estimation.
