### ISSUE TITLE
Tracking Issue: null safe equal join

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#4958]
# Background
[What is `IS NOT DISTINCT FROM`](https://www.postgresql.org/docs/current/functions-comparison.html)
Null safe means we treat `null = null` as true. In sql, we use `IS NOT DISTINCT FROM` expression to provide null safe equal.
Subquery unnesting rely on null-safe semantic join to provide correct result.
Some Issues like #4203 #4355 already detect such correctness problems.
`NestedLoopJoin` already supports null-safe semantic join, however, it is not efficient enough. So we hope null-safe semantic `HashJoin` to be supported.

BTW, index lookup join also need to use null safe equal type to match pk.

- [x] binder: Refactor `IS NOT DISTINCT FROM` expression #4962
- [x] optimizer: `EqJoinPredicate` support null-safe equal semantic #4983
- [x] optimizer: Replace subquery generated `Equal` with `IS NOT DISTINCT FROM` #5021
- [x] optimizer: Replace Index lookup pk `Equal` with `IS NOT DISTINCT FROM` #5076
- [x] batch: Modify `BatchHashJoinNode` #4983
- [x] batch: Modify `BatchLookupJoinNode` #5076
- [x] batch: `BatchHashJoinExecutor` support null-safe semantic join #4994
- [x] batch: `BatchLookupJoinExecutor` support null-safe semantic join #5076
- [x] batch: `ScanRange` support null-safe predicate #5054
- [x] stream: Modify `StreamHashJoinNode` #4983
- [x] stream: `StreamHashJoinExecutor` support  null-safe semantic join #5095
- [ ] batch: `SortMergeJoinExecutor`  support null-safe semantic join

**Comment by liurenjie1024** [comment]
Is this marker join?

**Comment by chenzl25** [comment]
> Is this marker join?

This is equal join but we can treat each equal pair whether to be null-safe equal which means `null = null` returns true.
