### ISSUE TITLE
Tracking: some refactor on Table Catalog

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#4976]
- [x] rename `order_key` to `pk`
- [x] check if the `is_index_on` is still used and try to remove it. https://github.com/risingwavelabs/risingwave/pull/5480
- [ ] create a `MView` message in proto like `Sink` or `Index`, then move all fields about streaming such as `stream_key` and `append_only` in it
   * add an MView proto message in meta store 
   * add MView catalogs in notify service and frontend
   * distinguish bind_table(in batch query) and bind_stream_table(MView/source, in streaming query ) in binder

**Comment by st1page** [comment]
After offline discussion, we find that the fields and properties is meaningful on all the storage table such as `watermark_columns` and `append_only`. So we stop to split the `Mview` catalog
