### ISSUE TITLE
Tracking: 2-phase `array_agg` and `string_agg`

### ISSUE THREAD

**Issue by richardchien** [risingwavelabs/risingwave#4998]
- [ ] `array_agg`
    - [ ] introduce a special agg call for global phase, `array_cat_agg`, which performs like `array_cat` but _aggregate_ all rows
    - [ ] enable 2-phase agg for `array_agg`
- [ ] `string_agg`
    - [ ] introduce a non-agg function, `join(array, delim)` (or `string_join`), to concatenate an array of strings
    - [ ] for calls with literal delimiters, enable 2-phase agg by reusing `array_agg` and `array_cat_agg`

**Comment by likg227** [comment]
may you provide a function to rewrite array_agg and string_agg to 2-phase agg e.g.` two_phase(array_agg: PlanAggCall) -> (PlanAggCall, PlanAggCall) `?
BTW, non-distinct agg appearing with distinct agg is disallowed in #4948. After you finish, you may reconsider this check.

**Comment by skyzh** [comment]
Do you expect this to be implemented in batch or stream? In stream, I suspect this will lead to unstable results from agg executor, which in turn affects the correctness of materialize.

**Comment by skyzh** [comment]
Consider there's a scale during two consecutive epochs with data unchanged. You must ensure that agg always has the same output before and after the scale. e.g., if we have a,b,c in the column which will be aggregated. If we produce the output from global agg like:

```
+a,b,c
---scale---
-b,c,a
+a,b,c,d
```

The two records `+a,b,c` `-b,c,a` won't match.

**Comment by skyzh** [comment]
... one solution is only allow string_agg with order by

**Comment by richardchien** [comment]
> ... one solution is only allow string_agg with order by

what about implicitly order by some column like `_row_id` if no order by clause is provided?

**Comment by skyzh** [comment]
That would be fine. 🥵

**Comment by skyzh** [comment]
Shall we also automatically transform limit 10 to limit 10 + order_by pk? 🤣

**Comment by likg227** [comment]
> Shall we also automatically transform limit 10 to limit 10 + order_by pk? 
Then we can remove Limit operator from our system. TopN is just enough.

**Comment by xiangjinwu** [comment]
> In stream, I suspect this will lead to unstable results from agg executor, which in turn affects the correctness of materialize.

Had a brief sync with @TennyZhuang several days ago about unstable results:
* User specified `order by` may not be enough because there may be ties
* #4953

**Comment by richardchien** [comment]
I believe for 2-phase `array_agg` and `string_agg`, the local results will be automatically ordered by pk if we reuse the current implementation. The problem is the new agg function to be introduced, `array_cat_agg`. To produce stable results, `array_cat_agg` will need to do a multiway merge ordered by pk instead of blindly concatenate all local results.

**Comment by richardchien** [comment]
As per some offline discussion, @st1page and I found that it will introduce undesirable complexity to implement the global phase of `array_agg`, `array_cat_agg`. When the query contains order-by clause, `array_cat_agg` is not as easy as blindly concatenating several arrays, instead, it should do ordered merge on all local results. This will be tricky if the column(s) ordered by is/are not the column to aggregate. So, we decided to suspend the implementation of this feature for now, until we have a better design.
