### ISSUE TITLE
Tracking: Minimal Frontend Framework in Rust

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#50]
This issue tracks the works to rewrite a basic frontend in rust.

This new frontend is expected to be a replacement for the current Java frontend, but they will coexist for several months. During this period, we may need two end-to-end tests for each frond-end respectively, until the new frontend can cover all features.

## Expected Features

In the first stage, we only support

* `CREATE TABLE`
* `DROP TABLE`
* `INSERT`
* `SELECT`
  * columns or constant values (no expressions allowed)
  * from one table (**no joins allowed**)
  * with very simple `WHERE` condition (column = constant)
* `CREATE MATERIALIZED VIEW`
  * Same as `SELECT`

## Components

- [ ] Postgres wire protocol: singularity-data/risingwave-legacy#2019 
- [ ] Server: #293 
- [x] Parser: singularity-data/risingwave-legacy#2170
- [x] Binder: singularity-data/risingwave-dev#338
- [ ] Optimizer: #109 
- [ ] Catalog: singularity-data/risingwave-dev#959
- [ ] Execution: singularity-data/risingwave-dev#202
- [ ] Query Manager: #1015 
- [ ] https://github.com/singularity-data/risingwave-dev/issues/838
- [x] #1219
