### ISSUE TITLE
Tracking: Support relational data model in Bummock

### ISSUE THREAD

**Issue by wyhyhyhyh** [risingwavelabs/risingwave#508]
Bummock will serve as a unified interface for table storage built on top of Hummock. 
See https://singularity-data.quip.com/lYozAfUcsvXV/Bummock-as-an-indexing-storage for  design doc. 

A roadmap includes:
- [ ] Implement a unified interface for collection. #573 
- [ ] Implement secondary index for table.
- [ ] Implement index scan batch executor.
- [ ] Implement index maintenance.
