### ISSUE TITLE
Tracking: Support Ch-benCHmark Queries

### ISSUE THREAD

**Issue by nanderstabel** [risingwavelabs/risingwave#5190]
Tracking issue for CH-benCHmark queries.

Resources:
https://db.in.tum.de/research/projects/CHbenCHmark/index.shtml
https://research.tableau.com/sites/default/files/a8-cole.pdf

## Notes
* TPC-C tables are explicitly prefixed `tpcc_`. This is in order to avoid confusion since both TPC-H and TPC-C have a customers and order(s) table.
* In the original CH-benCHmark queries the mathematical function `MOD()` is used. They are currently replaced by the modulo operator `%`.
* Table name prefix of `tpcc_stock` table is changed from `s_` to `st_` in order to distinguish it from the `supplier` table name prefix (in tpc-h).

### TPC-H
* `nation`
* `region`
* `supplier`

### TPC-C
* `tpcc_customer`
* `tpcc_district`
* `tpcc_history`
* `tpcc_item`
* `tpcc_neworder`
* `tpcc_order`
* `tpcc_orderline`
* `tpcc_stocks`
* `tpcc_warehouse`

A query is marked as supported if it has been added to the end-to-end test.

## SQL Features in Queries
| Query | Group-by (Aggregation) | Order-by (Sort/TopN) | Join | Subquery in `from` | Non-Correlated Subquery | Correlated Subquery | CTE / View | Dependencies
|---|---|---|---|---|---|---|---|---|
| Q1 | ✔️ |  |  |  |  |  |  |`tpcc_orderline`|
| Q2 | ✔️ | ✔️ | ✔️ | ✔️ (table) |  |  |  |`tpcc_item, supplier, tpcc_stock, nation, region`|
| Q3 | ✔️ | ✔️ | ✔️ |  |  |  |  |`tpcc_customer, tpcc_neworder, tpcc_order, tpcc_orderline`|
| Q4 | ✔️ | ✔️ |  |  |  | ✔️ (exists) |  |`tpcc_order, tpcc_orderline`|
| Q5 | ✔️ | ✔️ | ✔️ |  |  |  |  |`tpcc_customer, tpcc_order, tpcc_orderline, tpcc_stock, supplier, nation, region`|
| Q6 | ✔️ (simple) |  |  |  |  |  |  |`tpcc_orderline`|
| Q7 | ✔️ | ✔️ | ✔️ |  |  |  |  |`supplier, tpcc_stock, tpcc_orderline, tpcc_order, tpcc_customer, nation`|
| Q8 | ✔️ | ✔️ | ✔️ |  |  |  |  |`tpcc_item, supplier, tpcc_stock, tpcc_orderline, tpcc_order, tpcc_customer, nation`|
| Q9 | ✔️ | ✔️ | ✔️ |  |  |  |  |`tpcc_item, tpcc_stock, supplier, tpcc_orderline, tpcc_order, nation`|
| Q10 | ✔️ | ✔️ | ✔️ |  |  |  |  |`tpcc_customer, tpcc_order, tpcc_orderline, nation`|
| Q11 | ✔️ | ✔️ | ✔️ |  | ✔️ (greater than '>') |  |  |`tpcc_stock, supplier, nation`|
| Q12 | ✔️ | ✔️ | ✔️ |  |  |  |  |`tpcc_order, tpcc_orderline`|
| Q13 | ✔️ | ✔️ | ✔️ (outer) | ✔️ (table |  |  |  |`tpcc_customer, tpcc_order`|
| Q14 | ✔️ (simple) |  | ✔️ |  |  |  |  |`tpcc_orderline, tpcc_item`|
| Q15 |  | ✔️ | ✔️ |  |  |  | ✔️ |`tpcc_orderline, tpcc_stock, supplier`|
| Q16 | ✔️ | ✔️ | ✔️ |  | ✔️ (not in) |  |  |`tpcc_stock, tpcc_item, supplier`|
| Q17 | ✔️ |  | ✔️ | ✔️ (table |  |  |  |`tpcc_item, tpcc_orderline`|
| Q18 | ✔️ | ✔️ | ✔️ |  |  |  |  |`tpcc_customer, tpcc_order, tpcc_orderline`|
| Q19 | ✔️ (simple) |  | ✔️ |  |  |  |  |`tpcc_orderline, tpcc_item`|
| Q20 | ✔️ | ✔️ | ✔️ |  | ✔️ (in) |  |  |`supplier, nation,  tpcc_stock, tpcc_orderline, tpcc_item`|
| Q21 | ✔️ | ✔️ | ✔️ |  |  | ✔️ (not exists) |  |`supplier, tpcc_orderline, tpcc_order, tpcc_stock, nation`|
| Q22 | ✔️ | ✔️ | ✔️ |  | ✔️ (greater than '>' | ✔️ (not exists) |  |`tpcc_customer, tpcc_order`|

## E2E-test

- [x] [CH-benCHmark Q1](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] [CH-benCHmark Q2](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] [CH-benCHmark Q3](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] [CH-benCHmark Q4](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] CH-benCHmark Q5
- [x] [CH-benCHmark Q6](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] CH-benCHmark Q7
- [x] CH-benCHmark Q8
- [x] [CH-benCHmark Q9](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] [CH-benCHmark Q10](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] [CH-benCHmark Q11](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] [CH-benCHmark Q12](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] [CH-benCHmark Q13](https://github.com/risingwavelabs/risingwave/pull/5155)
- [x] [CH-benCHmark Q14](https://github.com/risingwavelabs/risingwave/pull/5915)
- [x] [CH-benCHmark Q15](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] [CH-benCHmark Q16](https://github.com/risingwavelabs/risingwave/pull/5155)
- [x] [CH-benCHmark Q17](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] [CH-benCHmark Q18](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] CH-benCHmark Q19
- [x] [CH-benCHmark Q20](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] [CH-benCHmark Q21](https://github.com/risingwavelabs/risingwave/pull/5600)
- [x] [CH-benCHmark Q22](https://github.com/risingwavelabs/risingwave/pull/5600)

**Comment by nanderstabel** [comment]
First things first: in this PR #5155 I have added all the CH-benCHmark queries and their missing TPC-C dataset.

As mentioned in the PR: many tests do successfully run, but do not produce any output due to their dataset tables being capped at 1500 (randomly selected) rows. In order to make the queries produce actual output either the max amount of rows per tables need to be increased or a curated list of rows need to be selected.

@fuyufjh @neverchanje @sumittal I assume for the already existing benchmarks there was also the need to select some specific rows in the dataset? Is there a smart way to go about this?

**Comment by liurenjie1024** [comment]
Yes, you may need to change some data to meet the join/filer condition and I did that for tpch.

**Comment by fuyufjh** [comment]
@nanderstabel @lmatz Some queries are not enabled yet. Do we have any future plans for these?

```
q05.slt.part --> no output
q07.slt.part --> no output
q08.slt.part --> no output
q19.slt.part --> precision error
```

**Comment by lmatz** [comment]
> @nanderstabel @lmatz Some queries are not enabled yet. Do we have any future plans for these?
> 
> ```
> q05.slt.part --> no output
> q07.slt.part --> no output
> q08.slt.part --> no output
> q19.slt.part --> precision error
> ```

The precision error is probably due to #5804, waiting for a new release, or use the workaround in #5804.

I think @nanderstabel is taking a leave right now and will come back and continue working on enabling these queries.

**Comment by lmatz** [comment]
Now we supported all the queries by #6870
