### ISSUE TITLE
Tracking: introduce memory management

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#5290]
This issue tracks the development of the memory management component of the compute node operator cache.

The development will follow the design in https://singularity-data.quip.com/CldAAcFmzZSO/Yet-another-simple-idea-for-memory-management

tasks:
- [x] [LRU cache that supports eviction by timestamp](https://github.com/risingwavelabs/lru-rs/pull/1)
- [x] LRU manager on compute node.
- [x] Use new LRU cache for operators.

Related issue:
#4987

**Comment by fuyufjh** [comment]
Can we close this?
