### ISSUE TITLE
Tracking: streaming hash join optimization

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#5605]
This issue tracks the optimization of streaming hash join.

- [ ] make stream chunk builder output indices aware. Previously done in #3588
- [ ] avoid degree table cases in append-only hash join.
- [ ] concurrent fetch hash join state #2428 
- [ ] (potential) vectorization for non-eq join condition.

**Comment by jon-chuang** [comment]
For concurrent hash join fetch, I am thinking of implementing a `prefetch` API over the `StateTable`/`StateStore` interface instead of previously tried approach, since we only care about the latency over the network. So, we will allow prefetch to dump the data into block cache, and let the operator consume the stream chunks async while the data is in block cache, else await while the prefetch request is in-flight.

**Comment by jon-chuang** [comment]
Actually, I realized that even a prefetch API doesn't totally solve application-side deduplication issue due to cache coherency i.e. a key that is not prefetched due to being prefetched may be evicted prior to the key being processed.

Hence, I think a "best effort" approach is suited here. We will try our best to prefetch all the keys not in cache. But, if some relevant keys in cache get evicted, we can still issue a fetch later on. We consider this pipeline stall ok as 1. we can still concurrently fetch other keys 2. probably the keys that are evicted are low-hit rate anyway, so hitting them is not likely.
