### ISSUE TITLE
Tracking: Introduce CompactRow for executors' cache

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#5800]
## Background
Currently executors use different in memory types to store rows in their cache:
- aggregation: 
Extreme: `Cache<CacheKey, Datum>`
array agg: `Cache<OrderedRow, Datum>`
 string agg: `Cache<OrderedRow, StringAggData>`

- hash_join: `Cache<Vec<u8>, EncodedJoinRow>` where
```rust
pub struct EncodedJoinRow {
    pub row: Vec<u8>,
    degree: DegreeType,
}
```

- top_n: `BTreeMap<OrderedRow, Row>`
- dynamic filter: `BTreeMap<ScalarImpl, HashSet<Row>>`

## Proposal
As we know that `Row(pub Vec<Datum>)` leads to excessive memory usage, and `hash_join` has made some optimizations by serializing `Row` into `Vec<u8>`, other executors, such as top_n may also benefit from this way.

In addition, current implement on hash_join will cause one extra deserialization and serialization: state table need to deserialize the  storage row type(Vec<u8>) into `Row` and hash join need to serialize the `Row` into `EncodedJoinRow`. So why not skip this  deserialization and serialization, just introduce a new memory friendly `CompactRow`. 

In the beginning， `CompactRow` can be as simple as possible, may just a struct to store `Vec<u8>`, and we can impl `CompactRow` some serialize/deserialize functions in the future to **make in-memory row and storage row not strongly consistent**. 
```rust
pub struct CompactRow {
    pub row: Vec<u8>,
}

// if needed
impl CompactRow{
  fn deserialize()
  fn serialize()
  fn xxx()
}
```

Thus `StateTable` read interfaces can return `CompactRow` and some executors can use `CompactRow`  for their cache.

## Discussion
@TennyZhuang: this may increase the complexity of pk dedup, if we want to support pk dedup, may change `CompactRow` to an enum or trait.

## Roadmap
- [x] introduce `CompactedRow`
- [x] refactor top_n (hash join) to store `CompactedRow` in cache.
- [x] refactor array_agg and extreme to store `CompactedRow` in cache.
- [x] refactor dynamic to store `CompactedRow` in cache.

**Comment by BugenZhao** [comment]
Some questions:
1. What encoding is used in the inner `Vec<u8>` (for now)? Note that the key in cache should be comparable.
2. Memory efficient row cannot be indexed randomly, so executors need to hold the schema to deserialize and use it. As we move the deserialization out of the state table, what's the main responsibility of the state table layer?
3. What about the write interface?

**Comment by BugenZhao** [comment]
> In addition, current implement on hash_join will cause one extra deserialization and serialization: state table need to deserialize the storage row type(Vec) into `Row` and hash join need to serialize the `Row` into `EncodedJoinRow`. So why not skip this deserialization and serialization, just introduce a new memory friendly `CompactRow`.

As pk-dedup is going to be defered, so why not just use the raw KV interface? 🤣 Note that the encoding of key-value is naturally what we want.

**Comment by st1page** [comment]
> What encoding is used in the inner Vec<u8> (for now)? Note that the key in cache should be comparable.

the key in the cache will use memcomparable and IIUC this issue just focus on the value in cache. we should have another issue for the key encoding

> Memory efficient row cannot be indexed randomly, so executors need to hold the schema to deserialize and use it. As we move the deserialization out of the state table, what's the main responsibility of the state table layer?

the executor should hold the schema of the cached row because the cache 
I think the CompactRow should not be as a memory Row format and need not to be same with the storage, and the `deserialize()` function should be used for 

> What about the write interface

maybe we can use RowRef for the write interface

**Comment by TennyZhuang** [comment]
If we can implement the same purpose in the state table interface, why do we expose the raw KV interface? It breaks the abstraction.
For the pk-dedup in the Future, we can introduce `enum Row {Compacted(CompactRow), Concat(ConcatRow)` for that purpose, but if we use the raw kv interface, we can never do the pk-dedup.

**Comment by wcy-fdu** [comment]
For 1, another issue can use `OrderedRowSerde` to serialize it into cache, just like `Extreme`.

**Comment by BugenZhao** [comment]
> I think the CompactRow should not be as a memory Row format and need not to be same with the storage,

Then what will it be?

> maybe we can use RowRef for the write interface

So there's still a pair of ser/de if we want to write the just-read records. It just defers the cost from read to write.

**Comment by st1page** [comment]
![image](https://user-images.githubusercontent.com/40830455/195259363-fa4de50f-6409-4f71-ac82-9b9bd2710989.png)'
we need not implement serialize method on `CompactRow`

**Comment by wcy-fdu** [comment]
Currently as we still use `Vec<Datum>`, so `StateTable` serialize do not need schema, but when we refactor `Vec<Datum>` to something else, `StateTable` still need to aware schema, so I suggest keep `DataType` in StateTable.

**Comment by st1page** [comment]
> > I think the CompactRow should not be as a memory Row format and need not to be same with the storage,
> 
> Then what will it be?
> 
> >

just to maintain the potential to change the memory row format

**Comment by BugenZhao** [comment]
Anyway, please just turn a deaf ear to my advice since it's you all that are much more familiar with the streaming executors. 🤣

**Comment by wcy-fdu** [comment]
I think we can first change other executors' cache to store `CompactedRow` like hash join.
What `StateTable`'s write and read interfaces will be depends on whether cache Row and Storage Row will be consistent, if they are not consistent in the future, these discussions about ser/deser will be meaningless.

**Comment by wcy-fdu** [comment]
After some refactor on top_n and dynamic_filter, cache value of streaming executors (except aggregation: @richardchien  is doing some refactor on aggregation and we decide to refactor agg cache after his refactor is done) is using `CompactedRow`.

Next step I will refactor the cache key of executors to reduce memory overhead. After that let's rethink the read/write interfaces of `StateTable`😊.
