### ISSUE TITLE
Tracking: Towards better streaming aggregation!

### ISSUE THREAD

**Issue by richardchien** [risingwavelabs/risingwave#5806]
- [x] Introduce `result_table` to merge value state tables
  - #5598
  - #5411
- [x] Enable state table sanity check
  - #5708
  - #5709
- [x] Refactor `AggState` (new name: `AggGroup`)
  - #5795
- [x] Refactor `ManagedStateImpl` (new name: `AggState`)
  - #5796
  - #5848
- ~~Frontend rewriting to simplify backend implementation~~ (Finally decided to implement these in backend)
  - Implicit filter on NULL value for `min`/`max`
  - Implicit order-by on aggregation argument for `min`/`max`
- [x] Refactor `ManagedTableState`
  - #5889
  - #5908
  - #6006
  - #6035
- [x] Support different state type other than `ValueState` and `MaterializedInputState`
  - #5976
