### ISSUE TITLE
Tracking: Bummock as an indexing storage for various data models.

### ISSUE THREAD

**Issue by wyhyhyhyh** [risingwavelabs/risingwave#585]
1. Relational
Bummock will serve as a unified indexing interface for table storage built on top of Hummock.
See https://singularity-data.quip.com/lYozAfUcsvXV/Bummock-as-an-indexing-storage for design doc.

A roadmap includes:

- [ ]  Implement a unified interface for collection. https://github.com/singularity-data/risingwave-dev/pull/573
- [ ]  Implement secondary index for table.
- [ ]  Implement index scan batch executor.
- [ ]  Implement index maintenance.

2. Nested (protobuf, json)
We support nested data model an indexing interface. 
https://singularity-data.quip.com/63ipA5OTEqnD/Considerations-on-Schemaless-Bummock

A brief roadmap:
- [x] #591
- [x] #575 
- [ ] Design and implement the storage format for nested data.
- [ ] Implement write path for nested data.
- [ ] Implement path scanner for nested data. 

Long term: 
- [ ] Implement indexing for nested data.
