### ISSUE TITLE
Tracking: high availability for Meta service

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#5943]
To support Meta's high availability, we need to do some refactor in Meta service:

Leader election
- [x] #6752 
- [x] https://github.com/risingwavelabs/risingwave/issues/6936 
- [x] #6753
- [x] #6786 
- [x] #6771 
- [x] #6534

Service discovery
- [x] #6754
- [x] #6755
- [x] #6787 (part of 6755)
- [x] #6845 (To fix)

State persistence (DONE natually)

Test
- [x] #6884
- [x] #7533 

Others
- [x] #7576
- [ ] [Enable meta HA setup in operator  ](https://github.com/risingwavelabs/risingwave-cloud/issues/1605)
- [ ] [Crate Meta K8s Service in cloud setup ](https://github.com/risingwavelabs/risingwave-cloud/issues/1604)

**Comment by CAJan93** [comment]
Design Docs: https://singularity-data.quip.com/8gMGA3kSZVMR/HA-for-Meta

**Comment by CAJan93** [comment]
Looking forward to work on this task. However I am still working on a different kernel task and will be at KubeCon next week. I will start with this the earliest at the beginning of November.

**Comment by skyzh** [comment]
added a new task "support connecting to multiple meta-node on compute-node"

**Comment by CAJan93** [comment]
Failover works, but Hummock crashes: https://github.com/risingwavelabs/risingwave/issues/6534

**Comment by CAJan93** [comment]
> support connecting to multiple meta-node on compute-node 

@yezizp2012 I do not understand this part: My understanding is that the meta HA setup is a single-leader-system (see [design docs](https://singularity-data.quip.com/8gMGA3kSZVMR/HA-for-Meta)). Therefore we only ever connect to one instance. 
Is my understanding correct @fuyufjh ?

**Comment by yezizp2012** [comment]
> > support connecting to multiple meta-node on compute-node
> 
> @yezizp2012 I do not understand this part: My understanding is that the meta HA setup is a single-leader-system (see [design docs](https://singularity-data.quip.com/8gMGA3kSZVMR/HA-for-Meta)). Therefore we only ever connect to one instance. Is my understanding correct @fuyufjh ?

IIUC, This should refers to the refactoring of the meta client? @skyzh right?

**Comment by skyzh** [comment]
> IIUC, this should refers to the refactoring of the meta client: meta client should be able to connect and retrieve leader information from multi-meta nodes, which requires a get_leader_addr interface in meta.

Yes. After that we can modify risedev to provide multiple meta addresses to compute nodes and frontend nodes. Currently it only picks the first one (see risedev warning)

**Comment by CAJan93** [comment]
Thank you very much for the clarifying. I would suggest that the change in the `client` and the change in the meta enabling a follower service which supports `get_leader_addr` will be done in separate PRs.

**Comment by CAJan93** [comment]
First version of the failover handling is done. Please have a look: https://github.com/risingwavelabs/risingwave/pull/6466 

There are a few things in the PR missing: 
- e2e tests. I do not know how best to approach that. Please let me know if you have suggestions 
- Currently we do busy-wait to do elections. ETCD also provides an update API afaik. I guess that this will require quite a reqwrite, which is why I would like to do this as future work. 
- Meta crashes on failover because of https://github.com/risingwavelabs/risingwave/issues/6534. Will be addressed in future PR

**Comment by CAJan93** [comment]
> added a new task "support connecting to multiple meta-node on compute-node"

Is this still up to date? I do not see the subtask @skyzh

**Comment by yezizp2012** [comment]
> > added a new task "support connecting to multiple meta-node on compute-node"
> 
> Is this still up to date? I do not see the subtask @skyzh

That should be a part of #6755 .

**Comment by CAJan93** [comment]
Tests are still running, but my guess is that https://github.com/risingwavelabs/risingwave/pull/6771 is ready for review. This is a minor tasks overall, but merging it would still simplify further steps. Let me know if you have any objections or suggestions to the PR.

**Comment by CAJan93** [comment]
I currently have 2 PRs that are ready for review. 
 
- https://github.com/risingwavelabs/risingwave/pull/6771: Introduces graceful shutdown of services. This is only indirectly related to the HA setup. It will simplify further development. 

- https://github.com/risingwavelabs/risingwave/pull/6792: Introduces the election mechanism, but does not introduce any failover (see [features and limitations here](https://github.com/risingwavelabs/risingwave/issues/6752#issuecomment-1340728154)). My expectation is that this does not affect our current setup, because we only ever deploy one meta node, which hopefully  always becomes leader. PR reduces code coverage, because I delete a unittest which is no longer needed in a HA setup (also see [#3398](https://github.com/risingwavelabs/risingwave/issues/3398) )

CC @arkbriar

**Comment by CAJan93** [comment]
https://github.com/risingwavelabs/risingwave/pull/6937 is ready for review. Please view the [issue](https://github.com/risingwavelabs/risingwave/issues/6936) for features and limitations.

**Comment by CAJan93** [comment]
[The fencing PR ](https://github.com/risingwavelabs/risingwave/pull/7022)is ready for review. The CI pipeline is green. Also see https://github.com/risingwavelabs/risingwave/issues/6786. 

Maybe we can get this merged before New Years :)

**Comment by CAJan93** [comment]
Fencing is merged. Thank you very much for your guidance and approval @yezizp2012

**Comment by CAJan93** [comment]
https://github.com/risingwavelabs/risingwave/pull/7248/ is ready for review. 
- Client is able to failover to new meta node
- Failover may require a few seconds. Meta nodes initially report stale leader information until election is finished
