### ISSUE TITLE
Tracking: new DML design

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#5949]
- RFCs: 
   - https://github.com/risingwavelabs/rfcs/pull/4
   - https://github.com/risingwavelabs/rfcs/pull/17  
- StreamMaterialize Executor https://github.com/risingwavelabs/risingwave/pull/6320
  - [x] Add a `check_pk: bool` flag and ignore the following operation if pk conflict
  - [x] Add a cache
- SourceExecutor
  - [x] Reimplement `SourceExecutor` to contain only streaming connector. 
  - [x] Introduce `DmlExecutor` to merge data from both `SourceExecutor` and batch.
  - [x] Introduce `DmlManager` (previously named `TableSourceManager`)
     - Use `table_id` instead of `source_id`
     - Store `tx` in this manager so that batch executors have access to these `tx`s
  - [x] Introduce `RowIdGenerateExecutor`
- change the create table on frontend
  - [x] use the new design for the old syntax https://github.com/risingwavelabs/risingwave/pull/6836
  - [x] support `create table with (connector = '...')`
  - [ ] remove `create materialized source` grammer
