### ISSUE TITLE
Tracking: enable DuckDB tests

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#5970]
### `pg_catalog`:
- [ ] pg_attribute.test
- [ ] pg_constraint.test
- [ ] pg_depend.test
- [ ] pg_enum.test
- [ ] pg_index.test
- [ ] pg_namespace.test
- [ ] pg_sequence.test
- [ ] pg_sequences.test
- [ ] pg_tablespace.test
- [ ] pg_views.test
- [ ] sqlalchemy.test
- [ ] system_functions.test

### `aggregate`:
`aggregate/aggregates`:
- [ ] distinct
- [ ] string_agg_union.test
- [ ] test_aggr_string.test
- [ ] test_aggregate_types.test
- [ ] test_aggregate_types_scalar.test
- [ ] test_any_value.test
- [ ] test_any_value_noninlined.test
- [ ] test_approx_quantile.test
- [ ] test_approximate_distinct_count.test
- [ ] test_arg_min_max.test
- [ ] test_arg_min_max_strings.test
- [ ] test_avg.test
- [ ] test_bigint_avg.test
- [ ] test_bit_and.test
- [ ] test_bit_or.test
- [ ] test_bit_xor.test
- [ ] test_bool.test
- [ ] test_corr.test
- [ ] test_count.test
- [ ] test_count_star.test
- [ ] test_covar.test
- [ ] test_empty_aggregate.test
- [ ] test_entropy.test
- [ ] test_first_noninlined.test
- [ ] test_group_by_many_groups.test_slow
- [ ] test_group_on_expression.test
- [ ] test_histogram.test
- [ ] test_histogram_3529.test
- [ ] test_incorrect_aggregate.test
- [ ] test_kahan_avg.test
- [ ] test_kahan_sum.test
- [ ] test_kurtosis.test
- [ ] test_last.test
- [ ] test_last_noninlined.test
- [ ] test_list_aggregate.test_coverage
- [ ] test_list_aggregate_function.test
- [ ] test_mad.test
- [ ] test_median.test
- [ ] test_minmax.test
- [ ] test_mode.test
- [ ] test_null_aggregates.test
- [ ] test_ordered_aggregates.test
- [ ] test_perfect_ht.test
- [ ] test_product.test
- [ ] test_quantile_cont.test
- [ ] test_quantile_cont_list.test
- [ ] test_quantile_disc.test
- [ ] test_quantile_disc_list.test
- [ ] test_regression.test
- [ ] test_scalar_aggr.test
- [ ] test_sem.test
- [ ] test_simple_filter.test
- [ ] test_skewness.test
- [ ] test_state_export.test
- [ ] test_stddev.test
- [ ] test_string_agg.test
- [ ] test_string_agg_big.test
- [ ] test_string_agg_many_groups.test_slow
- [ ] test_sum.test

`aggregate/group`:
- [ ] group_by_all.test
- [ ] group_by_limits.test
- [ ] test_group_by.test
- [ ] test_group_by_alias.test
- [ ] test_group_by_large_string.test
- [ ] test_group_by_multi_column.test
- [ ] test_group_by_nested.test
- [ ] test_group_by_parallel.test_slow
- [ ] test_group_null.test
- [ ] tpch_group_by_all.test_slow

`aggregate/having`:
- [ ] test_having.test
- [ ] test_scalar_having.test

`aggregate/distinct`:
- [ ] issue2656.test
- [ ] test_distinct.test
- [ ] test_distinct_on.test
- [ ] test_distinct_order_by.test

### `join`:

**Comment by xxchan** [comment]
One note: duckdb's default ordering is `ASC NULLS FIRST` (We havn't implemented it yet https://github.com/risingwavelabs/risingwave/issues/4743), while pg's is `ASC NULLS LAST`. 

ref: https://duckdb.org/docs/sql/query_syntax/orderby
