### ISSUE TITLE
Tracking: bump compiler toolchain to 1.65

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#5977]
PR: https://github.com/risingwavelabs/risingwave/pull/5119

Blocked by:

- [x] https://github.com/rust-lang/rust/issues/101465
- [x] https://github.com/rust-lang/rust/issues/101750
- [x] https://github.com/rust-lang/rust/issues/103423
