### ISSUE TITLE
Tracking: support delete-range to clean stale state for some grouped-key

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#5978]
### Background

We need to make hummock could delete data for some group key. For example, if users create a MV by time window, those data in a long time ago would never be queried and we need to delete them to recycle storage space. 

### Tasks

- [x] support recycle deleted data in compaction. We need to filter keys located in delete-ranges. https://github.com/risingwavelabs/risingwave/pull/5998
- [x] hummock supply an interface to delete-range of data for some table-id. https://github.com/risingwavelabs/risingwave/pull/6198
- [x] support filter deleted data  in query (iter and get). https://github.com/risingwavelabs/risingwave/pull/6279

**Comment by hzxa21** [comment]
@Little-Wallace Is this done?

**Comment by Little-Wallace** [comment]
This task has been finished

**Comment by Little-Wallace** [comment]
see random test in https://github.com/risingwavelabs/risingwave/pull/6688. We would run it daily once.
