### ISSUE TITLE
test: enable `order` duckdb test cases

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#5984]
Source: https://github.com/duckdb/duckdb/tree/master/test/sql/order

- [ ] hugeint_order_by_extremes.test
- [x] limit_full_outer_join.test
- [ ] limit_parameter.test
- [ ] limit_union.test
- [x] negative_offset.test
- [ ] order_by_all.test
- [ ] order_parallel_complex.test_coverage
- [ ] order_parallel_fixed.test_coverage
- [ ] order_parallel_many_ties.test_slow
- [ ] order_parallel_varsize.test_coverage
- [ ] persistent_list_of_varchar_order.test_coverage
- [x] test_limit.test
- [ ] test_limit_cte.test
- [ ] test_limit_parameter.test
- [ ] test_limit_percent.test
- [ ] test_nulls_first.test
- [x] test_order_by.test
- [x] test_order_by_exceptions.test
- [ ] test_order_large.test
- [ ] test_order_nested.test_coverage
- [ ] test_order_pragma.test
- [ ] test_order_range_mapping.test
- [x] test_order_same_value.test_slow
- [x] test_order_variable_size_payload.test_coverage
- [ ] top_n_nulls.test
