### ISSUE TITLE
test: enable `limit` duckdb test cases

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#5992]
Source: https://github.com/duckdb/duckdb/tree/master/test/sql/limit

- [ ] parallel_limit_transaction_local.test_slow
- [ ] test_limit0.test
- [x] test_parallel_limit.test_slow
- [ ] test_parallel_limit_nested.test_slow
- [ ] test_parallel_limit_nested_null.test_slow
- [x] test_parallel_limit_nulls.test_slow
- [x] test_parallel_limit_strings.test_slow
- [x] test_preserve_insertion_order.test

**Comment by chenzl25** [comment]
I found duckdb all limit test cases rely on statement like `CREATE TABLE integers2 AS SELECT * FROM range(1000000) tbl(i)`. We need to postpone those test cases util we support this kind of statement.

**Comment by lmatz** [comment]
> I found duckdb all limit test cases rely on statement like `CREATE TABLE integers2 AS SELECT * FROM range(1000000) tbl(i)`. We need to postpone those test cases util we support this kind of statement.

I see, expect it can be bypassed by `create table XXX` and `insert into XXX select ...`. 
`insert into XXX select` has a bug though, let me create an issue first.

**Comment by chenzl25** [comment]
Yes, we can use `generate_series` instead of `range` and separate the create table statement and select statement.
