### ISSUE TITLE
Tracking: enable CockroachDB logictests

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#6003]
Check https://github.com/cockroachdb/cockroach/tree/master/pkg/sql/logictest/testdata/logic_test for test cases.

- [ ] active_version
- [ ] aggregate
- [ ] alias_types
- [ ] alter_column_type
- [ ] alter_database_convert_to_schema
- [ ] alter_database_owner
- [ ] alter_default_privileges_for_all_roles
- [ ] alter_default_privileges_for_schema
- [ ] alter_default_privileges_for_sequence
- [ ] alter_default_privileges_for_table
- [ ] alter_default_privileges_for_type
- [ ] alter_default_privileges_in_schema
- [ ] alter_default_privileges_with_grant_option
- [ ] alter_primary_key
- [ ] alter_role
- [ ] alter_role_set
- [ ] alter_schema_owner
- [ ] alter_sequence
- [ ] alter_sequence_owner
- [ ] alter_table
- [ ] alter_table_owner
- [ ] alter_type
- [ ] alter_type_owner
- [ ] alter_view_owner
- [ ] and_or
- [ ] apply_join
- [ ] array
- [ ] as_of
- [ ] auto_span_config_reconciliation_job
- [ ] bit
- [ ] builtin_function
- [ ] builtin_function_notenant
- [ ] bytes
- [ ] cascade
- [ ] case_sensitive_names
- [ ] cast
- [ ] ccl
- [ ] check_constraints
- [ ] cluster_locks
- [ ] cluster_settings
- [ ] cluster_version
- [ ] collatedstring
- [ ] collatedstring_constraint
- [ ] collatedstring_index1
- [ ] collatedstring_index2
- [ ] collatedstring_normalization
- [ ] collatedstring_nullinindex
- [ ] collatedstring_uniqueindex1
- [ ] collatedstring_uniqueindex2
- [ ] column_families
- [ ] computed
- [ ] conditional
- [ ] connect_privilege
- [ ] contention_event
- [ ] crdb_internal
- [ ] crdb_internal_default_privileges
- [ ] create_as
- [ ] create_as_non_metamorphic
- [ ] create_index
- [ ] create_statements
- [ ] create_table
- [ ] cross_join
- [ ] cursor
- [ ] custom_escape_character
- [ ] dangerous_statements
- [ ] database
- [ ] datetime
- [ ] decimal
- [ ] default
- [ ] delete
- [ ] dependencies
- [ ] discard
- [ ] disjunction_in_join
- [ ] dist_vectorize
- [ ] distinct
- [ ] distinct_on
- [ ] distsql_agg
- [ ] distsql_automatic_stats
- [ ] distsql_builtin
- [ ] distsql_crdb_internal
- [ ] distsql_datetime
- [ ] distsql_distinct_on
- [ ] distsql_enum
- [ ] distsql_event_log
- [ ] distsql_expr
- [ ] distsql_join
- [ ] distsql_numtables
- [ ] distsql_srfs
- [ ] distsql_stats
- [ ] distsql_subquery
- [ ] distsql_tenant
- [ ] distsql_tenant_locality
- [ ] distsql_union
- [ ] drop_database
- [ ] drop_index
- [ ] drop_owned_by
- [ ] drop_role_with_default_privileges
- [ ] drop_role_with_default_privileges_in_schema
- [ ] drop_schema
- [ ] drop_sequence
- [ ] drop_table
- [ ] drop_temp
- [ ] drop_type
- [ ] drop_user
- [ ] drop_view
- [ ] edge
- [ ] enums
- [ ] errors
- [ ] event_log
- [ ] exclude_data_from_backup
- [ ] experimental_distsql_planning
- [ ] experimental_distsql_planning_5node
- [ ] explain
- [ ] explain_analyze
- [ ] expression_index
- [ ] external_connection_privileges
- [ ] family
- [ ] feature_counts
- [ ] fk
- [ ] float
- [ ] format
- [ ] function_lookup
- [ ] fuzzystrmatch
- [ ] generator_probe_ranges
- [ ] geospatial
- [ ] geospatial_bbox
- [ ] geospatial_index
- [ ] geospatial_meta
- [ ] geospatial_zm
- [ ] grant_database
- [ ] grant_in_txn
- [ ] grant_on_all_sequences_in_schema
- [ ] grant_on_all_tables_in_schema
- [ ] grant_revoke_with_grant_option
- [ ] grant_role
- [ ] grant_schema
- [ ] grant_sequence
- [ ] grant_table
- [ ] grant_type
- [ ] hash_join
- [ ] hash_join_dist
- [ ] hash_sharded_index
- [ ] hidden_columns
- [ ] impure
- [ ] index_join
- [ ] inet
- [ ] inflight_trace_spans
- [ ] information_schema
- [ ] inner-join
- [ ] insert
- [ ] int_size
- [ ] internal_executor
- [ ] interval
- [ ] inv_stats
- [ ] inverted_filter_geospatial
- [ ] inverted_filter_geospatial_dist
- [ ] inverted_filter_json_array
- [ ] inverted_index
- [ ] inverted_index_geospatial
- [ ] inverted_index_multi_column
- [ ] inverted_join_geospatial
- [ ] inverted_join_geospatial_bbox
- [ ] inverted_join_geospatial_dist
- [ ] inverted_join_json_array
- [ ] inverted_join_multi_column
- [ ] jobs
- [ ] join
- [ ] json
- [ ] json_builtins
- [ ] kv_builtin_functions
- [ ] kv_builtin_functions_local
- [ ] kv_builtin_functions_tenant
- [ ] limit
- [ ] locality
- [ ] lock_timeout
- [ ] lookup_join
- [ ] lookup_join_local
- [ ] lookup_join_spans
- [ ] loop.sh
- [ ] manual_retry
- [ ] materialized_view
- [ ] merge_join
- [ ] merge_join_dist
- [ ] multi_region
- [ ] multi_statement
- [ ] multiregion_invalid_locality
- [ ] name_escapes
- [ ] namespace
- [ ] new_schema_changer
- [ ] no_primary_key
- [ ] notice
- [ ] numeric_references
- [ ] on_update
- [ ] operator
- [ ] optimizer_timeout
- [ ] order_by
- [ ] ordinal_references
- [ ] ordinality
- [ ] orms
- [ ] overflow
- [ ] overlaps
- [ ] owner
- [ ] parallel_stmts_compat
- [ ] partial_index
- [ ] partial_txn_commit
- [ ] partitioning
- [ ] pg_builtins
- [ ] pg_catalog
- [ ] pg_catalog_pg_default_acl
- [ ] pg_catalog_pg_default_acl_with_grant_option
- [ ] pg_extension
- [ ] pgcrypto_builtins
- [ ] pgoidtype
- [ ] poison_after_push
- [ ] postgres_jsonb
- [ ] postgresjoin
- [ ] prepare
- [ ] privilege_builtins
- [ ] privileges_comments
- [ ] privileges_table
- [ ] propagate_input_ordering
- [ ] ranges
- [ ] reassign_owned_by
- [ ] record
- [ ] redact_descriptor
- [ ] rename_atomic
- [ ] rename_column
- [ ] rename_constraint
- [ ] rename_database
- [ ] rename_index
- [ ] rename_sequence
- [ ] rename_table
- [ ] rename_view
- [ ] reset
- [ ] returning
- [ ] role
- [ ] row_level_ttl
- [ ] rows_from
- [ ] run_control
- [ ] save_table
- [ ] scale
- [ ] scatter
- [ ] schema
- [ ] schema_change_feature_flags
- [ ] schema_change_in_txn
- [ ] schema_change_retry
- [ ] schema_repair
- [ ] scrub
- [ ] secondary_index_column_families
- [ ] select
- [ ] select_for_update
- [ ] select_index
- [ ] select_index_flags
- [ ] select_search_path
- [ ] select_table_alias
- [ ] sequences
- [ ] sequences_distsql
- [ ] sequences_regclass
- [ ] serial
- [ ] serializable_eager_restart
- [ ] set
- [ ] set_local
- [ ] set_role
- [ ] set_schema
- [ ] set_time_zone
- [ ] shift
- [ ] show_completions
- [ ] show_create
- [ ] show_create_all_schemas
- [ ] show_create_all_tables
- [ ] show_create_all_tables_builtin
- [ ] show_create_all_types
- [ ] show_default_privileges
- [ ] show_fingerprints
- [ ] show_grants_on_virtual_table
- [ ] show_grants_synthetic
- [ ] show_indexes
- [ ] show_source
- [ ] show_tables
- [ ] show_transfer_state
- [ ] skip_on_retry
- [ ] span_builtins
- [ ] split_at
- [ ] sql_keys
- [ ] sqllite
- [ ] sqlsmith
- [ ] srfs
- [ ] statement_source
- [ ] statement_statistics
- [ ] stats
- [ ] storing
- [ ] strict_ddl_atomicity
- [ ] suboperators
- [ ] subquery
- [ ] subquery_correlated
- [ ] synthetic_privileges
- [ ] system
- [ ] system_columns
- [ ] system_namespace
- [ ] table
- [ ] target_names
- [ ] temp_table
- [ ] temp_table_txn
- [ ] tenant
- [ ] tenant_slow_repro
- [ ] time
- [ ] timestamp
- [ ] timetz
- [ ] trigram_builtins
- [ ] trigram_indexes
- [ ] truncate
- [ ] tuple
- [ ] txn
- [ ] txn_as_of
- [ ] txn_retry
- [ ] txn_stats
- [ ] type_privileges
- [ ] typing
- [ ] udf
- [ ] union
- [ ] unique
- [ ] update
- [ ] update_from
- [ ] upsert
- [ ] user
- [ ] uuid
- [ ] values
- [ ] vectorize
- [ ] vectorize_agg
- [ ] vectorize_overloads
- [ ] vectorize_shutdown
- [ ] vectorize_types
- [ ] vectorize_unsupported
- [ ] vectorize_window
- [ ] views
- [ ] virtual_columns
- [ ] virtual_table_privileges
- [ ] void
- [ ] where
- [ ] window
- [ ] with
- [ ] zero
- [ ] zigzag_join
- [ ] zone_config
- [ ] zone_config_system_tenant
