### ISSUE TITLE
Tracking: failover in Meta Service

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#61]
Failover tracking issues as follow:
- [x] [Introduce NotifyService in frontend](https://github.com/singularity-data/risingwave-dev/issues/361)
- [x] support frontend reboot state recovery, mainly involved in catalog/cluster info etc.
- [x] support computer node reboot state recovery.
- [x] support migration state from one compute node to another one.
- [x] release hummock resource when heartbeat fail between computer node and meta.
- [x] dirty state clean up in case of failover.
- [x] [meta: state recovery when reboot meta](https://github.com/singularity-data/risingwave/issues/1277)
- [x]  #2646
