### ISSUE TITLE
Tracking: support union & union all

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#6392]
- [x] Support binder & planner. https://github.com/risingwavelabs/risingwave/pull/6363
- [x] support batch union operator & executor. https://github.com/risingwavelabs/risingwave/pull/4761
- [x] support streaming union all operator. https://github.com/risingwavelabs/risingwave/pull/6397
- [x] support streaming union operator (distinct semantic). https://github.com/risingwavelabs/risingwave/pull/6425
- [ ] optimize shuffle of batch union and stream union.
