### ISSUE TITLE
tracking: column pruning in optimizer 

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#640]
impl the `ColPrunable` for each plan node instead of default implantation. Notice that it should 
- call the prune_col of its input recursively
- rewrite its Condition and other Expression, rewrite its `InputRef` index
- rewrite its property like distribution and Order's index.

Mapping and ExprRewriter and other utils might be helpful

- [x] impl prune_col in `LogicalProject`
- [x] impl prune_col in `LogicalFilter`
- [x] impl prune_col in `LogicalJoin`
- [x] impl prune_col in `LogicalAgg`
- [x] impl prune_col in `LogicalTopN` 
- [x] Add a rule in `LogicalProject::new` to merge consecutive projects
