### ISSUE TITLE
Tracking: support CH-Benchmark for streaming e2e tests

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#6562]
- [x] Support streaming also, previously only batch queries
- [x] Support the missing Q5(no data)
- [x] Support the missing Q7(no data)
- [x] Support the missing Q8(no data)
- [x] Support the missing Q19(precision error)
- [x] #6875

~Related: #5190~

**Comment by fuyufjh** [comment]
Is it completed by https://github.com/risingwavelabs/risingwave/pull/5600 ?
