### ISSUE TITLE
Tracking: support index join

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#6589]
- [x] Batch lookup join supports lookup inner side table's prefix of the order key. https://github.com/risingwavelabs/risingwave/pull/6588
- [x] Covered index selection for lookup join. Enumerate the indexes of the inner side table, if one of them matches the join key, we use lookup join instead of hash join. https://github.com/risingwavelabs/risingwave/pull/6645
- [x] ~~Non-covered index selection for lookup join. It depends on whether we change the behavior of `create index` to covering all the table columns. If~~ we change the behavior, we don't need to support it. https://github.com/risingwavelabs/risingwave/pull/6702
- [ ] ~~Utilize the scan predicate and join predicate to make lookup more efficient.~~
- [x] Remove the restriction of join condition order. Currently, we match join conditions against the prefix of order key one by one. If users change the join condition order, it could fail to transform into a lookup join.https://github.com/risingwavelabs/risingwave/pull/6727
- [x] Enable `rw_batch_enable_lookup_join` by default. https://github.com/risingwavelabs/risingwave/pull/6818

**Comment by chenzl25** [comment]
Utilize the scan predicate and join predicate to make lookup more efficient. This one will be left for optimization in the future. The basic index join is done.
