### ISSUE TITLE
Tracking: table schema change

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#6903]
Design doc: [Table Schema Change](https://www.notion.so/risingwave-labs/Table-Schema-Change-dd4a452cde554005ae8668c7995f6d2a)

> In the streaming system, data is continuously ingested and processed in real time. This requires the table or the source to accommodate new fields and evolve its schema over time, according to the actual business. Therefore, the ability to modify the schema is a must-have feature for almost all production scenarios.
>
> This doc will mainly talk about a possible design of schema change of the **tables** in RisingWave, including the following aspects:
> 1. How to handle the `ALTER TABLE` requests by frontends and the meta service.
> 2. How to “update” the streaming pipeline of ingesting and materializing the table source data.
> 3. How to make later reads and writes compatible with the historical materialized data, and update them in a gradual manner if necessary.

## Tasks

- State Compatibility
  - [ ] Add DDL epoch as catalog version.
  - [ ] Introduce column-aware row encoding.
  - [ ] Integrate different row encoding for tables.
- Schema Change Procedure
  - [ ] Support binding and add handlers for `ADD COLUMN` requests.
  - [ ] Implement replacing table plan in meta service.
  - [ ] Support waiting for ongoing DML requests on compute nodes.
  - [ ] Integrate `ADD COLUMN` on the frontend with meta service.
- State Maintenance
  - [ ] Handle multi-version states in the compactor.
- Refinements and extensions
  - [ ] Support column ref-count and `DROP COLUMN`.
  - [ ] Handle index updates after schema change.
  - [ ] ...
