### ISSUE TITLE
Tracking: DAG Structured Query Plan

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#6955]
Based on the RFC: DAG Structured Query Plan https://github.com/risingwavelabs/rfcs/pull/28
- [x] : Support LogicalShare operator which has multiple parents. https://github.com/risingwavelabs/risingwave/pull/6956
- [x] : Support StreamShare operator. https://github.com/risingwavelabs/risingwave/pull/6956
- [x] : Make optimizer DAG aware, including predicate pushdown, column pruning, heuristic optimizer, stream rewrite and to stream. https://github.com/risingwavelabs/risingwave/pull/6956
- [x] : Make `toProst`/`Fragmenter` DAG aware. https://github.com/risingwavelabs/risingwave/pull/6956
- [x] : Make scale DAG aware. https://github.com/risingwavelabs/risingwave/pull/7013

LogicalShare generation: 

- [x] : Share source. https://github.com/risingwavelabs/risingwave/pull/6956
- [x] : Subquery unnesting. https://github.com/risingwavelabs/risingwave/pull/6956
- [x] : Share CTE. https://github.com/risingwavelabs/risingwave/pull/7204
- [x] : Share view. https://github.com/risingwavelabs/risingwave/pull/7432 

Improvement:
- [x] : Perform share source at the beginning of the logical optimization, so that we can benefit from predicate pushdown and column pruning. https://github.com/risingwavelabs/risingwave/pull/7111
- [ ] : Common sub-plan detection.

Others:
- [x] :  Support `RW_ENABLE_SHARE_PLAN` session variable to control whether to enable share plan. #7966
