### ISSUE TITLE
Tracking: migrating parser to byte stream based trait

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#7032]
we introduced a new byte-stream-based parser trait in #6846 to make the parsers functional with s3 source. But we are facing the request that supporting array as the top-level packaging (refer #6794), which breaks the existing agreement. So we are migrating to the new parser impl and making all parsers compatible with both mq and fs. 

~~In this dev plan, we are decoupling the source executor, connector source, and readers by async stream.~~

~~- [ ] migrate existing parsers to the new trait~~
~~- [ ] json~~
~~- [ ] avro~~
~~- [ ] canal~~
~~- [ ] debezium_json~~
~~- [ ] maxwell~~
~~- [ ] protobuf~~
~~- [ ] move down parsers into the connectors: let split readers produce data chunks directly (resolve #4961)~~
~~- [ ] allow parsing multiple rows in one record (as required in #6794)~~

Based on the implementation approach, the plan will be completed in the following order:
- [x] Introduce the new stream based source reader/parser trait #7422 
  - [x] move the `parser` mod into `connector` crate
  - [x] impl `SplitReaderV2` for `S3SplitReader` and `DummySplitReader`
  - [x] impl new `ByteStreamSourceParser` for `CsvParser`
- [x] Migrate other existing parsers/reader to the new traits
- [x] Resolve other related issues

**Comment by lmatz** [comment]
Nice! Then #6969 is not needed.
