### ISSUE TITLE
Tracking: Sqlsmith extras

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#7329]
SQL Features:
- [ ] Generate other table functions: `generate_series`, `unnest`. See: https://github.com/singularity-data/risingwave/issues/4540
- [ ] Generate array_agg

Refinements - Test suite:
- [ ] #3936
- [ ] #4415 
- [ ] Query shrinking to debug complex queries.
- [ ] Sqlsmith test: test inserts
- [ ] Sqlsmith test: test random seed
- [ ] Sqlsmith test: test parsing
- [ ] Sqlsmith test: panic recovery on various types of panics. Should print complete query to reproduce.
- [ ] Print back trace when fail - easier to fix sqlsmith errors.
- [ ] Refine recursion so that probability of recursion drop with increasing depth of recursion See: https://github.com/singularity-data/risingwave/pull/4216#discussion_r934130194
- [ ] Revisit `gen_from_relation`'s use of `can_recurse`. Other branches might recurse in the future. See: https://github.com/singularity-data/risingwave/pull/4216/files#r934137424

**Comment by jon-chuang** [comment]
I noticed that the plans generated often evaluate to very idiosyncratic queries. Hence, I am worried about the actual coverage. I believe the coverage for frontend/optimizer side may be ok, but am more worried about the e2e testing (batch and stream part). I am suggested several ideas to get a better understanding of the e2e coverage:

1. Test how many columns/table are in the underlying tables referenced v.s. columns/tables in the final optimized query plan. If a column does not appear in the final query or in a condition, it is very likely to be pruned away, so we do not get coverage.
2. Another issue is that with enough expressions, a condition always ends up being either false or true. Hence I would suggest not putting too many literals in expressions. The metric here is fraction of expressions that reference input variables after they have been optimized in frontend.

**Comment by kwannoel** [comment]
Sqlsmith feature gen is long running task. Track here instead: https://github.com/risingwavelabs/risingwave/issues/7934
