### ISSUE TITLE
Tracking: Session Timezone

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#7334]
- [x] Session timezone in session config (https://github.com/risingwavelabs/risingwave/issues/7175, https://github.com/risingwavelabs/risingwave/pull/7216)
- [x] Session timezone in expr (https://github.com/risingwavelabs/risingwave/issues/5826)
  - [x] Cast (https://github.com/risingwavelabs/risingwave/pull/7243)
  - [x] Cmp (https://github.com/risingwavelabs/risingwave/pull/7243)
  - [x] Arithmetic (https://github.com/risingwavelabs/risingwave/pull/7751)
- [x] Session timezone in PG Response (https://github.com/risingwavelabs/risingwave/issues/7336)
- [x] Add timezone metadata to MV catalog (https://github.com/risingwavelabs/risingwave/issues/7337)
- [ ] Interpretation and encoding of timezone? (https://github.com/risingwavelabs/risingwave/issues/7335)
  - [ ] ~~Support more timezone strings (https://github.com/risingwavelabs/risingwave/issues/7338)~~
- [ ] Session timezone in source? (under discussion)
- [x] Catch and replace instantiations of Expression outside of frontend
  - [x] (local and distributed batch) Lookup join (https://github.com/risingwavelabs/risingwave/pull/8402)
  - [x] (stream: https://github.com/risingwavelabs/risingwave/pull/8415, batch: https://github.com/risingwavelabs/risingwave/pull/8403) hop window

**Comment by jon-chuang** [comment]
> Interpretation and encoding of timezone

Not currently planned.
