### ISSUE TITLE
Tracking: sink refactor for separating append-only and non-append-only

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave#7414]
ref: https://www.notion.so/risingwave-labs/Sink-User-Behavior-Guideline-be17dc1d7c89415388bb7bb43effcbe9

- [x] make sink know whether it is append-only
- [x] add `force-append-only`
- [x] reject non-append-only requests when the connector is append-only
