### ISSUE TITLE
Tracking: optimizer session variables and hints

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#7491]
Session variables:
- [ ] `SET FORCE_DELTA_JOIN TO true`
- [ ] `SET FORCE_TWO_PHASE_AGG TO true`
- [ ] `SET DISABLE_TWO_PHASE_AGG TO true`
- [ ] `SET FORCE_LEFT_DEEP_JOIN TO true`
- [ ] `SET FORCE_BUSHY_JOIN TO true`

Optimizer hints:
- https://github.com/ossc-db/pg_hint_plan#hints-list
- https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/queries/hints/#broadcast

**Comment by chenzl25** [comment]
`DISABLE_TWO_PHASE_AGG` and `FORCE_TWO_PHASE_AGG` seem can't be both set to true. A priority needs to be introduced.

**Comment by lmatz** [comment]
Suppose a query can utilize multiple indexes to accelerate itself, is it possible for the current optimizer to choose a suboptimal one?

I guess this can be supported only after hints are introduced if let's say this is necessary
