### ISSUE TITLE
Tracking: Fix `TODO`s

### ISSUE THREAD

**Issue by twocode** [risingwavelabs/risingwave#75]
```shell
#! /bin/bash

grep -rsni "todo:" --include *.rs --exclude-dir=target . | awk 'BEGIN { FS = "/{2,} "} ; {print "`` "$2" ``" " at line "$1}'
grep -rsni "todo!()" --include *.rs --exclude-dir=target . | awk 'BEGIN { FS = ":[ ]+"} ; {print "`` "$2" ``" " at line "$1}'
grep -rsni "fixme" --include *.rs --exclude-dir=target . | awk 'BEGIN { FS = "/{2,} "} ; {print "`` "$2" ``" " at line "$1}'
```

- [x] singularity-data/risingwave-legacy#2606
- [x] singularity-data/risingwave-legacy#2675
- [ ] `` TODO: in some cases, the scan can be optimized into a `multi_get` request. `` at line ./storage/src/store.rs:27:
- [x] `` TODO: initialize those settings in a yaml file or command line instead of hard-coding `` at line ./storage/src/store.rs:127:
- [x] `` TODO: Ord Trait with 'a'+ts>'aa'+ts issue `` at line ./storage/src/hummock/key_range.rs:8:
- [x] `` TODO: precisely pass the version number that can be vacuum. `` at line ./storage/src/hummock/version_manager.rs:93:
- [x] `` TODO: This function maybe removed in the future. `` at line ./storage/src/hummock/version_manager.rs:198:
- [x] #1161
- [x] `` TODO: We do not need to add splits every time. We can add every K SSTs. `` at line ./storage/src/hummock/version_manager.rs:476:
- [x] #1279
- [x] #91
- [ ] `` TODO: decide upload concurrency `` at line ./storage/src/hummock/mod.rs:244:
- [x] #92
- [x] `` TODO: use different option values (especially table_size) for compaction `` at line ./storage/src/hummock/mod.rs:281:
- [ ] `` TODO: decide upload concurrency `` at line ./storage/src/hummock/compactor.rs:198:
- [x] `` TODO: delete these tables in (S3) storage `` at line ./storage/src/hummock/compactor.rs:224:
- [x] `` TODO: remove the version once we can pin a ts. `` at line ./storage/src/hummock/snapshot.rs:23:
- [x] `` TODO: Modify this line once we support ts-aware compaction and `ts` pinning. `` at line ./storage/src/hummock/snapshot.rs:34:
- [x] `` TODO: use the latest version once the ts-aware compaction is realized. `` at line ./storage/src/hummock/snapshot.rs:52:
- [x] `` TODO: use the latest version once the ts-aware compaction is realized. `` at line ./storage/src/hummock/snapshot.rs:98:
- [x] `` TODO: avoid this clone `` at line ./storage/src/hummock/snapshot.rs:130:
- [x] `` TODO: use the latest version once the ts-aware compaction is realized. `` at line ./storage/src/hummock/snapshot.rs:152:
- [x] `` TODO: avoid this clone `` at line ./storage/src/hummock/snapshot.rs:184:
- [x] `` TODO: should store Arc<Table> instead of table_id in TableStat `` at line ./storage/src/hummock/level_handler.rs:3:
- [x] `` TODO: this wrapper introduces extra overhead of async trait, may be turned into an enum if `` at line ./storage/src/hummock/state_store.rs:12:
- [x] `` TODO: reduce the redundant vec clone `` at line ./storage/src/hummock/state_store.rs:41:
- [x] #1264
- [ ] `` todo: check whether this hack improves performance `` at line ./storage/src/hummock/key.rs:19:
- [ ] `` todo: check whether this hack improves performance `` at line ./storage/src/hummock/key.rs:46:
- [ ] `` TODO: Since the real world workload may follow power law or 20/80 rule, or whatever name. `` at line ./storage/src/hummock/iterator/reverse_user_key.rs:142:
- [ ] `` TODO: decide whether this should also impl `HummockIterator` `` at line ./storage/src/hummock/iterator/user_key.rs:83:
- [ ] `` TODO: support custom comparator `` at line ./storage/src/hummock/table/block_iterator.rs:16:
- [x] `` TODO: combine this decode with header decode to avoid slice ptr copy `` at line ./storage/src/hummock/table/block_iterator.rs:81:
- [ ] `` TODO: merge this truncate with the following key truncate `` at line ./storage/src/hummock/table/block_iterator.rs:97:
- [ ] `` TODO: remove this collect_vec `` at line ./storage/src/hummock/table/block_iterator.rs:121:
- [x] `` TODO: may add an option for meta checksum algorithm `` at line ./storage/src/hummock/table/mod.rs:176:      ChecksumAlg::XxHash64,
- [ ] `` TODO: why 5? `` at line ./storage/src/hummock/table/builder.rs:237:                                  5 * self.meta.block_metas.len() as u32;
- [ ] `` TODO: move boundaries and build index if we need to encrypt or compress `` at line ./storage/src/hummock/table/builder.rs:246:
- [x] `` TODO: actually use epoch and support rollback `` at line ./storage/src/memory.rs:144:
- [x] `` TODO: [xiangyhu] flush using persist::fs module `` at line ./storage/src/bummock/table.rs:244:
- [x] `` TODO: Since we only need to know how many rows are visible, `` at line ./storage/src/bummock/table.rs:249:
- [x] `` TODO: [xiangyhu] footers `` at line ./storage/src/bummock/rg.rs:32:
- [x] `` TODO: [xiangyhu] replace this with Parquet `` at line ./storage/src/bummock/rg.rs:35:
- [x] `` TODO: introduce sled/etcd as storage engine here. `` at line ./meta/src/storage/metastore.rs:98:
- [ ] `` TODO: use a monotonic library to replace SystemTime. `` at line ./common/src/util/epoch.rs:34:
- [x] `` TODO: should store Arc<Table> instead of table_id in TableStat `` at line ./meta/src/hummock/level_handler.rs:4:
- [ ] `` TODO: return error instead of panic `` at line ./meta/src/hummock/hummock_manager.rs:813:
- [ ] `` TODO: use pointer last time to avoid binary search `` at line ./meta/src/hummock/compaction.rs:153:
- [ ] `` TODO: We do not need to add splits every time. We can add every K SSTs. `` at line ./meta/src/hummock/compaction.rs:185:
- [ ] `` TODO: loop only in input levels `` at line ./meta/src/hummock/compaction.rs:322:
- [ ] `` TODO: error handling `` at line ./meta/src/dashboard/mod.rs:88:      )
- [ ] `` TODO: handle error `` at line ./meta/src/dashboard/mod.rs:92:      .collect_vec();
- [ ] `` TODO: remove adding test data `` at line ./meta/src/dashboard/mod.rs:274:
- [ ] `` TODO: remove adding frontend register when frontend implement register. `` at line ./meta/src/dashboard/mod.rs:278:
- [ ] `` TODO: replace fragment id with IdGenerator, fragment id may need to store in MetaStore. `` at line ./meta/src/stream/fragmenter.rs:24:
- [x] `` todo: remove the lock, refactor `node_actors` storage. `` at line ./meta/src/stream/meta.rs:36:
- [ ] `` TODO: join dashboard service back to local thread `` at line ./meta/src/rpc/server.rs:64:    tokio::spawn(dashboard_service.serve());
- [ ] `` TODO: currently not a vectorized implementation `` at line ./batch/src/executor/hash_agg.rs:163:
- [ ] `` TODO: currently the order is fixed `` at line ./batch/src/executor/hash_agg.rs:308:
- [ ] `` TODO: [`Row`] may not be PartialOrd. May use some trait like [`ScalarPartialOrd`]. `` at line ./batch/src/executor/join/sort_merge_join.rs:102:
- [ ] `` TODO: Support more join type. `` at line ./batch/src/executor/join/sort_merge_join.rs:263:
- [ ] `` TODO: Replace this with unsorted comparison `` at line ./batch/src/executor/join/hash_join.rs:657:
- [ ] `` Buffering of inner table. TODO: Spill to disk or more fine-grained memory management to avoid `` at line ./batch/src/executor/join/row_level_iter.rs:13:
- [ ] singularity-data/risingwave-legacy#2860
- [ ] `` TODO: Support more join type. `` at line ./batch/src/executor/join/nested_loop_join.rs:211:
- [ ] `` TODO: Does not handle `visibility` for now. `` at line ./batch/src/executor/merge_sort_exchange.rs:32:
- [ ] `` TODO: vals &[i32] => vals &[Option<i32>] `` at line ./batch/src/task/test_utils.rs:428:
- [ ] `` TODO: Write an iterator for FixedWidthColumn `` at line ./batch/src/task/test_utils.rs:484:
- [ ] `` TODO: _config will be used by streaming env & batch env. `` at line ./server/src/server.rs:41:  let _config = load_config(&opts);
- [ ] `` TODO: We should use this function in future release of `opentelemetry_jaeger` `` at line ./server/src/bin/compute_node.rs:15:
- [ ] `` TODO: Enable this in release mode `` at line ./server/src/bin/compute_node.rs:19:
- [ ] `` TODO: implement `DROP CONSTRAINT <name>` `` at line ./sqlparser/src/ast/ddl.rs:34:
- [ ] `` TODO: ANSI SQL supports `TABLE` here. `` at line ./sqlparser/src/ast/query.rs:82:
- [ ] `` escape sequences (if any) processed (TODO: escapes are not handled) `` at line ./sqlparser/src/tokenizer.rs:225:
- [ ] `` TODO: deal with nested comments `` at line ./sqlparser/src/tokenizer.rs:652:
- [ ] `` TODO: add assertions `` at line ./sqlparser/tests/sqlparser_common.rs:431:
- [ ] `` TODO: add assertions `` at line ./sqlparser/tests/sqlparser_common.rs:457:
- [ ] `` TODO: add assertions `` at line ./sqlparser/tests/sqlparser_common.rs:464:
- [ ] `` TODO: assertions `` at line ./sqlparser/tests/sqlparser_common.rs:1896:
- [ ] `` TODO: add assertions `` at line ./sqlparser/tests/sqlparser_common.rs:2670:
- [ ] `` TODO: add assertions `` at line ./sqlparser/tests/sqlparser_common.rs:2676:
- [ ] `` TODO: add assertions `` at line ./sqlparser/tests/sqlparser_common.rs:2680:
- [ ] `` TODO: add assertions `` at line ./sqlparser/tests/sqlparser_common.rs:2684:
- [ ] `` TODO: add assertions `` at line ./sqlparser/tests/sqlparser_common.rs:2715:
- [ ] `` TODO: check `data_type` directly `` at line ./stream/src/executor/schema_check.rs:57:        let builder = field.data_type.create_array_builder(0)?;
- [ ] `` TODO: add macro row!, which requires a new trait `ToScalarValue`. `` at line ./stream/src/executor/test_utils.rs:12:
- [ ] `` TODO: This can be optimized while async gen fn stablized. `` at line ./stream/src/executor/hash_agg.rs:41:
- [ ] `` TODO: decide the target cap `` at line ./stream/src/executor/hash_agg.rs:78:      state_map: EvictableHashMap::new(1 << 16),
- [x] singularity-data/risingwave-legacy#2589
- [ ] `` TODO: this might be inefficient if there are not too many duplicated keys in one batch. `` at line ./stream/src/executor/hash_agg.rs:165:
- [ ] `` TODO: Use enum to replace this once `feature(adt_const_params)` get completed `` at line ./stream/src/executor/hash_join.rs:20:
- [ ] `` TODO: Remove this `data_types` when we replace columns with arrays `` at line ./stream/src/executor/hash_join.rs:109:
- [x] singularity-data/risingwave-legacy#2682
- [ ] `` TODO: find a better capacity number, the actual array length `` at line ./stream/src/executor/hash_join.rs:399:
- [ ] `` TODO: in pure in-memory engine, we should not do this serialization. `` at line ./stream/src/executor/aggregation/agg_executor.rs:283:
- [ ] `` TODO: May be refactored in the future. `` at line ./stream/src/executor/mview/snapshot.rs:80:
- [ ] `` TODO: use the new streaming_if_null expression here, and add `None` tests `` at line ./stream/src/executor/integration_tests.rs:152:
- [ ] `` TODO: use the new streaming_if_null expression here, and add `None` tests `` at line ./stream/src/executor/integration_tests.rs:429:
- [ ] `` TODO: remove unwrap `` at line ./stream/src/executor/merge.rs:133:      .unwrap();
- [ ] `` TODO: Refactor this once we find a better way to know the upstream is done. `` at line ./stream/src/executor/chain.rs:47:
- [ ] `` TODO: Can we update ops and visibility inplace? `` at line ./stream/src/executor/filter.rs:84:
- [ ] `` TODO: This can be further optimized as `Delete` and `Insert` may cancel each other. `` at line ./stream/src/executor/managed_state/aggregation/string_agg.rs:178:
- [x] singularity-data/risingwave-legacy#2699
- [ ] `` TODO: estimate a good cache size instead of hard-coding `` at line ./stream/src/executor/managed_state/aggregation/mod.rs:101:
- [ ] `` TODO: for append-only lists, we can create `ManagedValueState` instead of `` at line ./stream/src/executor/managed_state/aggregation/mod.rs:112:
- [ ] `` TODO: support `&K` instead of `K` as parameter. `` at line ./stream/src/executor/managed_state/aggregation/extreme_serializer.rs:51:
- [x] `` Flush the internal state to a write batch. TODO: add `WriteBatch` to Hummock. `` at line ./stream/src/executor/managed_state/aggregation/value.rs:89:
- [x] `` Flush the internal state to a write batch. TODO: add `WriteBatch` to Hummock. `` at line ./stream/src/executor/managed_state/aggregation/extreme.rs:92:
- [x] `` Flush the internal state to a write batch. TODO: add `WriteBatch` to Hummock. `` at line ./stream/src/executor/managed_state/aggregation/extreme.rs:297:
- [ ] `` TODO: we can populate the cache while flushing, but that's hard. `` at line ./stream/src/executor/managed_state/aggregation/extreme.rs:309:
- [ ] `` TODO: in pure in-memory engine, we should not do this serialization. `` at line ./stream/src/executor/managed_state/join/mod.rs:17:
- [x] `` TODO: This needs to be changed when transaction on Hummock is implemented. `` at line ./stream/src/executor/managed_state/top_n/top_n_state.rs:146:
- [ ] `` TODO: `Flush` should also be called internally when `top_n` and `flush_buffer` exceeds certain `` at line ./stream/src/executor/managed_state/top_n/top_n_state.rs:370:
- [ ] `` TODO: This can be optimized while async gen fn stablized. `` at line ./stream/src/executor/simple_agg.rs:37:
- [ ] `` TODO: Optimization: primary key may contain several columns and is used to determine `` at line ./stream/src/executor/top_n_appendonly.rs:49:
- [ ] `` TODO: in the future, we may add row_id column here for TableV2 as well `` at line ./stream/src/executor/stream_source.rs:116:
- [ ] `` TODO: remove this `` at line ./stream/src/task/stream_manager.rs:101:
- [ ] `` TODO: this should be replaced with real id from frontend `` at line ./stream/src/task/stream_manager.rs:108:
- [ ] `` TODO: We will refine this method when the meta service is ready. `` at line ./stream/src/task/stream_manager.rs:129:
- [ ] `` TODO: We will refine this method when the meta service is ready. `` at line ./stream/src/task/stream_manager.rs:135:
- [ ] `` TODO: We will refine this method when the meta service is ready. `` at line ./stream/src/task/stream_manager.rs:349:
- [ ] `` TODO: We will refine this method when the meta service is ready. `` at line ./stream/src/task/stream_manager.rs:361:
- [ ] `` TODO: The channel pair should be created by the Checkpoint manger. So this line may `` at line ./stream/src/task/stream_manager.rs:417:
- [ ] `` TODO: `` at line ./frontend/src/optimizer/plan_node/logical_join.rs:10:
- [ ] `` TODO: give joinType and consider `` at line ./frontend/src/optimizer/plan_node/logical_join.rs:33:
- [ ] `` TODO: give project expressions `` at line ./frontend/src/optimizer/plan_node/logical_project.rs:19:
- [ ] `` TODO: our backend not support some equal columns and sonm NonEqual condition `` at line ./frontend/src/optimizer/plan_node/join_predicate.rs:27:
- [ ] `` TODO: we have not Statistics to use broadcast join `` at line ./frontend/src/optimizer/plan_pass/batch_to_distributed.rs:68:
- [ ] `` TODO: use passThrough get a better plan `` at line ./frontend/src/optimizer/plan_pass/logical_to_stream.rs:11:
- [ ] `` TODO: we have not Statistics to use broadcast join `` at line ./frontend/src/optimizer/plan_pass/logical_to_stream.rs:69:
- [ ] `` TODO: we should have a builder of HeuristicOptimizer here `` at line ./frontend/src/optimizer/plan_pass/heuristic.rs:18:
- [ ] `` TODO: add transaction status `` at line ./frontend/src/pgwire/pg_message.rs:253:
- [ ] `` TODO: `` at line ./frontend/src/expr/type_inference.rs:32:
- [ ] `` TODO: this snippet is redundant `` at line ./source/src/table.rs:50:
- [ ] `` TODO: Currently batch read directly calls api from `ScannableTable` instead of using `` at line ./source/src/table_v2.rs:69:
- [ ] `` TODO: see if it is possible to implement this trait directly on `ScalarRef`. `` at line ./common/src/types/scalar_impl.rs:6:
- [ ] `` TODO: specify `NULL FIRST` or `NULL LAST`. `` at line ./common/src/types/mod.rs:227:
- [ ] `` TODO: specify `NULL FIRST` or `NULL LAST`. `` at line ./common/src/types/mod.rs:252:
- [ ] `` TODO: may take type information into consideration later `` at line ./common/src/types/mod.rs:444:
- [ ] `` TODO: handle nan and inf `` at line ./common/src/types/decimal.rs:318:
- [ ] `` TODO: handle nan and inf `` at line ./common/src/types/decimal.rs:325:
- [ ] `` TODO: Use techniques like apache arrow flight RPC to eliminate deserialization. `` at line ./common/src/array/column_proto_readers.rs:15:
- [ ] `` TODO: force convert usize to u64, frontend will treat this offset buffer as u64 `` at line ./common/src/array/utf8_array.rs:56:
- [ ] `` TODO: How about char? `` at line ./common/src/array/mod.rs:540:
- [ ] `` TODO: Optimize using bitmap `` at line ./common/src/array/stream_chunk.rs:61:
- [ ] `` TODO: We need better error reporting for stacktrace. `` at line ./common/src/error.rs:101:
- [ ] `` TODO: based on `memcomparable`, we may support more data type in the future. `` at line ./common/src/util/encoding_for_comparison.rs:13:
- [ ] `` TODO: specify the order for `NULL`. `` at line ./common/src/util/encoding_for_comparison.rs:45:
- [ ] `` TODO: We need to improve the error message `` at line ./common/src/vector_op/cmp.rs:16:
- [ ] `` TODO: We need to improve the error message `` at line ./common/src/vector_op/arithmetic_op.rs:87:
- [ ] `` Currently no-op. TODO: implement padding and overflow check (#2137) `` at line ./common/src/vector_op/cast.rs:47:
- [ ] `` TODO: replace boilplate code `` at line ./common/src/catalog/mod.rs:50:
- [ ] `` TODO: replace boilplate code `` at line ./common/src/catalog/mod.rs:64:
- [ ] `` TODO: replace boilplate code `` at line ./common/src/catalog/mod.rs:83:
- [ ] `` TODO: We should remove this, a buffer should be immutable `` at line ./common/src/buffer/buffer.rs:47:
- [ ] `` TODO: We need to unify these `` at line ./common/src/expr/expr_literal.rs:152:
- [ ] `` TODO: add expr with the delimiter parameter `` at line ./common/src/expr/build_expr_from_prost.rs:87:
- [ ] `` TODO: add expr with the delimiter parameter `` at line ./common/src/expr/build_expr_from_prost.rs:95:
- [ ] `` TODO: add expr with the delimiter parameter `` at line ./common/src/expr/build_expr_from_prost.rs:103:
- [ ] `` TODO: add encoding length expr `` at line ./common/src/expr/build_expr_from_prost.rs:120:
- [ ] `` TODO: consider implement it using generic function. `` at line ./common/src/expr/expr_binary_nullable.rs:13:
- [ ] `` TODO: decide whether nullability-cast should be allowed (#2350) `` at line ./common/src/expr/expr_unary.rs:70:
- [ ] `` TODO: should we enforce strong typed body on nodes? `` at line ./prost/src/stream_plan.rs:124:
- [ ] `` TODO: should we enforce strong typed body on nodes? `` at line ./prost/src/stream_plan.rs:134:
- [ ] `` TODO: Add field name `` at line ./prost/src/task_service.rs:81:
- [ ] `` TODO: remove this, do catalog init in Meta and return in response. `` at line ./prost/src/meta.rs:268:
- [ ] `` TODO: migration mv catalog creation/drop in. `` at line ./prost/src/meta.rs:743:
- [ ] `` TODO: migration mv catalog creation/drop in. `` at line ./prost/src/meta.rs:1408:
- [ ] `` TODO: unwrap can panic when option is None `` at line ./prost/helpers/src/generate.rs:97:
- [x] `` todo!() `` at line ./storage/src/metrics/mod.rs:10
- [x] `` todo!(); `` at line ./storage/src/bummock/table.rs:204
- [x] `` todo!(); `` at line ./storage/src/bummock/table.rs:224
- [x] `` todo!(); `` at line ./storage/src/bummock/table.rs:241
- [x] `` todo!(); `` at line ./storage/src/bummock/table.rs:246
- [x] `` todo!(); `` at line ./storage/src/bummock/rg.rs:76
- [x] `` todo!(); `` at line ./storage/src/bummock/rg.rs:80
- [x] `` todo!(); `` at line ./storage/src/bummock/rg.rs:85
- [x] `` todo!(); `` at line ./storage/src/bummock/rg.rs:89
- [ ] `` todo!() `` at line ./meta/src/stream/stream_manager.rs:220
- [ ] `` todo!() `` at line ./meta/src/rpc/service/stream_service.rs:75
- [ ] `` todo!() `` at line ./meta/src/rpc/service/hummock_service.rs:151
- [ ] `` todo!() `` at line ./meta/src/rpc/service/hummock_service.rs:158
- [ ] `` todo!() `` at line ./meta/src/rpc/service/hummock_service.rs:165
- [ ] `` todo!() `` at line ./meta/src/rpc/service/hummock_service.rs:172
- [ ] `` todo!() `` at line ./batch/src/task/test_utils.rs:383
- [ ] `` todo!() `` at line ./batch/src/rpc/service/task_service.rs:50
- [ ] `` todo!() `` at line ./batch/src/rpc/service/task_service.rs:58
- [ ] `` _ => todo!(), `` at line ./stream/src/executor/aggregation/mod.rs:191
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/batch_project.rs:19
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/stream_hash_join.rs:19
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/logical_join.rs:18
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/logical_join.rs:35
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/logical_scan.rs:13
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/logical_scan.rs:22
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/batch_seq_scan.rs:13
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/batch_seq_scan.rs:20
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/stream_project.rs:14
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/logical_project.rs:21
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/logical_project.rs:35
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/join_predicate.rs:12
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/join_predicate.rs:15
- [ ] `` //     todo!() `` at line ./frontend/src/optimizer/plan_node/join_predicate.rs:29
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/batch_sort_merge_join.rs:22
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/batch_sort_merge_join.rs:41
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/batch_sort_merge_join.rs:47
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/batch_exchange.rs:28
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/batch_hash_join.rs:23
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/batch_sort.rs:29
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/stream_table_source.rs:13
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/stream_table_source.rs:20
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_node/stream_exchange.rs:26
- [ ] `` todo!() `` at line ./frontend/src/optimizer/rule/project_join.rs:8
- [ ] `` todo!(); // nestedLoopJoin `` at line ./frontend/src/optimizer/plan_pass/logical_to_batch.rs:83
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_pass/batch_to_distributed.rs:82
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_pass/batch_to_distributed.rs:86
- [ ] `` todo!() `` at line ./frontend/src/optimizer/plan_pass/batch_to_distributed.rs:90
- [ ] `` todo!() `` at line ./frontend/src/optimizer/property/order.rs:40
- [ ] `` todo!() `` at line ./frontend/src/optimizer/property/distribution.rs:53
- [ ] `` todo!() `` at line ./frontend/src/expr/type_inference.rs:44
- [ ] `` let return_type = todo!(); // should be derived from inputs `` at line ./frontend/src/expr/agg_call.rs:17
- [ ] `` todo!() `` at line ./source/src/pulsar/source.rs:103
- [ ] `` todo!() `` at line ./source/src/pulsar/source.rs:107
- [ ] `` todo!() `` at line ./source/src/pulsar/source.rs:287
- [ ] `` todo!() `` at line ./source/src/table_v2.rs:77
- [ ] `` todo!() `` at line ./source/src/table_v2.rs:81
- [ ] `` todo!() `` at line ./source/src/table_v2.rs:85
- [x] `` todo!() `` at line ./source/src/high_level_kafka.rs:229
- [x] `` todo!() `` at line ./source/src/high_level_kafka.rs:233
- [x] `` todo!() `` at line ./source/src/high_level_kafka.rs:309
- [x] `` todo!() `` at line ./common/src/types/interval_type.rs:145
- [x] `` FIXME: error message in `result` should not be ignored `` at line ./storage/src/hummock/compactor.rs:241:
- [ ] `` FIXME: should we check `is_primary` in pb `ColumnDesc` after we support pk? `` at line ./storage/src/table/mview.rs:72:
- [ ] `` FIXME: there's is a consistency problem between get/set, fix this after refactor metastore. `` at line ./meta/src/cluster/worker_manager.rs:29:
- [ ] `` FIXME: should do flush on checkpoint in the future `` at line ./batch/src/executor/insert.rs:121:
- [ ] `` FIXME: We should trigger barrier from meta service. Currently, we use a timer to `` at line ./server/src/server.rs:49:
- [ ] `` FIXME: for `SimpleAgg`, should we still build some changes when `row_count` is 0 while `` at line ./stream/src/executor/aggregation/agg_executor.rs:101:
- [ ] `` FIXME: unnecessary compact. `` at line ./stream/src/executor/filter.rs:74:
- [ ] `` FIXME: may lose message `` at line ./stream/src/executor/stream_source.rs:107:
- [ ] `` FIXME: after merger is refactored in proto, put pk_indices into it. `` at line ./stream/src/task/stream_manager.rs:779:
- [ ] `` FIXME: We have to make sure that `append_chunk` has been processed by the actor first, `` at line ./stream/src/task/test_mv.rs:192:
- [ ] `` FIXME: use channel when testing hummock to make sure local state has already flushed. `` at line ./stream/src/task/test_mv.rs:197:
- [ ] `` FIXME: should implement Hash and Eq all by deriving `` at line ./common/src/types/mod.rs:443:
- [ ] `` FIXME: This code is adapted from numeric type. Maybe we should unify them `` at line ./common/src/types/datetime_type.rs:29:
- [ ] `` FIXME: if this derives `PartialEq` and `PartialOrd`, caller must guarantee the fields are valid. `` at line ./common/src/types/interval_type.rs:16:
- [ ] `` FIXME: add support for precision in microseconds. `` at line ./common/src/vector_op/cast.rs:68:
- [ ] `` FIXME: make private while new function available. `` at line ./common/src/expr/template.rs:24:
- [ ] `` FIXME: make private while new function available. `` at line ./common/src/expr/template.rs:131:
- [ ] `` FIXME: make private while new function available. `` at line ./common/src/expr/template.rs:234:
- [ ] `` FIXME: We can not unify char and varchar because they are different in PG while share the `` at line ./common/src/expr/expr_unary.rs:112:

**Comment by fuyufjh** [comment]
Shall we unpin this? There is almost no progress for a month :(

**Comment by xxchan** [comment]
This tracking isn't meaningful anymore. Use separate tracking issues instead
