### ISSUE TITLE
Tracking: jsonb operations

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#7714]
Listing all jsonb operations from [PostgreSQL](https://www.postgresql.org/docs/15/functions-json.html), and which ones to implement now, soon, or until requested.

### Basic
  * [x] TEXT format input / output (same as cast from / to string)
  * [x] BINARY format input / output
### General for all types:
  * [x] `IS [NOT] NULL` / `CASE WHEN` / `COALESCE` / etc
### Eq / Hash / Ord
  * There is no plan to support this type of operations right now.
  * Also includes `IS [NOT] DISTINCT` / `NULLIF` / `IN` / etc
### Cast to simple types
  * [x] bool
  * [x] smallint / int / bigint / decimal / real / double precision
  * There is no cast from them to jsonb, but a function `to_jsonb`.
### Accessing array / object
  * [x] `-> int` / `-> varchar`: to access member as `jsonb` or cast to bool / number
  * [x] `->> int` / `->> varchar`: to access member as string. (Note that cast to string is DIFFERENT. See example below.)
  * [x] `#> varchar[]` / `#>> varchar[]` #13110 
  * [x] `jsonb_extract_path` / `jsonb_extract_path_text`: #13143
### Informative / Debugging
  * [x] `jsonb_array_length`
  * [x] `jsonb_pretty` #13050 
  * [x] `jsonb_typeof`
### Predicate
  * [x] `?` / `?|` / `?&`: object key lookup
    * TODO: decide what to do for array element lookup, which only works for string and may just be a side effect. See example below.
  * [x] `@>` / `<@`: [containment](https://www.postgresql.org/docs/15/datatype-json.html#JSON-CONTAINMENT) #13056 
### Construction / Mutation
  * [x] #12180
  * [x] `-` array index / `-` object key (also array string element) / `-` object keys / `#-` path #13118 
  * `jsonb_strip_nulls`
  * [x] #12834: basis of many operations below.
  * [x] #13016
  * [x] `jsonb_object`: only when values are also strings. #13036 
### [Subscripting](https://www.postgresql.org/docs/current/datatype-json.html#JSONB-SUBSCRIPTING)
  * Avoid `j[index]` / `j[key]` and use `#>` / `#>>` / `->` / `->>` instead.
### Aggregation
  * [x] jsonb_agg #9452 
  * [x] jsonb_object_agg
### Table Function (aka Set Returning Function)
  * [x] #11570
  * [x] jsonb_each / jsonb_each_text / jsonb_object_keys #9977 
### Advanced
  * `jsonb_populate_record` / `jsonb_populate_recordset` / `jsonb_to_record` / `jsonb_to_recordset`
  * `jsonb_set` / `jsonb_set_lax` #17103 
  * `jsonb_insert`
  * `row_to_json` / `array_to_json`
## Additional Details

While SQL array is 1-indexed, JSON array as part of SQL is still 0-indexed.

Our goal is to ingest JSON data and then extract strongly-typed columns from it. So operations on constructing / mutating / comparison of JSON are not of interest right now.

Dedicated string member access operator vs Cast to string
```
with t(v1) as (values (null::jsonb), ('null'), ('true'), ('1'), ('"a"'), ('[]'), ('{}')),
     j(v1) as (select ('{"k":' || v1::varchar || '}')::jsonb from t)
select
    v1 ->> 'k',
    (v1 -> 'k')::varchar,
    jsonb_typeof(v1 -> 'k')
from j order by 2;
----
a "a" string
1 1 number
[] [] array
NULL null null
true true boolean
{} {} object
NULL NULL NULL
```

Operations on object keys also work for array string elements
(TODO)

**Comment by xiangjinwu** [comment]
Removing the milestone as the remaining operators are optional / long-term.

**Comment by st1page** [comment]
`jsonb_populate_record` / `jsonb_populate_recordset` / `jsonb_to_record` / `jsonb_to_recordset`

Also, We might need another expression to optimize the `ARRAY(jsonb_populate_recordset())` and `ARRAY(jsonb_populate_recordset())` for user to fast cast from jsonb array to `array of structs`

**Comment by xiangjinwu** [comment]
> Also, We might need another expression to optimize the `ARRAY(jsonb_populate_recordset())` and `ARRAY(jsonb_populate_recordset())` for user to fast cast from jsonb array to `array of structs`

Opened a dedicated issue: #17617

**Comment by xxchan** [comment]
What's still missing? Looks mostly finished

**Comment by xiangjinwu** [comment]
> What's still missing? Looks mostly finished

PostgreSQL 16 (and maybe the upcoming 17) is still actively adding more JSON expressions. But I am okay with either close this or keep it open. We have no plan to add those proactively in the near future.
