### ISSUE TITLE
tracking: stream values executor

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#7857]
~~***the old design does not consider the failover very well, waiting for a new design***~~

We used to think users do not need stream values in streaming queries. But now we found it: https://github.com/risingwavelabs/risingwave/issues/7854
Now we can not support the constant Rows in our streaming execution because we have not supported StreamValuesExecutor.

- [ ] Refactor on the barrier receiving.
  - [ ] #7856
- [x] Support `StreamValues` plan node in the optimizer.
- [x] Rewrite `LogicalValues` to `StreamBarrierRecv` + `StreamValues` + `StreamRowIdGen` in the optimizer.
  - [x] #8635 
- [x] Enrich the `AddMutation` to check whether the executor is fresh-start.
- [x] Streaming `Values` executor.

**Comment by BugenZhao** [comment]
> * Rewrite `LogicalValues` to `StreamBarrierRecv` + `StreamValues` + `StreamRowIdGen` in the optimizer.

Note: this part might be tricky, as after we attach the `RowIdGen` node to the plan, the schema of the `Values` is changed. So this should be done in `logical_rewrite_for_stream` and maybe we also need to introduce the logical one of `RowIdGen`.
