### ISSUE TITLE
Support google cloud storage for RisingWave

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#7920]
There are two ways to use google cloud storage in RisingWave:
- via `OpenDAL`, which is similar to hdfs support.
- via s3 protocol as gcs is s3 compatible, which is similar to cos support.
### Roadmap
- [x] Support gcs via `OpenDAL`
- [x] Support gcs via s3 protocol
- [x] benchmark the performance of the two implementations and choose one
- [ ] support gcs config in RisingWave Operator

**Comment by wcy-fdu** [comment]
I will give some detailed benchmark result later. cc @Xuanwo

**Comment by wcy-fdu** [comment]
## Benchmark Result(left: OpenDAL gcs & right s3-compatible gcs)
Editing...

**Comment by wcy-fdu** [comment]
Note that when running with s3-compatible mode, compactor panic after running for a while, I will investigate this issue
```
ObjectStore failed with IO error Error { code: "NoSuchKey", message: "The specified key does not exist." }.
  backtrace of `HummockError`:
   0: <risingwave_storage::hummock::error::HummockError as core::convert::From<risingwave_storage::hummock::error::HummockErrorInner>>::from
             at ./src/storage/src/hummock/error.rs:68:10
   1: <T as core::convert::Into<U>>::into
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/convert/mod.rs:726:9
   2: <risingwave_storage::hummock::error::HummockError as core::convert::From<risingwave_object_store::object::error::ObjectError>>::from
             at ./src/storage/src/hummock/error.rs:170:9
   3: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/result.rs:2107:27
   4: risingwave_storage::hummock::sstable_store::SstableStore::delete_list::{{closure}}
             at ./src/storage/src/hummock/sstable_store.rs:189:9
   5: risingwave_storage::hummock::vacuum::Vacuum::vacuum_inner::{{closure}}
             at ./src/storage/src/hummock/vacuum.rs:63:44
   6: risingwave_storage::hummock::vacuum::Vacuum::vacuum::{{closure}}
             at ./src/storage/src/hummock/vacuum.rs:44:9
   7: risingwave_storage::hummock::compactor::Compactor::start_compactor::{{closure}}::{{closure}}
             at ./src/storage/src/hummock/compactor/mod.rs:427:41
   8: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/wangcongyi/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
```

**Comment by wcy-fdu** [comment]
Seems that `OpenDAL` is stable than accessing gcs directly with s3 sdk.

**Comment by Xuanwo** [comment]
GC will be faster after opendal implemented batch operation (delete objects).

**Comment by Xuanwo** [comment]
> Seems that in s3-compatible mode, the compactor is basically not running, the throughput of compactor's read/write obj store is almost 0. I guess the compatibility of gcs to s3 has problems on some interfaces. From this perspective, `OpenDAL` is stable than s3-compatible.

Thanks for the detailed benchmark! Can I refer some images here in my blog or twitter?

**Comment by Xuanwo** [comment]
> Seems that in s3-compatible mode, the compactor is basically not running, the throughput of compactor's read/write obj store is almost 0.

The xml API of gcs (also known as s3-compatible mode) does not seem to support `delete-objects`.

**Comment by hzxa21** [comment]
> > Seems that in s3-compatible mode, the compactor is basically not running, the throughput of compactor's read/write obj store is almost 0. I guess the compatibility of gcs to s3 has problems on some interfaces. From this perspective, `OpenDAL` is stable than s3-compatible.
> 
> Thanks for the detailed benchmark! Can I refer some images here in my blog or twitter?

Sure. We are open-sourced and the information here is all public. Thanks for your contribution and support for RisingWave community :)

But do keep in mind that the streaming workload we use here is quite simple and we are using a single-node cluster. The benchmark result is mainly for verifying there is no correctness and obvious performance/stability issue. A more sophisticated and serious benchmark should be done if we want to do performance comparison among different backends or different implementations.
