### ISSUE TITLE
Tracking: Process time temporal join

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#8123]
Implement process time temporal join based on the RFC: https://github.com/risingwavelabs/rfcs/pull/49:

- [x] `FOR SYSTEM_TIME AS OF NOW()` syntax. (#8480)
- [x] Convert a logical join to a temporal join (~~Use a rule or directly~~ implement in `to_stream_plan`~~? Need investigation~~). (#8466)
- [x] Stream Process time temporal join operator. (#8466)
- [x] Process time temporal join executor. (#8412)
- [x] Loose temporal join restrictions to allow join condition containing only the prefix of the right table's pk. https://github.com/risingwavelabs/risingwave/pull/10627
- [x] Covering Index selection for temporal join. https://github.com/risingwavelabs/risingwave/pull/11019
- [ ] Secondary Index for temporal join

**Comment by chenzl25** [comment]
@wsx-ucb As we have already supported the process time temporal join, let's perform a benchmark analysis comparing the efficiency of stream hash join and process time temporal join. BTW, we can give a demo for process time temporal join, such as joining a Kafka stream with a materialized view backed by MySQL CDC. I think it is a good use case for our website doc.
