### ISSUE TITLE
Tracking: binary format bugs and unimplemented features

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#8213]
- [x] #8041 
- [x] #7949 
- [ ] bug(frontend): pgwire binary response unimplemented for byte array
- [ ] bug(frontend): pgwire binary response unimplemented for decimal inf,-inf
- [ ] bug(frontend): pgwire binary response unimplemented for JSONB type

Possible motivations/users:
- https://github.com/risingwavelabs/risingwave/issues/7793

Please enable test cases in https://github.com/risingwavelabs/risingwave/blob/cb825f0f3f1611b8ef82daf032bc0f184fc9ac88/e2e_test/extended_mode/type.slt#L6-L19

**Comment by kwannoel** [comment]
Might be higher priority, if users query with `parameters` (requires extended query mode -> uses binary format) or some integrations require binary format (cr: @jon-chuang ).

https://www.postgresql.org/docs/current/protocol-overview.html#PROTOCOL-QUERY-CONCEPTS
