### ISSUE TITLE
Tracking: remove exchange after append-only source

### ISSUE THREAD

**Issue by shanicky** [risingwavelabs/risingwave#8225]
Due to the situation mentioned in the issue, we now need to remove the exchange that comes after the append-only source. Currently, the estimated tasks that need to be done are as follows:

- [x] Add a new serial type that reuses int64.
  - [x] Implement scalar type for serial. https://github.com/risingwavelabs/risingwave/pull/8327 
  - [x] Implement array type for serial. https://github.com/risingwavelabs/risingwave/pull/8357
  - [x] Implement logical type for serial. https://github.com/risingwavelabs/risingwave/pull/8392
- [x] Skipping hash for Serial type & Modify the plan generated by the frontend. https://github.com/risingwavelabs/risingwave/pull/8532 

Here are some possible issues that may arise:

For split, i.e., sources with a small number of partitions but huge traffic, a simple mv will result in limited compute capacity. For example, in a Kafka cluster with only 3 partitions but huge traffic, the parallelism of many fragments will be limited to 3.

Relevant links:

https://github.com/risingwavelabs/risingwave/issues/7353
https://github.com/risingwavelabs/risingwave/issues/7621

**Comment by xxchan** [comment]
Relevant link https://github.com/risingwavelabs/rfcs/pull/45

**Comment by fuyufjh** [comment]
Hi, can I close this ?

**Comment by shanicky** [comment]
> Hi, can I close this ?

Alright, let me close it now
