### ISSUE TITLE
Tracking: Issues of Longevity & Chaos Test

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#8248]
## Kernel Team

- [x] https://github.com/risingwavelabs/risingwave/issues/8125
- [x] #8270
- [x] #8321 

## Cloud Team

- [x] [CLOUD-973 longevity test: node exited (137) unexpectly](https://linear.app/risingwave-labs/issue/CLOUD-973/longevity-test-node-exited-137-unexpectly)
- [x] [CLOUD-974 longevity-test: etcd was shutdown expectedly](https://linear.app/risingwave-labs/issue/CLOUD-974/longevity-test-etcd-was-shutdown-expectedly)

## QA Team

- [x] https://github.com/risingwavelabs/risingwave-test/issues/257
