### ISSUE TITLE
Tracking: Hummock Block Format

### ISSUE THREAD

**Issue by Li0k** [risingwavelabs/risingwave#8252]
This issue tracks the progress of `Hummock Block Format` support in RisingWave kernel.

We plan to introduce two new features:
1. Flexible length encoding
2. Customized compression for `TableId` and `Epoch`

Any ideas and suggestions are welcome!

Related RFC: https://github.com/risingwavelabs/rfcs/pull/56

### Basic
- [ ] Statistical information for key_length and epoch_count in block / sst
- [ ] TableId compression on block level
- [ ] Flexible length rely on statistis and key_length
- [ ] `Epoch` compression on the bottom level (remove `Epoch` from encoding)

### Expand
- [ ] `Epoch` dictionary encoding
- [ ] Introduce dictionary encoding for the whole block when using `zstd`

**Comment by Li0k** [comment]
### epoch dictionary encoding

TLDR:
1. Introduces complexity and some performance degradation, with insignificant space savings
2. Version compatibility issues

https://github.com/risingwavelabs/risingwave/pull/8605#issuecomment-1475671213

**Comment by hzxa21** [comment]
Future work are tracked in separate issues.
