### ISSUE TITLE
Tracking: support Iceberg sink

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8280]
RisingWave is designed to be both a streaming database and a streaming engine so it also supports external sinks natively. RisingWave will only support the ingestion part but not the DDL commands (CREATE TABLE) or data querying. In short, it's merely a streaming ingestion engine.

This issue tracks the features required for the Iceberg sink.

Catalog support:
- [ ] Support using Hive Metastore as the catalog
- [x] Support HadoopCatalog
- [ ] Support using Glue as the catalog (medium-priority)
- [ ] Support using REST as the catalog (low-priority)

Nit:
- [ ] Support schema validation with case insensitive field name support

Feature required for RisingWave
- [ ] Support committer that takes the commit data of each parallelism and commit together
- [ ] Support batching across multiple checkpoint barriers.

**Comment by wenym1** [comment]
We may support timestamp data type after https://github.com/risingwavelabs/risingwave/issues/8299.
