### ISSUE TITLE
Tracking: sqlsmith query generation

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#8284]
Track: https://github.com/risingwavelabs/risingwave/issues/8220

High priority:
- [ ] Generation should not fail if query caused an unexpected error. https://github.com/risingwavelabs/risingwave/pull/8259
- [ ] Instead of writing to file later, since everything is already logged, just scrape queries from the logs.
That will clean up logic significantly.
- [ ] Generate 1000 queries for cron.

Low priority:
- [ ] Collect and aggregate queries with same / similar failing reasons. Not really needed now, but if more failing queries start being generated, this will be needed. Can use some fuzzy compare, since error messages may not match 1-1, but are highly similar.
- [ ] Collect total generated query / expected to measure how effective it is.
- [ ] Generation should run more times if insufficient queries generated. Currently sqlsmith generates sufficient queries, we can revisit if needed.
- [ ] Decouple generation and execution: Generate queries first, execute after.
- [ ] When executing, if a query causes a crash in the cluster:
   - Record the failing query
   - Restart the cluster
   - Re-run ddl + dml
   - Continue executing rest of queries.

**Comment by kwannoel** [comment]
I will add some docs to `sqlsmith/develop.md` later as well.

**Comment by kwannoel** [comment]
Added: https://github.com/risingwavelabs/risingwave/pull/10092/commits/826c692a31b3f221637b396ea69817d895789ef3
