### ISSUE TITLE
Tracking(streaming): EMIT ON WINDOW CLOSE

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#8348]
RFC: https://github.com/risingwavelabs/rfcs/pull/51

- [x] The EOWC framework:
  - https://github.com/risingwavelabs/risingwave/pull/8891
  - https://github.com/risingwavelabs/risingwave/pull/8963
  - https://github.com/risingwavelabs/risingwave/pull/9510
  - https://github.com/risingwavelabs/risingwave/pull/9622
  - https://github.com/risingwavelabs/risingwave/issues/9645
- Specialized implementations:
  - [x] GroupAgg
    - https://github.com/risingwavelabs/risingwave/pull/8750
    - https://github.com/risingwavelabs/risingwave/pull/9971
  - [x] OverWindow
    - https://github.com/risingwavelabs/risingwave/pull/9110
    - https://github.com/risingwavelabs/risingwave/pull/9429
  - [ ] GroupTopN
  - [ ] BatchSortAgg (reusing EOWC streaming agg in batch mode?)
  - [ ] EqJoin
  - [ ] [WindowJoin and IntervalJoin](https://github.com/risingwavelabs/risingwave/issues/18445)

**Comment by jon-chuang** [comment]
Hello, do we not support `EMIT ON WINDOW CLOSE` in `HopWindow`?

**Comment by hengm3467** [comment]
@st1page I understand the clause is not fully implemented, so it's ready to be documented. Correct? Thanks.

**Comment by richardchien** [comment]
> @st1page I understand the clause is not fully implemented, so it's ready to be documented. Correct? Thanks.

If document it, I guess we'd better mark it as an experimental feature.

**Comment by st1page** [comment]
> @st1page I understand the clause is not fully implemented, so it's ready to be documented. Correct? Thanks.

I think yes.

**Comment by fuyufjh** [comment]
https://github.com/risingwavelabs/risingwave-docs/pull/2586
