### ISSUE TITLE
Tracking: Store States as a Cell-based Relational Table

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#849]
This is to track the works related [Store States as a Cell-based Relational Table ](https://singularity-data.quip.com/tlLHAbb9VQF5/RFC-Store-States-as-a-Cell-based-Relational-Table). 
- [x] Implement the `CellBasedRowSerializer`
- [x] Implement the read/write interfaces of `CellBasedTable` struct.
- [x]  Implement  the get/write `StateTable`/`MemTable`  for read visibility.
- [x] #1201
- [x] Implement  the scan of relational table(`StateTableIter` )
- [x] #1206
- [x] Assign each state a table id in streaming scheduler. 
- [x] https://github.com/singularity-data/risingwave/issues/2811
- [x] Change the agg’s key space encoding and implement its read/write interfaces by CellBasedTable
- [x] Change the join’s key space encoding and implement its read/write interfaces by CellBasedTable: #2795
