### ISSUE TITLE
tracking: generated columns

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#8699]
- [ ] introduce generated columns
- [ ] proc_time
- [ ] handle generated column return type
- [ ] test against CREATE SOURCE / CREATE TABLE
- [ ] refine error messages.

**Comment by TennyZhuang** [comment]
Can we close the issue now?
