### ISSUE TITLE
Tracking: Materialized View on Materialized View

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#87]
There are still some work to make MV on MV run with new features that added these days.
- [x] Support parallel mview upstreams. #117 
- [x] Support barrier from meta. #88 
- [x] Support new meta store interfaces.
- [x] Implement `ChainNode` snapshot read based on conf change barrier epoch. #197 
- [x] Waiting table v2 for more bug reports. 🤣
