### ISSUE TITLE
Tracking: mathematical functions

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#8806]
https://www.postgresql.org/docs/current/functions-math.html

### Polymorphic

* [x] unary `+` / `-` for smallint / int / bigint / decimal / real / double
* [ ] `@` / `abs` for smallint / int / bigint / decimal / real / double (missing `@`)
* [x] binary `+` / `-` / `/` / `*` for various combinations
* [x] `%` / `mod` for smallint / int / bigint / decimal
* `gcd` / `lcm` for int / bigint / decimal
* [x] `~` / `&` / `|` / `#` for smallint / int / bigint
* [x] `<<` / `>>` for lhs smallint / int / bigint

### For decimal and double
* [ ] `round` / `trunc` / `ceil` / `ceiling` / `floor` (missing `trunc` / `ceiling`)
* `sign`
* `|/` / `sqrt`
* [ ] `exp` / `ln` / `log` / `log10` (missing decimal / `ln` / `log` / `log10`)
* [ ] `^` / `pow` / `power` (missing decimal)
* `width_bucket(operand, low, high, count)`

### For decimal
* `factorial(bigint)` -> decimal
* `div(decimal, decimal)` -> decimal
* `log(decimal, decimal)` -> decimal
* [x] `round(decimal, int)` -> decimal
* `trunc(decimal, int)` -> decimal
* `min_scale(decimal)` -> int
* `scale(decimal)` -> int
* `trim_scale(decimal)` -> decimal

### For double
* `||/` / `cbrt`
* `degrees` / `radians`
* [x] `pi`
* `sin` / `cos` / `tan` / `cot` / `asin` / `acos` / `atan` / `atan2`
* `sind` / `cosd` / `tand` / `cotd` / `asind` / `acosd` / `atand` / `atan2d`
* `sinh` / `cosh` / `tanh` / `asinh` / `acosh` / `atanh`

### Impure
* `random` / `setseed`
