### ISSUE TITLE
Tracking: string functions

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#8831]
### Basic

* [x] `bit_length` / `char_length` / `character_length` / `octet_length` / `length`
* [x] `position` / `strpos`
* [x] `||` / `concat` / `concat_ws`
* [x] `lower` / `upper` / `initcap`
* [x] `overlay(string PLACING newsubstring FROM start [FOR count])`
* [ ] `substring` / `substr` / `left` / `right` (missing `left` / `right`)
* [ ] `trim` / `btrim` / `ltrim` / `rtrim` (missing `btrim`)
* [x] `lpad` / `rpad`
* [x] `repeat`
* [x] `reverse`
* [x] `replace`
* [ ] `translate` (missing frontend part)
* [x] `split_part`
* [ ] `starts_with` / `^@` (missing `^@`)
* [ ] `string_to_array`

### Misc

* [x] `ascii` / `chr`
* [x] `to_hex`
* `quote_ident` / `quote_literal` / `quote_nullable` / `parse_ident`
* [x] `md5`

### RegExp

* `regexp_like`
* `regexp_count`
* `regexp_instr`
* `regexp_substr`
* [x] `regexp_match`
* `regexp_replace`
* `regexp_split_to_array`

### Formating

* `format`

### Encoding related

* `pg_client_encoding`
* `normalize` / `is normalized`
* [x] `to_ascii`
* `unistr`

### Aggregate Function

* [x] `string_agg`

### Set Returning Function

* `string_to_table`
* [x] `regexp_matches`
* `regexp_split_to_table`

**Comment by BanBuDu0** [comment]
I finished encdec some time ago.
I think I will keep contributing all of the bytea functions one by one, if no one is doing the same work.
