### ISSUE TITLE
Tracking: date/time functions

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#8849]
https://www.postgresql.org/docs/current/functions-datetime.html

### Arithmetic operators

* [x] #924

### Basic

* `age(timestamp, timestamp)` -> interval
* `age(timestamptz, timestamptz)` -> interval
* `date_bin(interval, timestamp, timestamp)` -> timestamp
* `date_bin(interval, timestamptz, timestamptz)` -> timestamptz
* [x] `date_trunc(field, interval)` -> interval
* [x] `date_trunc(field, timestamp)` -> timestamp
* [x] `date_trunc(field, timestamptz, zone)` -> timestamptz
* [ ] `date_part` / `extract`
* [x] `AT TIME ZONE`
* [x] `to_timestamp(double)` -> timestamptz
* `justify_days` / `justify_hours` / `justify_interval`
* `make_date` / `make_timestamp` / `make_timestamptz` / `make_time` / `make_interval`
* `OVERLAP`
* `isfinite`

### Current

* [x] `current_timestamp` / `transaction_timestamp()` / `now()` -> timestamptz
* `localtimestamp` -> timestamp
* `current_date` -> date / `age(timestamp)` -> interval / `age(timestamptz)` -> interval
* `localtime` -> time

Nonstandard:
* `statement_timestamp()` -> timestamptz
* `clock_timestamp()` -> timestamptz / `timeofday()` -> varchar
* `'now'` / `'today'` / `'tomorrow'` / `'yesterday'`

### No support

* `pg_sleep`
* `current_time` -> timetz
* `current_time(int)` -> timetz

**Comment by matanper** [comment]
Is it possible to add to the list [date_diff](https://www.w3schools.com/sql/func_sqlserver_datediff.asp)?
Current alternative is taking the epoch and then subtracting by given unit you want:
```sql
(EXTRACT(EPOCH FROM date2 - date1) / 86400)::int
```

**Comment by maingoh** [comment]
`date_bin` seem to be supported https://github.com/risingwavelabs/risingwave/pull/21559 ?
