### ISSUE TITLE
Tracking: Dedicated Batch Serving Cluster

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#8940]
RFC: https://github.com/risingwavelabs/rfcs/blob/eric/dedicated-serving-cluster/rfcs/0014-dedicated-serving-cluster.md

We'll disable barrier read and only support reading from checkpoint. We ensure freshness by increasing checkpoint frequency.
We don't adopt approach 1 or approach 3, because we want different SLAs for streaming/serving cluster.

- [x] use serving cluster in frontend #9040
- [x] batch benchmark: read-write workload. 
- [x] improvement: better vnode mapping reorganization #10004
- [x] improvement: availability #10328
