### ISSUE TITLE
Tracking(perf): optimize streaming aggregator

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#9101]
We have seen the `StreamingFoldAgg::apply_batch_concrete` can cost about 20% of CPU time. So when the workload's locality is good and the cache-miss rate is low, the aggregation computation might be the bottleneck.
Because the StreamingFoldAgg is just the computation logic and without the state IO or other influence, it's benchmark and performance analyze is easier than the whole hashAgg https://github.com/risingwavelabs/risingwave/issues/5683

- [x] set benchmark for the `StreamingFoldAgg` https://github.com/risingwavelabs/risingwave/pull/9185?notification_referrer_id=NT_kwDOAm8F97M2MTU3MzQxNTkyOjQwODMwNDU1#event-9020552808
- optimize the selectivity situation
  - reference https://db.cs.cmu.edu/papers/2021/ngom-damon2021.pdf just to refer, we still need do ourselves benchmark and experiments
   - [x] make a new "ones" iter or just to use `next_set_bit` to implement the aggregator's logic and compare it with the current iterator. in other words, the new iter's definition will be `ones() -> Iter<Item = usize>` which iter all the index where is set `true`. https://github.com/risingwavelabs/risingwave/pull/9246
   - [x] optimize the `next_set_bit`. currently it just call the `is_set_unchecked` and check one by one, we should skip the blocks and use some bit operation to find next one in the same block. https://lemire.me/blog/2018/03/08/iterating-over-set-bits-quickly-simd-edition/ https://github.com/risingwavelabs/risingwave/pull/9278
