### ISSUE TITLE
Tracking: Support Grouping Sets

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#9284]
### Is your feature request related to a problem? Please describe.

Grouping sets will allow us to efficiently perform group-by operations on multiple columns at once, without having to resort to cumbersome subqueries or union statements.

With grouping sets, we will be able to specify multiple grouping columns in a single query, resulting in a more concise and readable code. This feature will benefit our data analysts and business intelligence users, allowing them to easily manipulate and analyze complex datasets.

[PostgreSQL Grouping Sets](https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-GROUPING-SETS)

### Describe the solution you'd like

We can support `CUBE` and `ROLLUP` later because it is a syntax sugar for grouping sets. Grouping sets can be implemented by rewriting the grouping sets into a `Expand` operator. In this way, we can utilize the existing `ExpandExecutor` to support grouping sets.

Example:

```sql
create table items_sold (brand varchar, size varchar, sales int);
insert into items_sold values ('Foo', 'L', 10),('Foo', 'M', 20),('Bar', 'M', 15),('Bar', 'L', '5');
SELECT brand, size, sum(sales) FROM items_sold GROUP BY GROUPING SETS ((brand), (size), ());

Use expand to turn a row into three rows (the last column is a flag column).
('Foo', 'L', 10) -> (null, 'L', 10, 1), ('Foo', null, 10, 2), (null, null, 10, 3)
Group by `brand`, 'size', and the flag column.
That's it!
``` 

> GROUPING ( group_by_expression(s) ) → integer
> Returns a bit mask indicating which GROUP BY expressions are not included in the current grouping set. Bits are assigned with the rightmost argument corresponding to the least-significant bit; each bit is 0 if the corresponding expression is included in the grouping criteria of the grouping set generating the current result row, and 1 if it is not included.

BTW, we also need to implement the `GROUPING()` aggregation function, which can be implemented by `CASE WHEN` expressions on the flag column after aggregation.

### Tracking

- [x] Support (only one) grouping sets in group-by clauses. Convert grouping sets into a plan node. Support a optimizer rule to convert an agg with grouping sets into an agg without grouping sets by using expand operators. https://github.com/risingwavelabs/risingwave/pull/10807
- [ ] ~Support multi grouping sets expressions in group by clauses and it can interleave with group-by columns.~
- [x] Support Cube. https://github.com/risingwavelabs/risingwave/pull/11262
- [x] Support Rollup. https://github.com/risingwavelabs/risingwave/pull/11119
- [x] Support Grouping agg call. https://github.com/risingwavelabs/risingwave/pull/11006
