### ISSUE TITLE
Tracking: Hummock Integration (availability, vacuuming, etc..)

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#93]
- [x] https://github.com/singularity-data/risingwave-dev/issues/384
- [x] wait_epoch and https://github.com/singularity-data/risingwave-dev/issues/365
- [x] https://github.com/singularity-data/risingwave-dev/issues/372
- [x] https://github.com/singularity-data/risingwave-dev/issues/546
- [x] Implement vacuum. https://github.com/singularity-data/risingwave-dev/issues/751
- [x] https://github.com/singularity-data/risingwave-dev/issues/737
- [x] https://github.com/singularity-data/risingwave-dev/issues/336
- [x] https://github.com/singularity-data/risingwave-dev/issues/661
- [x] https://github.com/singularity-data/risingwave/issues/1112
- [x] https://github.com/singularity-data/risingwave-dev/issues/763
