### ISSUE TITLE
Tracking(streaming): executor should evict cache more frequently

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#9341]
- [x] https://github.com/risingwavelabs/risingwave/pull/9346
- [ ] agg distinct `ColumnDeduplicater`
   - [ ] call update_epoch
   - [ ] evict per chunk 
- [ ] append only distinct `DedupCache`
   - [ ] call update_epoch
   - [ ] evict per chunk 
- [ ] `HashAgg` evict per chunk

**Comment by lmatz** [comment]
Is it possible that it can hurt performance?

**Comment by st1page** [comment]
> Is it possible that it can hurt performance?

I think it should not :thinking: especially for the nexmark. But we can see it later. because the `evict` is just CPU computing, we can just see if it will appear in the flamegraph to see its influence.

**Comment by st1page** [comment]
closed by https://github.com/risingwavelabs/risingwave/pull/9346
