### ISSUE TITLE
Tracking: state_store benchmark roadmap.

### ISSUE THREAD

**Issue by Sunt-ing** [risingwavelabs/risingwave#95]
Reference: 
- Design note: https://singularity-data.larksuite.com/docs/docusUkBFoG9B5CwOruT68Sx65f
- End to end benchmark roadmap: https://github.com/singularity-data/risingwave/issues/2232

Tracking:
Stage one (target 2022.1.5):
- [x] A command line executable tool `ss_bench` with following capabilities:
	- Configurable backends: (`InMemoryStateStore`, hummock+s3, hummock+minio, `TikvStateStore`, `RocksDBStateStore`)
	- Configurable hummock options: (SST size, block size, bloom filter, default bucket, checksum algo, etc..)
	- Configurable data sizes: (key length/value length).
	- Configurable mode: (simple get/ simple scan / simple write_batch / mixed).

Stage two (target 2022.1.10):
- [ ] Launch Premetheus endpoint to expose internal storage counters.
- [x] Configurable concurrencies: (multithreaded `get`/`scan`/`write_batch` operations).
- [ ] Review performance with ss_bench.

Stage three: more likely patterns as our internal states:
- [ ] Sequencial writes within single key space.
- [ ] Random writes within single key space.
- [ ] (Sequencial, random) x (writes, deletes, updates) within single key space.
- [ ] (Sequencial, random) x (writes, deletes, updates) x (single key space, multiple key spaces)
- [ ] (Tiered, Leveled compaction) x (Sequencial, random ingestion) x (single, multiple key space)
