### ISSUE TITLE
Use remote catalog service

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/risingwave#958]
* [x] singularity-data/risingwave-legacy#2459
* [x] singularity-data/risingwave-legacy#2460
* [x] singularity-data/risingwave-dev#957
