### ISSUE TITLE
Tracking(sink datatype mapping): Type missing when sink to MySQL, PostgreSQL or TiDB

### ISSUE THREAD

**Issue by wugouzi** [risingwavelabs/risingwave#9603]
Currently, there are some types in RisingWave that don't have counterparts in MySQL, PostgreSQL or TiDB, and we need some workaround for Debezium sink and jdbc sink:
- [ ] `Interval` for MySQL and TiDB
- [ ] `struct` for MySQL, and TiDB
- [ ] `List` for MySQL and TiDB
- [ ] `Bytea` for MySQL and TiDB
- [ ] `Serial` for MySQL and TiDB
- [ ] `Int256` for MySQL, PostgreSQL and TiDB (reject sink for this type)
