### ISSUE TITLE
Tracking(sink datatype mapping): sink type mismatch for jdbc and Debezium

### ISSUE THREAD

**Issue by wugouzi** [risingwavelabs/risingwave#9604]
When doing sinking, RisingWave type may need to be mapped to different types based on type of sink(Debezium, jdbc, etc.) and target DBMS (MySQL, PostgreSQL, etc.). Below is a list of things that need to be done.
- [x] For `Date`, Debezium maps it to `int32`, but jdbc requires a string.
- [x] For `Timestamp`, Debezium maps it to `int64`, but jdbc requires a string. Related issue: #9376 
- [ ] Potential problem after #9603 
- [x] #9918
- [x] #9919

**Comment by StrikeW** [comment]
> - [ ] For `Date`, Debezium maps it to `int32`, but jdbc requires a string.

I think you mean the JSON payload of Jdbc sink, after #9957 JDBC sink can support Date.

> - [ ] For `Timestamp`, Debezium maps it to `int64`, but jdbc requires a string. Related issue: #9376 

#9957 added a flag to control how Sink converts the `Timestamp` in JSON format:
https://github.com/risingwavelabs/risingwave/blob/487c4c60c584e1e8d603b0a6d2af4632aa869a47/src/connector/src/sink/mod.rs#L340-L342

But I think we can use the string representation to unify the implementation of Kafka sink and JDBC sink (JSON payload). IMO, we don't need to stick to the data type mapping of the [debezium‘s Postgres connector](https://debezium.io/documentation/reference/2.1/connectors/postgresql.html#postgresql-timestamp-type). Making the output JSON format consistent with Debzium JSON is enough. cc @neverchanje

**Comment by hzxa21** [comment]
The remaining work is tracked in #9603. I will close this issue for now. Feel free to reopen if needed.
