### ISSUE TITLE
Tracking: Automating Kernel backwards compatibility tests

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#9973]
Tracker:

High priority:
- [x] Basic framework with just inserts on base table + mview. https://github.com/risingwavelabs/risingwave/pull/10190
- [x] Test deletes as suggested by @lmatz: https://github.com/risingwavelabs/risingwave/pull/10190#pullrequestreview-1468210163.
- [x] Test updates.
- [ ] Test kafka (GA support we need to test this!) 
   - Blocked by https://github.com/risingwavelabs/risingwave/pull/10413
   - And https://github.com/risingwavelabs/risingwave/issues/9437
- [x] ~Support old and new node compat. Currently cloud does rolling upgrade, multiple nodes in parallel. This means in kernel we need to support backwards compat between nodes. To test that, we need to test all permutations for backwards compat: `new-fe->old-meta + old-compute`, `new-meta->old-fe+old-compute`, `new-compute->old-meta+old-fe`.~ Cloud should not do rolling update. Should be full cluster teardown and setup.
- [ ] Get the version automatically. For example, if current (unreleased) version is v1.2, and released version is `v1.1`, we should test backwards compatibility with v1.0. That can be done by decrementing the minor version by 1, or if it is `0`, we need to query `git` for the previous major branch.

Also important:
- [ ] Test nexmark
- [ ] Test tpch
- [ ] Reduce compilation time

---

Initial suggestion by @fuyufjh:
> My basic idea was: starting a new-version cluster over the config/metadata/s3 files of an old-version cluster, to see whether the new cluster can work properly

---

We can run it over a sample of nexmark + tpch queries.
IMO this should be run over every PR to catch breaking changes.

If this is too expensive, we can trigger it when `diff of source files > 1000`.
We also can provide a label to opt in (`test-breaking-changes`).

If breaking changes are inevitable, we should add `breaking-changes` tag, so it wouldn't block the PR.

Further suggestions welcome!

**Comment by lmatz** [comment]
@cyliu0 has manually tested a few times, any advice/suggestion?

**Comment by cyliu0** [comment]
Now we focused on two aspects of the upgrading test. The first one is functional compatibility, we will test all the critical features of RW like source, MV, and sink. The second one is performance, we will compare the performance before and after the upgrade.
For automation, I'd like to have an image tag triggered automation test which we can specify the original and upgrade image tag to perform the upgrade test. And we need the health check tool to make sure the cluster is heathy before and after the upgrade. And it's very nice if we can run this in k8s. And the test should be easily to add new steps.

**Comment by kwannoel** [comment]
> we will test all the critical features of RW like source, MV, and sink after the upgrade. 

Do you maintain a test query set?

**Comment by cyliu0** [comment]
Actually I'm using the nexmark and tpch just like your suggestion
